### ISSUE TITLE
Add acknowledge pattern (like socket.io)

### ISSUE THREAD

**Issue by DutchKevv** [RIAEvangelist/node-ipc#101]
**Feature Request**

With (for example) socket.io it is possible to do `socket.emit('type', data, callback);`

Whenever the last param is a function, is makes it a callback function.

Internally socket.io just increments a counter, sends it `{ack: ++this._ackCounter}` over the message along with event type and event data, stores it in `this._acks []`.. Whenever the client/other-end sees a `{ack:number}` set, it gives out an extra function as last parameter in socket.on('message', data, cb); The receiver should call that function with its result and that is send back to caller.

And the caller triggers the stored `this._ackes[id]` cb function whenever the results come back with that same `{ack:id}`..

`ipc.of.cache.emit('get', {from: 0, until: now}, function(result){});`

This also allows (with a little wrapper around the emit function) to do a promise type of coding that saves a lot of boilerplate code.

---

Promise based wrapper

```
class extends IPC {

     emit(type, data, waitForCallback) {

        return new Promise((resolve, reject) => {

            let cb = waitForCallback ? (err, result) => err ? reject(err) : resolve(result) : null;

            super.emit(type, data, cb)

            if (!waitForCallback)
                resolve();
        });
    }
}
```

`ipc.of.cache.emit('get', {from: 0, until: now}, true).then(result).catch(error)`

async-await

`let data = await ipc.of.cache.emit('get', {from: 0, until: now}, true)`

disabled (no callback), same as now

`ipc.of.cache.emit('get', {from: 0, until: now})`

**Comment by RIAEvangelist** [comment]
this must be optional and opt in only. It will slow things down significantly.

**Comment by RIAEvangelist** [comment]
It is one of the reasons I use `ws` instead of `socket.io`

**Comment by RIAEvangelist** [comment]
remember every operation that happens, even checking the config vars slows things down.

**Comment by DutchKev** [comment]
Aah yeaah I understand.. Guess there would be 2 extra steps involved, one when sending to check if last parameter is a function and one when receiving to check if the `{ack: id}` is set.. All other steps would only be fired when one of above conditions is fulfilled and would have been done anyway by the end user if he wanted to listen for callback events.

I will finish the previous PR and will create one for this after that... My personal project has a CSV file with about 40 million rows, that are being send over to a worker child.. So I wil split it line by line to make it a test case for performance hits

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
