### ISSUE TITLE
IP Address(es) vs Host names

### ISSUE THREAD

**Issue by mrb1090** [RIAEvangelist/node-ipc#104]
Curious if node-ipc can be configured with a machine's IP address vs host name?

i.e. ipc.config.host = '192.168.1.100'

Thanks,

Mike B.

**Comment by mrb1090** [comment]
Non-issue.  Confirmed IP addresses work as well...

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
