### ISSUE TITLE
Unix Abstract Sockets

### ISSUE THREAD

**Issue by ArsalanDotMe** [RIAEvangelist/node-ipc#107]
How can I get this library working with Unix abstract sockets? Those have a null character at the start of their name.

**Comment by RIAEvangelist** [comment]
im not sure, i have not tried using a null char, have you tried putting the escaped null char at the beginning?

**Comment by RIAEvangelist** [comment]
i have not implemented abstract sockets as a specific implementation yet.

**Comment by RIAEvangelist** [comment]
any updates?

**Comment by ArsalanDotMe** [comment]
Adding null char to the beginning does not work. The only way I could make
it work was through another node module aptly named [abstract-socket](
https://www.npmjs.com/package/abstract-socket). It has its own native
extension to make abstract sockets work although the implementation is very
small and simple.

**Comment by RIAEvangelist** [comment]
I believe they are natively supported now since v0.12 that module was mostly useful in vrsion 0.10 and earlier. I will look into this as time becomes available.

Thanks for the update.

**Comment by ArsalanDotMe** [comment]
BTW, I ran my own tests and this is also something you can test on your own quite simply. If you want, I'll send you some toy C++ server and node client sources. Abstract sockets are still not supported in node even on the current LTS (v6.x).

See this issue: https://github.com/joyent/libuv/issues/797

**Comment by RIAEvangelist** [comment]
Yes, that would be awesome thanks :)

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
