### ISSUE TITLE
Remove node-cmd from package.json dependencies

### ISSUE THREAD

**Issue by mrvini** [RIAEvangelist/node-ipc#108]
Please remove node-cmd from the package dependencies, it's not used by the the module, but rather carried some extra weight of the overall package

**Comment by RIAEvangelist** [comment]
Thanks, it's needed for the testing suite, so I moved it to devDeps

released in [8.10.2](https://github.com/RIAEvangelist/node-ipc/releases/tag/8.10.2)

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
