### ISSUE TITLE
How to start the ipc server on child process?

### ISSUE THREAD

**Issue by VooVoo01** [RIAEvangelist/node-ipc#109]
I try to organize direct communication between child processes (wo parent).
But have an error when trying _ipc.server.start()_ on the child processes via Windows Sockets: 

             Error: write ENOTSUP
                 at exports._errnoException (util.js:1022:11)
                 at ChildProcess.target._send (internal/child_process.js:662:20)
                 at internal/child_process.js:498:16
                 at Array.forEach (native)
                 at ChildProcess.<anonymous> (internal/child_process.js:497:13)
                 at emitTwo (events.js:111:20)
                 at ChildProcess.emit (events.js:191:7)
                 at process.nextTick (internal/child_process.js:752:12)
                 at _combinedTickCallback (internal/process/next_tick.js:67:7)
                 at process._tickCallback (internal/process/next_tick.js:98:9)

Is it possible to start the ipc server on child processes on Windows?

**Comment by RIAEvangelist** [comment]
I don't know how you are starting the child process, but it seems it does not have support for sockets.

If you are doing this to utilize more cores or threads to make your program faster, I suggest starting sibling processes through the system interface. You could use something like `node-cmd` to do this.

btw childprocess in node is slow. I would spawn a whole new process.

**Comment by VooVoo01** [comment]
I'm starting the child processes using the cluster module with _cluster.fork()_ command. Then make IPC servers on every worker and organize direct communication between workers, without master process.
I changed _ipc.iconfig.id_ on every worker and left other setting by default. 

It works fine on Linux, but makes above error on Windows.
There are simple example in attached file.
[cluster2.zip](https://github.com/RIAEvangelist/node-ipc/files/680005/cluster2.zip)

ps
node-ipc server/client works right on Windows when I started sibling processes through the system interface.
But cluster more convenient, because it will be TCP and WebSocket server.

**Comment by RIAEvangelist** [comment]
Appologies on the delay in responding I am back now and will have a look at this unless you have any further information.

**Comment by VooVoo01** [comment]
I did not find the solution and have refused from Windows :)
It works well on Linux.

**Comment by RIAEvangelist** [comment]
:1st_place_medal:  looks like this is a known issue on windows when using posix sockets.

Thanks for the update!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
