### ISSUE TITLE
add ipc.server.of for process grouping and automatic client registration

### ISSUE THREAD

**Issue by zaksmok** [RIAEvangelist/node-ipc#110]
Hello. 
I see the code for adding websocket to "server.of" in branch v8.* (https://github.com/RIAEvangelist/node-ipc/blob/v8.x/dao/socketServer.js).

I don't see that code in latest release? Why there are different versions and newer one doesn't have code for server.of?

**Comment by RIAEvangelist** [comment]
Can you confirm this is still an issue for you?

**Comment by zaksmok** [comment]
Yes. I just run in new empty folder `npm install node-ipc`
 it downloaded `node-ipc@8.10.2". 

In the source code of `node_modules\node-ipc\dao\socketServer.js` i don't see any code responsible for handle handshake. After downgrading to `node-ipc@8.9.2` the code is visible.

**Comment by RIAEvangelist** [comment]
Can you confirm that the expected functionality does not work? Or are you just saying you don't see it in the code?

**Comment by zaksmok** [comment]
Expected functionality is not working. I debugged code and `server` variable doesn't have `of` key. That's why I cannot comunicate to specific client using it's ID.

**Comment by RIAEvangelist** [comment]
are you on hangouts?

I'm not sure what you are trying to do. as far as I remember of has always been on the ipc object not the server object. All of the tests and examples are working.

if you are on hangouts hit me up @ the email on my profile https://github.com/RIAEvangelist

**Comment by RIAEvangelist** [comment]
for posterity sake, @zaksmok and I spoke on hangouts about this and he was referring to some rejected code from the v8.x branch.

However he did bring up some really good points and we came up with an update for v9.0.0 which will include registration of client connections to server groups based on ipc.config.id

This should make load balancing super simple by just spinning up multiple instances of the same node client process. :tada: :balloon: 

will be adding automatic client registration and ` ipc.server.of.myAmazingClient.emit ` as a local broadcast to all clients registered under the same ipc.config.id.

**Comment by RIAEvangelist** [comment]
@zaksmok 

updates should be in place.  
I also updated the example servers to use the socket.id in the logs. As well as removed id from all of the messages.
  
I will have to make some new examples and update the tests yet, but everything should be working on that branch. Some of the tests are failing, but after looking at them they need to be re-written a bit anyway. The QA that wrote them was less than stellar... clearly. And will have to do documentation too.

give the v9.x branch a go please.

server can now emit to a single client or an array of clients.  

so 
    
     server.emit(server.of.ClientArray,'a',{a:1});
    //and
    server.emit(clientSocket,'a',{a:1});
     

should work

**Comment by zaksmok** [comment]
great, thanks for your time!

**Comment by RIAEvangelist** [comment]
almost ready?

**Comment by zaksmok** [comment]
I think we should add function to autosend client ID after connecting. In current implementation user will have to manually emit his id. Can you look at this?

**Comment by RIAEvangelist** [comment]
not everyone wants id to be in their messages. this module is meant to be fast. I think the user organizing their sockets the way they want is OK when they want it. doing when they do not want it is just extra overhead.

**Comment by RIAEvangelist** [comment]
PR almost ready to merge, just need to document the `ipc.server.of` and `ipc.server.of[id].broadcast`

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
