### ISSUE TITLE
IPC message queues

### ISSUE THREAD

**Issue by pocketmax** [RIAEvangelist/node-ipc#114]
Does this package use IPC message queues? i.e. to list the queues "ipcs -q"

**Comment by RIAEvangelist** [comment]
Of you want queues you can use sync or do confirmation events.

The event lists are available on your ipc instantiation if you want to see
them.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
