### ISSUE TITLE
Socket is never created

### ISSUE THREAD

**Issue by birjolaxew** [RIAEvangelist/node-ipc#117]
Using code:

```javascript
let ipc = require("node-ipc");

ipc.config.id = "test";
console.log("Serving");
ipc.serve(()=>{
    console.log("Served");
});
ipc.server.on("error", (err)=>{
    console.error(err);
});
```

I get the following output:

```bash
$ node test-ipc.js
Serving

```

No error is logged, no socket is created in `/tmp/`, process ends immediately.

OS: Arch Linux  
nodejs@v7.10.0
node-ipc@9.0.1

**Comment by birjolaxew** [comment]
Might be a good idea to call `.start` :P Sorry about that

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
