### ISSUE TITLE
Add option for socket permissions

### ISSUE THREAD

**Issue by birjolaxew** [RIAEvangelist/node-ipc#118]
When serving from a script that's run as `root`, all clients must be run as `root` too, or they'll get an `EACCESS` error.

It would be neat if we could set the permissions of the created socket, so we can allow all users to connect as clients.

**Comment by RIAEvangelist** [comment]
Could you use node-cmd for this?

**Comment by birjolaxew** [comment]
I can change the permissions manually using `fs.chmod`, but that requires me to know the path to it (eg. [this magic conversion](https://github.com/RIAEvangelist/node-ipc/blob/master/dao/socketServer.js#L306-L308)).

This could be eased by exposing the path, but I'd still consider it a responsibility of the module.

**Comment by RIAEvangelist** [comment]
I believe the ` magic port ` is exposed by that code you linked to as : ` ipc.path ` once the server is opened just fyi ;)

**Comment by RIAEvangelist** [comment]
allowing

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
