### ISSUE TITLE
Does rawBuffer also add delimiter?

### ISSUE THREAD

**Issue by DutchKevv** [RIAEvangelist/node-ipc#119]
Hi there,

At my project I'm converting all ipc communication to binary streams (rawBuffer).

For small messages I get it to work just fine, but as soon as messages get bigger (> 300-400 characters) the buffer seems to get concatenated/changed. 

I place an int32 with the total length value at the beginning of every buffer. But this is corrupted on bigger messages, although if I do to toString() on the buffer I can see all other binary is fine. 

I also check for the delimiter and can find it, but still if I slice the buffer at the delimiter point, the first bytes are still changed. I also wonder if that is really safe to check when you send a binary buffer, because at some time in that binary buffer it could still match the configured delimiter by accident? 

Thanks!

**Comment by RIAEvangelist** [comment]
You can store your buffer and concat them then slicing the buffer once you
have the appropriate length.

**Comment by DutchKevv** [comment]
Thanks

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
