### ISSUE TITLE
Server.broadcast not exposed in the type defintions

### ISSUE THREAD

**Issue by JuergenGutsch** [RIAEvangelist/node-ipc#123]
Hi All,

the API exposed in the type definitions on https://www.npmjs.com/package/@types/node-ipc is not complete. 
Wo is responsible for that type definitions file?

I miss the Server.broadcast method

**Comment by RIAEvangelist** [comment]
That is a 3rd party service. It looks like that is missing *ALL* the types. would you like to contribute a type def file for that service?

**Comment by JuergenGutsch** [comment]
I thought you provided the type defs :) 
In that case I'm going to complete the type def and add it to DefinetlyTyped repo (https://github.com/DefinitelyTyped/DefinitelyTyped)
Thanks :)

**Comment by RIAEvangelist** [comment]
awesome thanks @JuergenGutsch ! :balloon:

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
