### ISSUE TITLE
How to serve *only* locally?

### ISSUE THREAD

**Issue by imeckler** [RIAEvangelist/node-ipc#124]
Is there a way to make an IPC server only serve to clients on the same machine? Does `ipc.serve` do this? The documentation at [here](http://riaevangelist.github.io/node-ipc) makes it seem like `ipc.serve` also serves to the network, although the documentation [here](https://github.com/RIAEvangelist/node-ipc#serve) makes it seem like it does only serve locally.

**Comment by RIAEvangelist** [comment]
if you use `unix sockets` they are only local.

if you want to use [TCP or UDP sockets](https://github.com/RIAEvangelist/node-ipc#servenet) you can set the host to localhost or 127.0.0.1 or any othe IP you want. Setting the IP to 0.0.0.0 will make it public for any domain or IP that is pointed at the machine.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
