### ISSUE TITLE
Mistake inside handling event "on error"

### ISSUE THREAD

**Issue by EdikDolynskyi** [RIAEvangelist/node-ipc#125]
I have found the mistake inside function `startServer()` on handling event "on error". Log error and publish  doesn't work correct (socketServer.js:292)

```
this.server.on(
    'error',
    function(err){
	this.log('server error',err);
	this.publish(
	    'error',
	    err
        );
    }
);
```

Probably, we should bind `this` to callback and  there should be something like this:
```
this.server.on(
    'error',
    function(err){
	this.log('server error',err);
	this.publish(
	    'error',
	    err
        );
    }.bind(this)
);
```

Could you please fix it as soon as possible?

**Comment by RIAEvangelist** [comment]
Can you provide some code i can test this with?

Examples semm to be logging correctly.

![screenshot from 2017-08-15 14-17-09](https://user-images.githubusercontent.com/369041/29336996-a07c4e6a-81c4-11e7-8b73-8d22eed72e57.png)

**Comment by RIAEvangelist** [comment]
![screenshot from 2017-08-15 16-22-05](https://user-images.githubusercontent.com/369041/29340826-e7ded316-81d5-11e7-8d06-4f2d91b1f0a8.png)

**Comment by RIAEvangelist** [comment]
@EdikDolynskyi can you please provide some code I can use to confirm your issue?

**Comment by EdikDolynskyi** [comment]
@RIAEvangelist I am sorry, I have used node-ipc inside my app so it is difficult to show an example. But an error related to this issue appears when I call `ipc.server.start()`  inside callback on event `"disconnect"`. 

````
ipc.of.myApp.on(
	'disconnect',
	function(){
		ipc.config.id   = 'myApp';
		ipc.config.retry= 1500;
		ipc.config.maxRetries = 0;

		ipc.serve(
			...
		);
		ipc.server.start();
	}
);
````
Error:
[![Screenshot from Gyazo](https://gyazo.com/42c8704dab2ff76e51f14de9619b997a/raw)](https://gyazo.com/42c8704dab2ff76e51f14de9619b997a)

The error appeared very rarely, but I can reproduce if I call `ipc.server.start()` twice inside callback on event "on disconnect".

I hope it will help you.

**Comment by RIAEvangelist** [comment]
@EdikDolynskyi awesome! Thank you :+1:

**Comment by RIAEvangelist** [comment]
@EdikDolynskyi can you make sure you are on the latest? It looks like the code you are suggesting is already inplace. I think your version may be old.

![screenshot from 2017-08-25 01-43-16](https://user-images.githubusercontent.com/369041/29706518-ee7cc968-8936-11e7-8290-f2ea4376e9af.png)

**Comment by RIAEvangelist** [comment]
@EdikDolynskyi please let me know if your version was infact the bug or not.

**Comment by EdikDolynskyi** [comment]
@RIAEvangelist current version of my installed `node-ipc` is "9.0.1"

**Comment by EdikDolynskyi** [comment]
@RIAEvangelist Oh, I see, you had two more releases) Is it fixed already?

**Comment by RIAEvangelist** [comment]
@EdikDolynskyi I'll check `v9.0.1`

**Comment by EdikDolynskyi** [comment]
@RIAEvangelist It is not necessary, I found it was fixed on May 19, 2017, and released at version `9.1.0` a month ago. Thanks!

**Comment by RIAEvangelist** [comment]
@EdikDolynskyi yes this was fixed in `9.1.0` by @atiertant

**Comment by RIAEvangelist** [comment]
welcome ;) :tada:

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
