### ISSUE TITLE
Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by ioncreature** [RIAEvangelist/node-ipc#127]
Hi there!

I faced with `node-ipc` unhandled exception after running only client code:

```js
const Ipc = require('node-ipc').IPC;

const ipc = new Ipc();
ipc.config = {
    id: 'sock',
    appspace: 'ws.',
    silent: true,
    socketRoot: __dirname + '/'
};

ipc.connectTo(ipc.config.id, () => {
    log('Started');
});

const ipcClient = ipc.of[ipc.config.id];

ipcClient.on('connect', () => {
    log('Сonnected');
});

ipcClient.on('disconnect', () => {
    log('Disconnected');
});

ipcClient.on('error', error => {
    log('Socket error', error);
});

setInterval(() => {
    log('Send message to server');
    ipcClient.emit('message', {this: 'is', my: 'message'});
}, 1000);
```

I expect to receive `Error: This socket is closed` to `error` event listener but got unhandled exception:
```
TypeError: Cannot read property 'log' of undefined
    at Socket.<anonymous> (/Users/ioncreature/repo/test/node_modules/node-ipc/dao/client.js:152:19)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at onwriteError (_stream_writable.js:386:12)
    at onwrite (_stream_writable.js:414:5)
    at Socket.destroy (internal/streams/destroy.js:12:7)
    at Socket._writeGeneric (net.js:721:10)
    at Socket._write (net.js:781:8)
    at doWrite (_stream_writable.js:371:12)
    at writeOrBuffer (_stream_writable.js:357:5)
```

The same error both in `8.9.3` and `9.1.1`

**Comment by RIAEvangelist** [comment]
you are using ` log('data') ` but have not defined log. Try ` ipc.log ` if you want to use node-ipc's built in logger.

**Comment by ioncreature** [comment]
@RIAEvangelist
This problem is problem of `node-ipc` itself, not in my code

Look at 
https://github.com/RIAEvangelist/node-ipc/blob/17f7f111ff23bf11cdd95ff0cc0eae7d161e3d8c/dao/client.js#L148-L155

Look at my code else one time. 
After 1 second it tries to emit to socket when no socket connection established.

So error message says that there is no `client` variable in line `151`

And it should be handled and come to `error` event listener.

But I got unhandled exception here

**Comment by rahul-dutt-sharma** [comment]
I do not see how providing a log function would help as the client itself if evaluated to undefined (as per the error stacktrace)

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
