### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by zaksmok** [RIAEvangelist/node-ipc#128]
I'm receiving:
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node /home/server/cluster.js]
 2: 0x56400b20885e [node /home/server/cluster.js]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node /home/server/cluster.js]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node /home/server/cluster.js]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node /home/server/cluster.js]`

Here is the code of cluster.js:
https://pastebin.com/DtFx60sW

Any clue?

**Comment by RIAEvangelist** [comment]
Are you on the latest versions, and Is it possible you have an endless loop somewhere in your code?

**Comment by zaksmok** [comment]
I'm using version 9.1.0. 
I shared whole code on pastebin here: https://pastebin.com/DtFx60sW. 
There is no loop. Cluster.js is used as middle app. It's receiving messages and send to socket.js (in cluster mode). I have about 10 services and 4 socket clusters.

As you can see cluster.js code is very simple and for some reason there are memory leaks.

**Comment by RIAEvangelist** [comment]
Was there ever any progress made on this?

**Comment by zaksmok** [comment]
I tried to figure out the problem - no results. It's still happening from time to time

**Comment by RIAEvangelist** [comment]
Are you logging to the console or to a file?

I recall when I first started with node logging to the console, after some time depenkding on verbosity the service would crash. Logging to a file or using forever to start the processes with -a and the file name fixed the issue.

**Comment by zaksmok** [comment]
I'm using pm2 to start processes, it's logged to file and console. Additionally i'm usiing winston for my custom logging to files. What do you mean by using "-a" option? I didn't find this option in node docs

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
