### ISSUE TITLE
multiple Clients on disconnect

### ISSUE THREAD

**Issue by wgrhstf** [RIAEvangelist/node-ipc#129]
I use node-ipc in Electron for Communication between a Server-App and multiple Clients. So on Serverside I start with

    NodeIpc.config.id = 'world';
    NodeIpc.config.retry = 1500;

on Client Side it reports back with 

    NodeIPC.config.id = 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7; // <-unique Client ID
    NodeIPC.config.retry= 1500;
    NodeIPC.connectToNet(
    'world',
    function(){
        NodeIPC.of.world.on(
            'connect', function(){
                NodeIPC.of.world.emit(
                    'Data.fromClient',
                    {
                        Hello : I'm alive
                    }
                );
            }
        );

When The Client disconnects (that happen quite often) I need the admin to know, so I have

    NodeIpc.server.on(
        'socket.disconnected',
         function (socket, destroyedSocketID) {
             NodeIpc.log('client ' + destroyedSocketID + ' has disconnected!');
         });

This works great for the first disconnect, but if the Client disconnects and connect a couple of times in a short period the log looks like it was connected multiple times

    server socket error { Error: read ECONNRESET
        at exports._errnoException (util.js:1050:11)
        at TCP.onread (net.js:581:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
    socket disconnected 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7
    client 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7 has disconnected!
    Client 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7 down!
    client 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7 has disconnected!
    Client 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7 down!
    client 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7 has disconnected!
    Client 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7 down!
    client 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7 has disconnected!
    Client 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7 down!
    client 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7 has disconnected!
    Client 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7 down!
    client 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7 has disconnected!

But maybe I got something completely wrong in my setup...

**Comment by RIAEvangelist** [comment]
It looks like whatever is causing the client to disconnect is in the server code, and when the client reconnects it is rejected or closes shortly therafter.

Does that seem like a possibility?

**Comment by RIAEvangelist** [comment]
Or perhaps are you storing the client refrences somewhere in your code? If you are it is possible your code is trying to read from sockets that are closed, instead of accessing directly from ipc.of or similar.

**Comment by wgrhstf** [comment]
The references are not stored anywhere else (in fact the ID's I use for the socket are used in couple of other script parts, but not in main.js where the node-ipc communication takes place). 

The Client disconnection itself is on purpose. Sometimes the user just opens it for a couple of seconds, closes it and reopens again. But the multiple `Client xxx down! client xxx has disconnected!` leads to strange behaviour as it is passed multiple times to the app as well. 
The whole function on the Server goes like
```
 NodeIpc.serveNet(
        function () {
NodeIpc.server.on(
                'Data.fromClient',
                function (data, socket) {
                    NodeIpc.log('got a message from', (data));
                    NodeIpc.server.emit(
                        socket,
                        'Data.fromServer',
                        {
                            someValues: fortheClient
                        }
                    );
                    Window.webContents.send('Client.Data', data);
                  NodeIpc.server.on(
                    'socket.disconnected',
                     function (socket, destroyedSocketID) {
                        NodeIpc.log('client ' + destroyedSocketID + ' has disconnected!');
                        Window.webContents.send('Client.offline', destroyedSocketID);
                 });
});
NodeIpc.server.start();
```
But I don't see any part that could cause the sockets to hang...

**Comment by RIAEvangelist** [comment]
how about the client code?

**Comment by wgrhstf** [comment]
It's mainly what I wrote in my initial Post:
```
NodeIPC.config.id = 46f41bdd-dd60-4eb1-82ee-0313e4f1adc7; // <-unique Client ID
NodeIPC.config.retry= 1500;
NodeIPC.connectToNet(
'world',
function(){
    NodeIPC.of.world.on(
        'connect', function(){
            NodeIPC.of.world.emit(
                'Data.fromClient',
                {
                    Hello : I'm alive
                }
            );
        }
    );
```
Nothing strange in here I think...
