### ISSUE TITLE
connecting multiple clients to server from the same process

### ISSUE THREAD

**Issue by syberkitten** [RIAEvangelist/node-ipc#131]
Is it possible to create multiple client instances
from the same process to connect to a IPC Socket server?

It comes for testing purposes where i need to connect multiple processess
to a server, yet while testing it's more convenient to instantiate the clients
within a single process.

I'm getting this response when the second client is trying to connect:
```
Already Connected to xxxx - So executing success without connection

**Comment by syberkitten** [comment]
```
this is a sample of my code (nodejs module) IPCClient.js:
```


var config = {
  appspace: 'app.',
  socketRoot: '/tmp/',
  networkHost: 'localhost', // should resolve to 127.0.0.1 or ::1 see the table below related to this
  networkPort: 9200,
  encoding: 'utf8',
  rawBuffer: false,
  sync: false,
  silent: false,
  logInColor: true,
  logDepth: 5,
  retry: 500,
  maxRetries: false,
  stopRetrying: false
}

function extend (target) {
  var sources = [].slice.call(arguments, 1)
  sources.forEach(function (source) {
    for (var prop in source) {
      target[prop] = source[prop]
    }
  })
  return target
}

function IPCClient () {
  this.ipc = require('node-ipc')
  console.log('IPC Client Constructor')
  extend(this.ipc.config, config)
}

IPCClient.prototype.connect = createIPCInstance

function createIPCInstance (configObject, target, dataCallback) {
  var that = this
  return new Promise(function (resolve, reject) {
    if (!configObject.id) {
      throw new Error('Id is required')
    } else {
      extend(that.ipc.config, configObject)
    }
    that.ipc.connectTo(
      target,
      function () {
        that.ipc.of[target].on(
          'connect',
          function () {
            that.ipc.log('connected to server: ' + target, that.ipc.config.delay)
            /*
            ipc.of[target].emit(
              'hello from client :)'
            )
            */
            resolve(that.ipc.of[target])
          }
        )
        that.ipc.of[target].on(
          'error',
          function (err) {
            that.ipc.log('## error:', err)
            reject(err)
          }
        )
        that.ipc.of[target].on(
          'disconnect',
          function () {
            that.ipc.log('## Disconnected from server ##')
          }
        )
        if (dataCallback) {
          that.ipc.of[target].on(
            'data',
            dataCallback
          )
        }
      }
    )
  })
}

module.exports = function () {
  return new IPCClient()
}

```

outside the module, usage, everything for the first connected client works:

```
ipcClientInstance = require('IPCClient.js')()
// returns a promise with a connected instance of  that.ipc.of['world']
var ipcClientPromise = ipcClientInstance.connect({id:'number1'}, 'world')

ipcClientPromise.then((ipcClient) => {
     ipcClient.emit('query', {
         type: 'total-clients-connected',
        clientId: '11111',
       })
}).catche((e) => {
   console.log('who cares?')
})

// OR I'm using a simpler syntax but it's beside the issue:
    let tempClient
    [err, tempClient] = await to(ipcClientInstance.connect({id:'number1'}, 'world'))
     tempClient.emit('query', {
         type: 'total-clients-connected',
        clientId: '11111',
       })




```

**Comment by RIAEvangelist** [comment]
This should work just fine, however, let's recheck in v10.x when it is launched and see if you still have an issue. LMK if you still have any trouble. AFAIK this has been supported for a loooong time though.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
