### ISSUE TITLE
ConnectTo the starting server.

### ISSUE THREAD

**Issue by Catlite91** [RIAEvangelist/node-ipc#135]
If client connect to the serve using UnixSocket which is already in starting, currently node-ipc will throw an Error.
Is this problem possible to be resolved in the node-ipc module?

**Comment by RIAEvangelist** [comment]
Not enough info. Can only help withmore info. show code.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
