### ISSUE TITLE
Messages getting lost

### ISSUE THREAD

**Issue by patrickjane** [RIAEvangelist/node-ipc#136]
I am facing the problem that if I execute the `ipc.server.emit(socket, ...)` function in a loop lets say 1000 times, then the client side will receive malformed messages and/or messages are missing.

It will look kind of like this:

```
server:
sending .... 987
sending .... 988
sending .... 989
sending .... 990
sending .... 991
sending .... 992
sending .... 993
sending .... 994
sending .... 995
sending .... 996
sending .... 997
sending .... 998
sending .... 999

client:
got data "undefined"
got data "undefined"
got data "963"
got data "964"
got data "965"
got data "966"
got data "967"
got data "968"
got data "undefined"
got data "undefined"
got data "undefined"
got data "undefined"
got data "undefined"
got data "979"
got data "undefined"
got data "undefined"
got data "undefined"
got data "undefined"
got data "undefined"
```

I am using raw buffers. I tried setting "sync" to true, but it didn't have any effect.

Is this the expected behaviour, or what should be considered if a server wants to send a batch of messages as soon as a client connects (or whenever the server so wishes)?

As I see there is no callback-functionality for the sending part, so there is no way in my program to detect the finished sending of a message, right?

**Comment by jviotti** [comment]
Hi @patrickjane ,

Can you give us an example program? I can't manage to reproduce this.

**Comment by patrickjane** [comment]
Unfortunately I can't, because I am not working with `node-ipc` anymore.

**Comment by frankboehmer** [comment]
See #145

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
