### ISSUE TITLE
Invalide JSON response format

### ISSUE THREAD

**Issue by trend-setter** [RIAEvangelist/node-ipc#137]
I'm using a basic client-server application using node-ipc. COmmunication works fine in initial stages of deployment. But if any request is sent after some 8-10 hours, Server is not able to read any message sent from Client and the control is struck. Server throws the following error

> received event of : error {message: 'Invalid JSON response format', err: [SyntaxError: Unexpected token], response: <some random characters ending with the string sent from Client>

**Server Code:** 
`ipc.config.id = 'server';
ipc.config.retry= 1500;
ipc.config.networkPort = 8500;
ipc.config.networkHost = '0.0.0.0';
send.mime.default_type = 'text/plain'

var messages={
    client:false

};

ipc.serveNet(
    function(){
        ipc.server.on(
            'app.message',
            function(data, socket){
                //ipc.log('got a message from', (data.id), (data.message));
                messages[data.id]=true;

                split_data=data.obj_data.split(':');
                file_data = data.file_data.split(',');
                <Some more operations>`
 Is there anyKnown Timeout Issue with node-ipc? or is it soem other issue?

**Comment by frankboehmer** [comment]
Might have its root cause in #145

**Comment by allofee** [comment]
Encountered the similar issue. When the client re-connected to server, and client emit a msg to server, the server will receive wrong msg content like below.
The original test msg sent is {"type":"message","data":{"url":"null","type":2,"fileName":"null"}}.

## socket connection to server detected ##
received event of :  error { message: ESC[32m'Invalid JSON response format'ESC[39m,
  err: SyntaxError: Unexpected token G in JSON at position 0
    at JSON.parse (<anonymous>)
    at Message.parse (/root/nodeqqbot/node_modules/js-message/Message.js:56:30)
    at Server.gotData (/root/nodeqqbot/node_modules/node-ipc/dao/socketServer.js:185:17)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20),
  response: ESC[32m'GET / HTTP/1.1\r\nHost: 39.108.85.220:8000\r\nUser-Agent: HTTP Banner Detection (https://security.ipip.net)\r\nConnection: close\r\n\r\n{"type":"message","data":{"url":"null","type":2,"fileName":"null"}}'ESC[39m }

But the following msgs sent from client to server will be right. Thinking if it is a problem with buffer? Is there a way to clear the buffer before starting to send msg?

**Comment by RIAEvangelist** [comment]
not sure about this one, would like more info. Likely a buffer corruption from the previous. It may be fixed in v10.x

**Comment by rajmonotype** [comment]
Facing same issue, @RIAEvangelist Can you tell us any update time for fixing this bug?

**Comment by RIAEvangelist** [comment]
It looks like the buffer that was sent has much more than JSON in it as shown by the OP:

"ESC[32m'GET / HTTP/1.1\r\nHost: 39.108.85.220:8000\r\nUser-Agent: HTTP Banner Detection (https://security.ipip.net)\r\nConnection: close\r\n\r\n{"type":"message","data":{"url":"null","type":2,"fileName":"null"}}'ESC[39m }"

Is there any way someone could provide a code snippet that makes this happen so I can confirm it is an issue with the lib and not the messages being sent?

**Comment by RIAEvangelist** [comment]
If I can't duplicate the issue I can't work on it. Looking for help.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
