### ISSUE TITLE
broadcasting to local subnet (UDP)

### ISSUE THREAD

**Issue by utillity** [RIAEvangelist/node-ipc#138]
do I understand correctly that your server.broadcast() method will "broadcast" to all connected (TCP) clients? I need to broadcast to the local subnet (UDP) - and I believe sockets must be opened in a specific way to allow broadcasts to be sent/received.

I cannot get this to work on Windows 10, Electron. Is this supported? An example would be great, as I cannot get the current examples to work for broadcasting a message to the local subnet

**Comment by utillity** [comment]
why do you close without commenting?

**Comment by RIAEvangelist** [comment]
Answer is in the example/UDP/Multi client broadcast. 

I closed without commenting because it's in the docs and examples and thought I would just be necro bumping the post.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
