### ISSUE TITLE
disconnect not fired when network is down

### ISSUE THREAD

**Issue by wgrhstf** [RIAEvangelist/node-ipc#139]
Maybe it is something fundamental I'm missing. When I shut down my (TCP) Client or server application the other side reacts with a `disconnect` event as assumed, and I can react properly. 
But when I cut the network by puling the plug both sides do not recognize they are disconnected from each other. Is there any way to tell the connection between server and client is interrupted in node-ipc, or do I have to check manually?

Edit: the event is fired, but it takes up to a minute. So my question would rather be if that can be done in real-time somehow?

**Comment by RIAEvangelist** [comment]
It's likely a system socket timeout. This is the essence of a DOS attack.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
