### ISSUE TITLE
Client socket id requires being explicitly provided in message data

### ISSUE THREAD

**Issue by stulees** [RIAEvangelist/node-ipc#140]
Documentation states that when receiving the `socket.disconnected` event, it will provide the `destroyedSocketID`. However, the value for it is always `false`. It seems intuitive to assume that when you set a value for `ipc.config.id` for a client that it would be inherently applied as the id of the client socket. 

In inspecting the code further, it appears that (undocumented) the id of a socket is only set if `id` is provided in the data of a message - https://github.com/RIAEvangelist/node-ipc/blob/94249c24ea524151a33455196a8490cd0a9e0fcb/dao/socketServer.js#L187-L189

This socket id value is required when `socket.disconnected` is received - https://github.com/RIAEvangelist/node-ipc/blob/94249c24ea524151a33455196a8490cd0a9e0fcb/dao/socketServer.js#L138-L140

It would best if either the documentation was updated to inform of this requirement or socket id is internally applied from the value of `ipc.config.id` of a client.

**Comment by lutzbickhardt** [comment]
Actually the same applies to the connect and close events; it would be nice to get the socket.id
that opened or closed as parameters.

**Comment by scriptcoded** [comment]
Any updates here?

**Comment by RIAEvangelist** [comment]
in v10.x we will move to either passing back a ref to the socket itself or the id to fix this. Thank you for the leg work.

Reopening to make sure we test.

**Comment by RIAEvangelist** [comment]
#188 will address this issue

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
