### ISSUE TITLE
Better event documentation

### ISSUE THREAD

**Issue by JohnWeisz** [RIAEvangelist/node-ipc#141]
I've created a server with `serveNet`, connected my client (from C++ using Winsock) to it, and sent it a message. The message is visible and I can obtain the binary data exactly as it was built on the C++ end (it's an array of integers transmitted as a byte array).

At one point I however, need to send binary data _to the C++ client_, but it seems the `emit` method requires a socket object of some sort, this is referenced in the documentation, but never explained:

```js
//server
ipc.server.emit(
    socket, // <- what is this? where does it come from?
    [10,20,30]
);
```

Where do I get this socket object from? According to the documentation, the only way I can get this is when a client _disconnects_ (!), which is obviously of little use to me.

**Edit**

Since I'm working with binary data, I'm using the `data` event, not `message`, and the former does not expose the socket object.

**Comment by JohnWeisz** [comment]
Alright, so as it turns out, most events will also include the socket object on the list of callback arguments, it's just not documented.

In particular, it's available from the `connect` event.

**Comment by RIAEvangelist** [comment]
We should document that the socket is available here.

Re opening to request documentation either from you or me. Either way is good. Just need to remember it. 

Working on the v10.x branch

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
