### ISSUE TITLE
socket.write(message);

### ISSUE THREAD

**Issue by hasezoey** [RIAEvangelist/node-ipc#147]
```
project\node_modules\node-ipc\dao\socketServer.js:101
    socket.write(message);
           ^

TypeError: socket.write is not a function
    at Server.emit (project\node_modules\node-ipc\dao\socketServer.js:101:12)
    at Server.ipc.serve (project\main.js:353:28)
    at Server.emit (project\node_modules\event-pubsub\es5.js:74:21)
    at Server.onStart (project\node_modules\node-ipc\dao\socketServer.js:45:14)
    at Object.onceWrapper (events.js:275:13)
    at Server.emit (events.js:182:13)
    at emitListeningNT (net.js:1364:10)
    at process._tickCallback (internal/process/next_tick.js:174:19)
```

Windows 10@latest
nodejs 10@latest
node-ipc@9.1.1

executet in a cluster (`require('cluster')`)

(main and child are in the same file)

main.js
```js
            ipc.config.id = 'master';
            ipc.config.silent = true;
            ipc.serve(() => {
                ipc.server.on('msg', (data) => {
                    console.log(`Master Recieved: ${data}`);
                });
                ipc.server.emit('msg', 'hello from master'.green); // error comes from here
            });
            ipc.server.start();

            for (const id in cluster.workers) {
                cluster.workers[id].send('', (err) => {
                    if (err) console.error(err);
                });
            }
```

child.js
```js
// never gets executet 
process.on('message', (msg) => {
        ipc.config.id = `worker-${cluster.worker.id}`;
        ipc.config.silent = false;
        ipc.connectTo('master', () => {
            ipc.of['master'].on('msg', (data) => {
                console.log(`worker ${cluster.worker.id} got: ${data}`);

                setTimeout(() => {
                    ipc.of['savjeecoin-master'].emit('msg', `Hello from worker ${cluster.worker.id}`);
                }, 50000);
            });
        });
});
```

**Comment by xnite** [comment]
Having the same issue.

**Comment by crussell52** [comment]
Ran into the same problem -- dug deeper and found `ipc.server.broadcast()` -- for udp sockets, `ipc.server.emit()` delegates to `ipc.server.broadcast()` if a socket is not specified.  The same does not happen for other connection types (socket files in my case).

**Comment by crussell52** [comment]
@asos-martiplanellas I really hope this isn't bad etiquette to mention here, but... this project appears pretty dormant to me so I moved on to my own file-socket ipc implementation. I am not using it in production (yet), but that's the goal.  It is published under the MIT license, so if it helps you I'd love the feedback.

https://github.com/crussell52/node-socket-ipc

**Comment by RIAEvangelist** [comment]
Project is active.  Apologies for the delay, is this still an issue?

**Comment by RIAEvangelist** [comment]
Also, were you guys listening for the connected event before trying to emit? The socket may not yet have been created or connected.

**Comment by hasezoey** [comment]
> Also, were you guys listening for the connected event before trying to emit?

as in the original issue, yes:
serve (callback) -> listen to "msg" -> emit to "msg"

otherwise i didnt use this project since i opened this issue, so i cant help much

**Comment by RIAEvangelist** [comment]
Thanks

**Comment by edward-buskus** [comment]
I meet a problem with permissions when node-ipc server are started as windows service, then windows user applications cannot connect to this socket, until they are started as administrator, is there a way to avoid this issue ?

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/

**Comment by hasezoey** [comment]
@joshuaalayon your comment is off-topic, this was a issue about a specific bug, please do not do this, even though what you may write may be true
