### ISSUE TITLE
[Question] A way to check processes load.

### ISSUE THREAD

**Issue by vladikus10** [RIAEvangelist/node-ipc#148]
I'm using `node-ipc` to communicate between normal node app processes and a single server process which handles "global" timeouts. Once a timeout has ran out, the server notifies a single process about it and it executes an action.

It works just fine, however, my current issue is that the server has to pick a random process from the pool and notify it. Is there a way to get a single process that has the least load at the time of the timeout?

**Comment by RIAEvangelist** [comment]
maybe you could use node-cmd to get that from the system

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
