### ISSUE TITLE
anyway to know connectTo  fail?

### ISSUE THREAD

**Issue by njleonzhang** [RIAEvangelist/node-ipc#150]
is there a method through which I can know the connect failed? for example. the ipc server is not started.

**Comment by NbOpposite** [comment]
It will keep emitting errors on every failed retry as well, so keep that in mind!
`ipc.of[id].on('error', (err) => { /* dostuff */ })`

**Comment by njleonzhang** [comment]
Thx

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
