### ISSUE TITLE
Adding js docstrings and generate an API reference

### ISSUE THREAD

**Issue by SimplyLinn** [RIAEvangelist/node-ipc#151]
I just recently started using this and feel like I'm flying somewhat blind.

If I were to go trough the code and add relevant docstrings and a travis bulidscript that generates a more feature rich documentation page with an API reference, and automatically published that to gh-pages, turned that into a PR, would that PR be merged?

It would be quite a time-consuming task and I wouldn't want to do it without a green light from the maintainer

**Comment by RIAEvangelist** [comment]
Have you tried using the documentation that is written already?

If so, what more are you looking for? If what you are looking for is not present and seems valuable, I would love to request this when v10.x is nearing completion.

Thanks.

**Comment by SimplyLinn** [comment]
This was asked over a year ago, so don't actually recall as I got a day job and stopped with the project that used IPC for now. But IIRC, it was mostly that having a long single page with all the documentation, when you could use a tool like jsdoc to specify variable typings and similar, just to document the public API.

Then use another tool, [similar to the one discord.js](https://discord.js.org/#/docs/main/stable/general/welcome) uses, to take these JSdoc strings to generate a website that can be clicked around and stuff.

**Comment by RIAEvangelist** [comment]
Yeah, sorry for that.

Yep, I am very familiar with JSDoc, I have used it on a few projects. While it is cool that it builds out the docs for us, I find it rather difficult for a noobie to read and understand that type of documentation.

Do you know of any doc generators which generate more human-readable/understandable format output? 

I think you are right, breaking the docs up would be a good idea.

**Comment by SimplyLinn** [comment]
Since I've done some work on the Discord.js project, the ones I'm familiar with are their projects:
[discordjs/docgen](https://github.com/discordjs/docgen)
[discordjs/website](https://github.com/discordjs/website)

Both are open source and could probably with relative ease be made to work for this project as well?

In case you're interested I could help out with figuring out a travis/CI workflow that automatically builds and publishes documentation for releases/branches? I don't have THAT much time to dedicate to hobby projects, so I have no guarantee or even estimate on a timeframe of when this will be done

**Comment by RIAEvangelist** [comment]
That might be super cool. I think the v10 is going to be a rewrite because of how far the underlying socket implementation has come.

When I get closer to release, I'll touch base again.

Thanks!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
