### ISSUE TITLE
Prevent automatic logging of error messages to the console?

### ISSUE THREAD

**Issue by Slapbox** [RIAEvangelist/node-ipc#152]
When I try to connect to a socket which isn't available, currently I get the following:

```
######
error:  { Error: connect ENOENT \\.\pipe\tmp-app.myHost
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '\\\\.\\pipe\\tmp-app.myHost' }

```

How can I prevent this logging activity?

**Comment by RobinTail** [comment]
@Slapbox 
ipc.config.silent = true

**Comment by RIAEvangelist** [comment]
You can push a custom log function onto the ipc object. I believe it is in the docs.

LMK if not.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
