### ISSUE TITLE
Reconnecting to 'Windows Socket' on Windows cannot occur if server process restarts

### ISSUE THREAD

**Issue by Slapbox** [RIAEvangelist/node-ipc#154]
When my server process is stopped, if I start it back up again, my client cannot connect. I have to stop and start the server process a second time before it will connect.

Any thoughts on how to remedy this, or what may cause it?

**Comment by Slapbox** [comment]
Add a delay before restarting your node-ipc server to avoid this. 5 seconds seems to be plenty.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
