### ISSUE TITLE
How do I handle dynamic remote hosts?

### ISSUE THREAD

**Issue by techsin** [RIAEvangelist/node-ipc#155]
This is a question not a bug report or feature request.

What if I've multiple nodejs instances running which are not child processes of main process. But on different machines. For example heroku. I don't know ahead of time of what ip address or port they are going to be spawned at. What are some solutions..

Thanks.

**Comment by wgrhstf** [comment]
I ran into the same Problem and did it with the Machine Name. I've got the Name of my Admin Computer, let's say 'AdminMachine'. So there I set up my NodeIPC Server via
```
NodeIpc.config.id = 'world';
NodeIpc.config.retry = 1500;
NodeIpc.config.networkHost = getmyIP-Adressfunction();
NodeIpc.config.networkPort = 23000;
```
Every Client is now listening to 'world' via

```
NodeIPC.config.id = myUniqueClientID;
NodeIPC.config.retry= 1500;
NodeIPC.config.networkHost = 'AdminMachine';
NodeIPC.config.networkPort = 23000;
```
And on connect sends it's Data to the Admin for further processing
```
NodeIPC.connectToNet(
    'world',
    function(){
        NodeIPC.of.world.on(
            'connect',
            function(){
                NodeIPC.of.world.emit(
                    'Data.fromClient',
                    {
                        ClientComputerName: theNameofmyClient,
                        ClientIP: ClientIPAdress,
                        //whatever else i like to know....
                    });
            });
});
```
So on my Admin Machine I can collect the Data of any Client for further processing, or sending out commands to specific Clients.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
