### ISSUE TITLE
Messages are large, You may want to consider smaller messages.

### ISSUE THREAD

**Issue by RacerDelux** [RIAEvangelist/node-ipc#157]
Testing out a c# to nodejs implementation.
I am basing my example off the following code: [](https://github.com/edwardchanjw/nodeipcWithCSharp)
There is one thing I changed, in the mentioned example, they use '--' to terminate the string. I removed that setting and moved it back to the standard '\f' termination.

This is the log of the message I try to send:
`{ "type": "message", "data": {"foo": "bar"} } \f`

After I send the message, I close the pipe.
On the nodejs side, this is the logging from node-ipc:

> ## socket connection to server detected ##
> Messages are large, You may want to consider smaller messages.
> socket disconnected false

I looked into issue #79 but there is nothing in there that seems to help with this current issue.

**Comment by lukethompsxn** [comment]
I have found this exact same problem when trying to send data from a C application. @RacerDelux did you manage to find a solution for it?

**Comment by RacerDelux** [comment]
I had to use a different solution. I am using TCP now.

**Comment by lukethompsxn** [comment]
@RacerDelux Still using node-ipc or another node library?

**Comment by RacerDelux** [comment]
just the built in TCP sockets.

**Comment by seba-salavilla** [comment]
try sending especial character code \f =code 12 
like golang
fmt.Sprintf("{jsondata}%c",12)

**Comment by seba-salavilla** [comment]
> Testing out a c# to nodejs implementation.
> I am basing my example off the following code:
> There is one thing I changed, in the mentioned example, they use '--' to terminate the string. I removed that setting and moved it back to the standard '\f' termination.
> 
> This is the log of the message I try to send:
> `{ "type": "message", "data": {"foo": "bar"} } \f`
> 
> After I send the message, I close the pipe.
> On the nodejs side, this is the logging from node-ipc:
> 
> > ## socket connection to server detected
> > Messages are large, You may want to consider smaller messages.
> > socket disconnected false
> 
> I looked into issue #79 but there is nothing in there that seems to help with this current issue.

try sending especial character code \f =code 12
like golang
fmt.Sprintf("{jsondata}%c",12)

**Comment by RIAEvangelist** [comment]
You may need to change the buffer size in your node setup or system buffer
for the socket type. It is likely one of those two.

If it isn't causing any problems, likely solutions are not to log it or to
catch it.

**Comment by RIAEvangelist** [comment]
It is also possible this was related to socket corruption. We will keep testing to see if this still happens in v10.x branch

**Comment by RacerDelux** [comment]
I can take a look at it, I was forced to use tcp sockets instead.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
