### ISSUE TITLE
ipc.server.on('started') type of event or async await

### ISSUE THREAD

**Issue by wa11a** [RIAEvangelist/node-ipc#159]
now when you call "ipc.server.start()"
there's no way to get notified or wait for it to start.
so if I call stop and the server didn't start yet it will still be running.

**Comment by RIAEvangelist** [comment]
This is interesting, any further suggestions?

I am closing just because necrobump.

**Comment by RIAEvangelist** [comment]
I'm opening as this is a valid feature request.

**Comment by RIAEvangelist** [comment]
just looked sat the code and there is actually a `start` event which passes the ipc socket as the only param.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
