### ISSUE TITLE
TLS | add `secureContext` option from net.createServer() 

### ISSUE THREAD

**Issue by fas3r** [RIAEvangelist/node-ipc#161]
Hello @RIAEvangelist, 

- (1) With `TLS` it's possible to provide a `secureProvider` that contains the `cert`, `key` and `[ca(s)]` as buffers when calling `tls.createSecureContext()`, would it be possible to expose that option ? 

- (2) Still with `TLS`, would it be possible to expose [server.setSecureContext()](https://nodejs.org/api/tls.html#tls_server_setsecurecontext_options) method ? It allow to change the `secureContext` dynamically ( update certificate or the server ) without restarting the server ( linked to request 1* )

Thanks.

**Comment by RIAEvangelist** [comment]
How is this different than the current TLS socket?

**Comment by RIAEvangelist** [comment]
Secure context is used. as part of the 10.x upgrade, I looked into this. We are already using it.
