### ISSUE TITLE
Compatibility With Node 12?

### ISSUE THREAD

**Issue by Slapbox** [RIAEvangelist/node-ipc#163]
I've not done a pure Node 12 test, but my packaged IPC application can't communicate with Electron 6 (based on Node 12.4) Well, actually communication works in only one direction.

I noticed that tests end at Node 8? Is there any plan to maintain this library anymore?

**Comment by RIAEvangelist** [comment]
Sorry for the very long delay. v10.0.0 should be released soon, and will fix this issue. Same as #165

**Comment by Slapbox** [comment]
@RIAEvangelist thanks so much for the update!

**Comment by RIAEvangelist** [comment]
@Slapbox Welcome, it may take a week to get out. Now that public and private props are native for classes I am going to rewrite and update min node version to keep compatibility in the old versions.

also making it apache 2.0 licence. too many companies complaining about dbad

**Comment by Slapbox** [comment]
@RIAEvangelist I think it's a great move to ditch dbad for the sake of satisfying "corporate." Why Apache versus MIT though? MIT seems closer to dbad, but both seem like fine options - I'm just wondering.

**Comment by RIAEvangelist** [comment]
I don't really have a preference one way or the other. I'll Google an Apache vs Mit

**Comment by RIAEvangelist** [comment]
I guess this issue should stay open

**Comment by RIAEvangelist** [comment]
@Slapbox I am thinking of doing a full rewrite utilizing the latest socket and server apis, but trying to follow the node-ipc v4 interface as closely as possible.

What do you think? There may be some breakage, but this is a major rev. It moves from everything below 10-12 to only 12 or above

**Comment by Slapbox** [comment]
Personally I think we can use Node >=12 here without issue. Do you have some things you'd expect might break?

Nobody's ever excited to hear that things could break, but regardless of what's on that list, I think that the right answer is to do what you feel is going to be better long term. It sounds like you're thinking that would be the full rewrite?

**Comment by RIAEvangelist** [comment]
I believe migrating to the newer socket implementation of node 12+ is the right move especially for future compliance with all apis.

My goal would be to keep the exposed apis as documented but there could be more archane implementations that use specific fields which were not documented... I suppose though if it does break, they can stick with v9 version in their package until they migrate. 

I'll just have to be ready for some questions.

[I mentioned it here in the vue-cli](https://github.com/vuejs/vue-cli/issues/4937) to make sure.

**Comment by Slapbox** [comment]
I say go for it. The odds that someone _needs_ to upgrade ASAP are pretty low. We might fit the bill, though I'm not 100% sure. In any event, our use case isn't terribly extensive and I'm sure we can make do.

I'm guessing a full re-write might take quite a bit longer than what you'd originally planned. Any thoughts on when about the potential new version might be released?

**Comment by RIAEvangelist** [comment]
Well... I think the weekend, so probably by next weekend.

**Comment by Slapbox** [comment]
Wow that'd be quick!

**Comment by EdikDolynskyi** [comment]
Hi! I have been using node-ipc for a long time. Thanks for your work.

Now I face the issue with node-ipc not working with Node JS v12 and the need is urgent for me. 
Could you tell me if you plan to update the module in the nearest future?

Can I help? Thanks in advance.

**Comment by Suhail** [comment]
I am using node-ipc in Node 12.10 with Electron 8.x fwiw

**Comment by Slapbox** [comment]
@suuhail thanks for updating the issue. I also got it working with Electron 7 & 8. Idk what's up with 6, or what was going on. 

@RIAEvangelist I'm not sure what status this issue should be. I know you planned to make some related changes.

**Comment by aminya** [comment]
Is there any chance that we get this working? Is there an alternative package?

**Comment by RIAEvangelist** [comment]
This does seem to work with node v12

**Comment by Slapbox** [comment]
@aminya the issue seems to me to be with Electron 6 specifically.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
