### ISSUE TITLE
How can i spawn a new connection instead utilizing already connected?

### ISSUE THREAD

**Issue by JustinTrudeau1999** [RIAEvangelist/node-ipc#164]
Hello. FIrst of all great module. But i stumbled on a problem.

Basically a i have a site, on that side user can do some actions, and on the server node-ipc packet get send to node-ipc server, like so:

```
function do_work(lists,callback)
{
        var ipc = require('node-ipc');
            ipc.config.id = 'client';
            ipc.config.maxRetries = 0;

            ipc.connectTo('provider',function(){


            ipc.of.provider.on(
                'disconnect',
                function () {
                    ipc.log('disconnected'.notice);

                }
            );
            ipc.of.provider.on(
                'error',
                function (err) {
                    ipc.log(err);
                    //send error in callback
                    callback(err,null):
                }
            );
            ipc.of.provider.on(
                'result',
                function (data) {
                    //send result in callback
                    callback(null,data):
                }
            );

           var params = JSON.stringify(lists);
           ipc.of.provider.emit(
                    'grab',
                    params
           );
      });
}
```

So let's say 20 this function is called 20 times, at the same time for 20 users. I put require in function scope, but it still try to utilize that global instance created first time. What can i do ? Use `sync: true` ? Can i create a new ipc connection?

**Comment by RIAEvangelist** [comment]
I don't think this is an issue with the library, but let me know how you fixed your issue, if you were able to.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
