### ISSUE TITLE
listening on "*" (wildcard) does not return event name or data for node >= 10

### ISSUE THREAD

**Issue by timbowhite** [RIAEvangelist/node-ipc#165]
See https://github.com/RIAEvangelist/event-pubsub/issues/19

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
