### ISSUE TITLE
SOCK_SEQPACKET support?

### ISSUE THREAD

**Issue by dmawrey** [RIAEvangelist/node-ipc#167]
I've been looking everywhere for a node package to handle the unix socket type SOCK_SEQPACKET and I can't see it clearly stated anywhere whether node-ipc would be capable of this. If not, consider this an enhancement request. :)

**Comment by RIAEvangelist** [comment]
if it is sequential packet, then yes, and there is an example as well.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
