### ISSUE TITLE
switch from Istanbul to c8 for ES6 support

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-ipc#168]
Hey guys, I want to write some new tests and coverage. I could use some help from someone to update the module with a newer coverage tool. 

Any help appreciated.

**Comment by RIAEvangelist** [comment]
Istanbul now working.

**Comment by RIAEvangelist** [comment]
While the tests can run and we do get partial coverage reports, the istanbul dependancy on esprima still breaks some of the coverage reports.

So this at least lets our build tests operate properly for CI and Appveyor.

**Comment by RIAEvangelist** [comment]
Likely going to go with `c8` and may redo tests, or change CI as travis does not support udp6 for linux

**Comment by RIAEvangelist** [comment]
switched over, just writing tests now.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
