### ISSUE TITLE
Broadcast from server?

### ISSUE THREAD

**Issue by maksdam** [RIAEvangelist/node-ipc#172]
Description says it's there, but i can't get how to invoke it.
Broadcast() function could be found here: ./node-ipc/dao/socketServer.js
`Object.assign(this, {...})` is used inside Server constructor, so assigned fields aren't shown i guess
Problem is actual for a @types - can't find broadcast in Server interface as well

**Comment by Suhail** [comment]
I was also looking for this and noticed this PR: https://github.com/RIAEvangelist/node-ipc/pull/99/files#diff-55c405e124e3d50c7ff67af11fdd032aR276

It used to exist but something happened. Is there a new way?

**Comment by gituser3000** [comment]
hacky solution (ipc.server as any)['broadcast']('messageType', `message content`)

**Comment by RIAEvangelist** [comment]
what is this hacky solution? `(ipc.server as any)['broadcast']('messageType', 'message content')` what is it solving and how can this be merged back into the main code better?

Code samples appreciated.

**Comment by RIAEvangelist** [comment]
Isn't this just the same as `ipc.server.broadcast`? I must be missing something.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
