### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by Rpoint** [RIAEvangelist/node-ipc#174]
I've looked through multiple issues and seems like no one has my issue or simply i couldnt find it.

As i've been halfway through a project i noticed that i can't connect to a server over the network. I've been working locally using virtual machines to test it out and as long as the data arrives through the same pc it does receive and behave as it should.

So i put everything aside and check out where the problem could be. So i start from scratch, literally taking your examples and go up from there step by step.

I start from this [example](https://github.com/RIAEvangelist/node-ipc/tree/master/example/TCPSocket/basic) you put on.

Those are the steps taken:

1. I run them locally as they are, they connect and communicate.
2. I set up port and address, run them both locally and they connect and communicate.
3. I try to run them from 2 different pcs, they wont see each other.
4. I directly connect the pcs, skipping any router/switch, still cant communicate.

I've read through the documentation multiple times and seems like im still missing something, would really appreciate some clarification on the matter.

Thanks in advance.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
