### ISSUE TITLE
There is no method to clear retry timeout.

### ISSUE THREAD

**Issue by jennymiaomjz** [RIAEvangelist/node-ipc#176]
setTimeout(
                function retryTimeout(){
                    client.retriesRemaining--;
                    client.connect();
                }.bind(null,client),
                client.config.retry
            );

**Comment by RIAEvangelist** [comment]
I'm not sure I understand what you are looking for here.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
