### ISSUE TITLE
Cluster server example fails  

### ISSUE THREAD

**Issue by rajatkb** [RIAEvangelist/node-ipc#177]
**Description** : The cluster server example given in the repository fails with the following error. I ran the same code as given in the sample.

```
internal/child_process.js:762
        handle.setSimultaneousAccepts(true);
               ^

TypeError: handle.setSimultaneousAccepts is not a function
    at ChildProcess.target._send (internal/child_process.js:762:16)
    at ChildProcess.target.send (internal/child_process.js:677:19)
    at sendHelper (internal/cluster/utils.js:26:15)
    at send (internal/cluster/master.js:356:10)
    at internal/cluster/master.js:322:5
    at SharedHandle.add (internal/cluster/shared_handle.js:29:3)
    at queryServer (internal/cluster/master.js:316:10)
    at Worker.onmessage (internal/cluster/master.js:251:5)
    at ChildProcess.onInternalMessage (internal/cluster/utils.js:47:8)        
    at ChildProcess.emit (events.js:323:22)
```

Code for reference:

```javascript

const fs = require('fs');
const ipc=require('node-ipc');
const cpuCount = require('os').cpus().length;
const cluster = require('cluster');
const socketPath = '/tmp/ipc.sock';

ipc.config.unlink = false;

if (cluster.isMaster) {
    console.log(`Master pid ${process.pid}`)
   if (fs.existsSync(socketPath)) {
       fs.unlinkSync(socketPath);
   }

   for (let i = 0; i < cpuCount; i++) {
       cluster.fork();
   }
}else{
   ipc.serve(
     socketPath,
     function() {
       ipc.server.on(
         'currentDate',
         function(data,socket) {
           console.log(`pid ${process.pid} got: `, data);
         }
       );
     }
  );

  ipc.server.start();
  console.log(`pid ${process.pid} listening on ${socketPath}`);
}
```

**Comment by RIAEvangelist** [comment]
There are separate examples for Windows and Unix-based systems. It appears you were trying to run the Unix example on a windows machine. I just duplicated this myself to confirm. Try running the windows example on the windows machine.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
