### ISSUE TITLE
How to connect to the IPC server from .NET land?

### ISSUE THREAD

**Issue by mrakgr** [RIAEvangelist/node-ipc#178]
```fsharp
module UDS

open System
open System.Text
open System.IO
open System.Net
open System.Net.Sockets

let endp = UnixDomainSocketEndPoint("/tmp/app.world")
let socket = new Socket(AddressFamily.Unix,SocketType.Stream,ProtocolType.IP)
socket.Connect(endp)
if socket.Connected then 
    printfn "Am connected. Sending."
    let _ = socket.Send(Encoding.ASCII.GetBytes("Hello"))
    ()
else
    printfn "Failed to connect."
printfn "Done"
```

```
Unhandled exception. System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10050): A socket operation encountered a dead network. /tmp/app.world
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at <StartupCode$Sockets1>.$UDS_1.main@() in C:\Users\Marko\Source\Repos\Sockets1\Sockets1\UDS_1.fs:line 12
```

This same exception happens to me if I try the wrong address.

What I am trying to do is to connect to that basic server from [the example](https://github.com/RIAEvangelist/node-ipc#basic-examples). I can connect to it using the JS client provided, but I want to do the same from a .NET program and am not sure what I am doing wrong.

**Comment by mrakgr** [comment]
```fsharp
module UDS

open System
open System.Text
open System.IO
open System.Net
open System.Net.Sockets

let endp = UnixDomainSocketEndPoint("/tmp/app.world")
let address_families = Enum.GetValues(typeof<AddressFamily>)
let socket_types = Enum.GetValues(typeof<SocketType>)
let protocol_types = Enum.GetValues(typeof<ProtocolType>)
for address_family in address_families do
    for socket_type in socket_types do
        for protocol_type in protocol_types do
            try
                //printfn "Trying %A, %A" socket_type protocol_type
                use socket = new Socket(address_family :?> AddressFamily,socket_type :?> SocketType,protocol_type :?> ProtocolType)
                socket.Connect(endp)
                if socket.Connected then 
                    printfn "Am connected using %A, %A. Sending." socket_type protocol_type
                    let _ = socket.Send(Encoding.ASCII.GetBytes("Hello"))
                    ()
                else
                    printfn "Failed to connect."
            with e -> () //printfn "%s" e.Message

printfn "Done"
```

I tried literally every configuration enumeration possible and they all fail. It seems only the `AddressFamily.Unix,SocketType.Stream,ProtocolType.IP` is actually supported, though that one can't find the network. Is it possible that I need to put something else for path rather than `"/tmp/app.world"`? This is the path the server is using.

I forgot to mention it, but I am trying to do this from Windows 10. That might have something to do with it.

**Comment by mrakgr** [comment]
```fsharp
module Pipes

open System
open System.Diagnostics
open System.IO
open System.IO.Pipes
open System.Security.Principal
open System.Text
open System.Threading

let client = new NamedPipeClientStream(".","tmp-app.world",PipeDirection.InOut)
printfn "Connecting to server..."
client.Connect()
if client.IsConnected then
    printfn "Connected."

Console.ReadKey()
```

This actually works. I got the name of the pipe by inspecting the server in the debugger.

**Comment by mrakgr** [comment]
```fsharp
module Pipes

open System
open System.IO.Pipes
open System.Text

let client = new NamedPipeClientStream(".","tmp-app.world",PipeDirection.InOut)
printfn "Connecting to server..."
client.Connect(1000)
if client.IsConnected then
    printfn "Connected."
    let x = Encoding.UTF8.GetBytes("A")
    client.Write(x,0,x.Length)

Console.ReadKey()
```

Now I keep getting the `Messages are large, You may want to consider smaller messages.` error. Should I prefix the message with `message`?

**Comment by mrakgr** [comment]
No, neither prefixing the message directly nor sending `message` and `Hello` one after the other works. What should I do here?

**Comment by mrakgr** [comment]
I noticed that the client example is converting the data to JSON so I tried passing in `{"type":"message","data":"hello"}"`. That fails as well. As a side note...

```js
function emit(type,data){
    this.log('dispatching event to ', this.id, this.path, ' : ', type, ',', data);

    let message=new Message;
    message.type=type;
    message.data=data;

    if(this.config.rawBuffer){
        message=new Buffer(type,this.config.encoding);
    }else{
        message=eventParser.format(message);
    }

    if(!this.config.sync){
        this.socket.write(message);
        return;
    }

    this.queue.add(
        syncEmit.bind(this,message)
    );
}
```

In one of the if branches, I note that in `message=new Buffer(type,this.config.encoding);` the `data` is never used. That looks like a bug to me. Is that intentional?

**Comment by mrakgr** [comment]
```
    if(data.slice(-1)!=eventParser.delimiter || data.indexOf(eventParser.delimiter) == -1){
        this.log('Messages are large, You may want to consider smaller messages.');
        return;
    }
```

In the `socketServer.js` file, this gets triggered even though the data is perfectly fine. What happens is that the last element of `{"type":"message","data":"hello"}` is `}` and so `data.slice(-1)!=eventParser.delimiter` evaluates to true.

I am confused why it works for the JS client and not for the .NET one. Is the purpose of that if to check for nulls? Because it is telling me that the `eventParser.delimiter` is an empty string in the debugger, so I am guessing something tricky is going on. I actually tried passing a null as a part of the array from the .NET side and it still did not go through. The null at the end just ended up being an empty space in the debugger.

**Comment by mrakgr** [comment]
It might be that it is testing for `\r`.

**Comment by RIAEvangelist** [comment]
Apologies for the long delay, along side coding I am a professional electric motorcycle racer and reviewer and my spine was crushed in an accident. I am now healed up and trying to get back into things, I tried once before but I wasn't healed enough.

The \r delimiter is definitely your issue here. Thank you for posting all of the info for other .NETers to be able to communicate. The \r is configurable so it can be whatever you like, but we do need a delimiter to know the message is complete.

Thanks again!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
