### ISSUE TITLE
Please publish an updated package?

### ISSUE THREAD

**Issue by fluffynuts** [RIAEvangelist/node-ipc#179]
I've basically banged my head against the wall all afternoon, unable to figure out why my code doesn't work, and yours does (from checking out this repo @ master). Finally figured out it's probably to do with me using node 12 (I see issues around this) and if I update my package.json to reference this repo, things work as expected.

I honestly thought that, since I don't see a warning to the contrary about node 12 on the npmjs package page, my code _must_ be at fault and I simply _must_ have no idea how to do anything. Even copying your code into my project failed -- because, as I figured out later, the package is not up to date with the code in this repo.

I'm sure there must be other people who have hit this. If you're not happy to do a full release yet due to major changes, perhaps do an rc? Or a major version update?

Thanks for the hard work that went into this library though -- now that I can get something working, I think it's going to really help solve a problem I have.

**Comment by fluffynuts** [comment]
nvm, I'm a plain old idiot; it would help if I caught that last line about `ipc.server.start()`

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
