### ISSUE TITLE
help understanding the UDP Multi-Client-Broadcast example

### ISSUE THREAD

**Issue by npomfret** [RIAEvangelist/node-ipc#181]
I'm trying to broadcast over UDP to multiple clients running on the same machine.

I've run the example for doing a UDP broadcast (`Multi-Client-Broadcast.js`).  I was expecting the 2 clients to receive the broadcast message that gets sent by `world-server.js` after they have both connected.  I can see in the server logs that the message gets sent, but neither of the 2 clients appears to receive it.  Have I misunderstood how this is supposed to work?

The logs from the server reveal the possible problem:

> broadcasting event to all known sockets listening to  127.0.0.1  :  8000 message { id: 'world',
>   message:
>    'Everybody Loves The World! Got messages from hello and goodbye!' }
> 

But neither of the 2 clients is listening on port 8000 (they can't because the server is bound to that port).

**Comment by RIAEvangelist** [comment]
I'll have a look and see if its a misunderstanding or a poor example.

**Comment by RIAEvangelist** [comment]
hmm... looks like everything in the example works great up to the broadcast.

I'm just getting back into stuff after a long break from everything with a crushed spine. I'm also a professional motorcycle racer and reviewer. 

The server is on port 8000 so the clients are "listening" to it. We can tell the messaging works because both clients receive their  independent respective messages. Just not the broadcast.

Where I see the confusion, and some severe spelling errors, is in fact somewhere in this part of the example :

`
               if(messages.hello && messages.goodbye){
                    
                     // this happened so we know we got in here
                     ipc.log('got all required events, telling evryone how muchg I am loved!');
                    

                    //the internal log says this happened
                   ipc.server.broadcast(
                        'message',
                        {
                            id      : ipc.config.id,
                            message : 'Everybody Loves The World! Got messages from hello and goodbye!'
                        }
                    );
                }
`

So either the clients are not handling the data when they get it, or its not being sent. If you could help figure it out, that would be great, otherwise as I get back into things I will work on making a better example.

Thanks!

**Comment by npomfret** [comment]
I think (maybe) I misunderstood how the example is supposed to work - or it just doesn't do what I needed.  Essentially I was looking for a solution that allows me to broadcast to multiple services running on the same host.  The following illustrates the solution I incorporated, the trick was to use `reuseAddr: true` on the socket:

```
const udp = require("dgram");

const multicastAddr = "225.1.1.1";
const port = 6821;

for (let i = 0; i < 3; i++) {
    const socket = udp.createSocket({type: "udp4", reuseAddr: true});

    socket.bind(port, multicastAddr, function () {
        console.log(`bind client ${i}`);
        socket.addMembership(multicastAddr);
        socket.setBroadcast(true);
    });

    socket.on("close", () => console.info('closed', i));
    socket.on("connect", () => console.debug('connect', i));

    socket.on('error', (err) => {
        console.error(err);
    });

    socket.on('listening', () => {
        const address = socket.address();
        console.log(`client ${i} listening ${address.address}:${address.port}`);
    });

    socket.on("message", function (b, rinfo) {
        console.log(`listener ${i} received message: ${b}`);
        socket.close();
    });
}

const sender = udp.createSocket({type: "udp4", reuseAddr: true});

const dataAsText = JSON.stringify({"foo": 'bar'});
console.log(`sending message: ${dataAsText}`);
sender.send(dataAsText, 0, dataAsText.length, port, multicastAddr, () => sender.close());


```

**Comment by RIAEvangelist** [comment]
Well that is fancy, I will have a look in the guts of the ipc thanks 👍

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
