### ISSUE TITLE
node-ipc electron connectTo error

### ISSUE THREAD

**Issue by surendra-17** [RIAEvangelist/node-ipc#182]
myapp1
myapp1 connect to
Error: connect ENOENT \\.\pipe\tmp-app.myapp1
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '\\\\.\\pipe\\tmp-app.myapp1'
} error on connection
checking false
myapp1
myapp1 connect to
Error: connect ENOENT \\.\pipe\tmp-app.myapp1
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '\\\\.\\pip

**Comment by RIAEvangelist** [comment]
ENOENT means you either do not have permission to connect to the port, or it is not open for connection. It is possible that you have the wrong address as well. Test with the examples folder and LMK if you can't get those to work.

Closing unless you still have issues after you test the examples.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
