### ISSUE TITLE
TCP Server is not working right on some devices

### ISSUE THREAD

**Issue by bayramgeldi** [RIAEvangelist/node-ipc#183]
TCP Server is not working right on some devices. I am using tcp socket to communicate between electron and .net applications. I am creating server on electron app. Here is my server:

`const ipc = require('node-ipc');
 const Store = require('electron-store');
 const store = new Store();

 const config = store.get('gastro-club');
 const BASE_URL = "https://gastroclub.com.tr/hm/api/";
 const CONTENT_TYPE = "application/json; charset=utf-8";
 const userParameter = config.user_parameter;
 const username = config.username;
 const password = config.password;
 const ip = config.ip;
 const port = config.port;
 const token = "Basic " + btoa(username + ":" + password);

 ipc.config.id = 'world';
 ipc.config.retry = 1500;
 ipc.config.sync = true;
 ipc.config.networkHost = (ip)?(ip):'127.0.0.1';
 ipc.config.networkPort = (port)?(port):9700;
 ipc.config.rawBuffer = true;
 ipc.config.encoding = 'utf8';

 ipc.serveNet();
 ipc.server.start();

    console.log('TCPServer.js file');
    ipc.server.on(
        'connect',
        function (socket) {
            //console.log("connection", socket);
            ipc.log('got connection');

        }
    );
    ipc.server.on(
        'data',
        function (data, socket) {
            ipc.log('got a message', data,data.toString());
            if (data) {
                let jsRaw = data.toString();
                let json;
                try{
                    json=JSON.parse(jsRaw);
                }catch (e) {
                    console.log(e);
                }

                if (json && json.message === "gastro") {
                    let code= json.code;
                    let price= json.total;
                    //console.log('open gastro');
                    //ipcRenderer.send('key:gastro', json.data);
                    console.log(json);
                    getDiscount(code,price, socket);
                    //testDiscount(code,price, socket);
                }else {
                    ipc.server.emit(
                        socket,
                        '{"Result":"false","Errors":[{"Message":"Alınan mesaj geçerli formatta değil."}],"Message":"Alınan mesaj geçerli 
 formatta değil.","DiscountRate":"null","PromotionCode":"null","FullName":"null","CampaignTitle":"null"}'
                    );
                }
            }
        }
    );
 function TCPServerRun() {

 }

 function getDiscount(code, price, socket) {
    //console.log('func', userParameter, token);
    $.ajax({
        url: BASE_URL + "Check",
        contentType: CONTENT_TYPE,
        dataType: "json",
        type: "POST",
        async: false,
        headers: {
            'Authorization': token,
        },
        data: JSON.stringify({
            "Code": code,
            "UserParameter": userParameter,
            "Price": price
        }),
        success: function (data) {
                //doğrulama başarılı
                ipc.server.emit(
                    socket,
                    JSON.stringify(data)
                );
        },
        error: function (jqXHR, textStatus) {
            //error
            ipc.server.emit(
                socket,
                '{"Result":"false","Errors":[{"Message":"Gastro ile iletisim saglanamadi."}],"Message":"Gastro ile iletisim 
 saglanamadi.","DiscountRate":"null","PromotionCode":"null","FullName":"null","CampaignTitle":"null"}'
            );
        }
    });
 }
 function testDiscount(code, price, socket){
    let data={
        "DiscountRate": "15",
        "Result": true,
        "Message": "Kod Doğrulama Başarılı",
        "PromotionCode": "GC93899",
        "CampaignTitle": "Restoran İndirimi"
    };
    ipc.server.emit(
        socket,
        JSON.stringify(data)
    );
 }

 module.exports.TCPServerRun = TCPServerRun;`
with this configuration it works on most computers but on some devices it is connecting to server but not receiving data. And after closing connection  and retrying it again it comes back with old message.

**Comment by RIAEvangelist** [comment]
Are you using the correct delimiter?

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/

**Comment by bayramgeldi** [comment]
Thank you informing
