### ISSUE TITLE
Update js-message dependency

### ISSUE THREAD

**Issue by bkhatkov** [RIAEvangelist/node-ipc#184]
Hello,

Could you please update js-message dependency to 1.0.7 (at the moment it is fixed to 1.0.6).
Current:
"dependencies": {
    "event-pubsub": "4.3.0",
    "js-message": "1.0.6",
    "js-queue": "2.0.2"
  },
To be:
"dependencies": {
    "event-pubsub": "4.3.0",
    "js-message": "^1.0.7",
    "js-queue": "2.0.2"
  },

**Comment by RIAEvangelist** [comment]
ah 💩 ok.

**Comment by RIAEvangelist** [comment]
updated docs and deps for [9.1.3](https://github.com/RIAEvangelist/node-ipc/releases/tag/9.1.3) published patch to npm as well. Thanks

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
