### ISSUE TITLE
Limit on maximum number of connected clients?

### ISSUE THREAD

**Issue by himanshusinghs** [RIAEvangelist/node-ipc#186]
Is there a limit on maximum number of clients that can be connected to ipc server?
For me, after first 99 connected clients I start receiving ERR_STREAM_DESTROYED error for the rest that are still trying to connect.
First had a thought that it might be due to how our project was developed but even isolated, it pose the same issue.

**Comment by RIAEvangelist** [comment]
I'm not aware of this being a limitation. Perhaps there is a deeper setting in one of the sockets servers if this is the case.

Could make up a quick demo that just has a server in one file, and maybe a loop in a client file, or two, to demonstrate the basic issue. Nothing fancy, just demonstrate the issue in its most basic form.

This would show clearly that it is not related to your code.

Thanks!

**Comment by RIAEvangelist** [comment]
Would love an isolated code snippit to help isolate this. even just a for loop with code to demonstrate the issue would be great

**Comment by RIAEvangelist** [comment]
stale

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
