### ISSUE TITLE
add id to socket not just the socket container IPC.js#L328

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-ipc#188]
[IPC.js#L328](https://github.com/RIAEvangelist/node-ipc/blob/c82afb34b504e1ff9204c01d457ba645aa7935da/services/IPC.js#L328)

should also put the id on the socket, not just the `of[id].id` but also the `of[id].socket.id` if it exists at this point.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
