### ISSUE TITLE
Connection exceeding amount with amounts remaining.

### ISSUE THREAD

**Issue by markrmessmore** [RIAEvangelist/node-ipc#193]
So I added an event and with said event am getting the following issue. I didn't immediately notice any previously reported issue so if I'm missing something please point it out.

I have a client and server communicating back and forth nicely. Here is the code in question:

CLIENT:
```
// SETTINGS
ipc.config.id           = 'client'
ipc.config.maxRetries   = 5
ipc.config.silent       = false
ipc.config.retry        = 1500

// EVENT
ipc.connectTo(client, () => {
    ipc.of.client.emit('sendItem', itemData)
    
    ipc.of.client.on('itemResponse', (data, server) => {
        console.log('here')
    })

    ipc.of.client.on('sendErr', (data, server) => {
        console.log(data)
    })
})
```

SERVER
```
ipc.server.on('sendItem', (data, client) => {
    send(data)
    .then(response => {
        ipc.server.emit(client, 'itemResponse', response)
    })
    .catch(err => {
        ipc.server.emit(client, 'sendErr', err)
    })
})
```

Here is the error I am receiving on the client end:
```
connection closed server /tmp/app.server 5 tries remaining of 5
Client exceeded connection rety amount of  or stopRetrying flag set.
```

In short, the commands outside of ipc are working as expected. However the two lines of `5 tries remaining` and `exceeded connection...` show up at precisely the same time. I've even tried to reduce the activity of WHAT is happening when the data is received (hence the basic `console.log()` variants that you see above. Prior to this issue I was not using the `maxRetries` option. because things were just working. I've only set it in this instance to see if that could resolve the issue. 

Any help pointing me in a direction would be greatly appreciated.

**Comment by RIAEvangelist** [comment]
Try logging out something each time it disconnects. Perhaps something you are not expecting is happening.

**Comment by markrmessmore** [comment]
I'm not entirely sure what I did to resolve this...however the situation involved multiple simultaneous calls from Express. I rewrote the Express calls and have removed any disconnects for simplicity.

**Comment by RIAEvangelist** [comment]
Ok, It seemed to me like it was possible the connections were being dropped
and reconnected, perhaps in an unexpected flow.

The sort of things you were talking about with express can often times give
a seamless feel despite frequent connect and disconnects. The seamless feel
sometimes confuses what's happening behind the scenes.

I'm glad you were able to resolve the issue!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
