### ISSUE TITLE
Receiving message via a named pipe

### ISSUE THREAD

**Issue by RichardFoss** [RIAEvangelist/node-ipc#194]
Thank you for this package! 
I would like to receive data from a JUCE C++ program via a named pipe.
I have attempted to do this by using the 'rawBuffer' approach. I have followed the code in the 'Advanced Examples':
ipc.config.rawBuffer=true; 
ipc.server.on( 'data',
I'm not getting a response on the server side.
Is this the correct approach?
Thanks for the help!

**Comment by RIAEvangelist** [comment]
If you want to transfer rawbuffer data, this would be one way to do it.

I would suggest you start my creating the pipe and just trying to connect to it.

**Comment by RichardFoss** [comment]
Thanks for your reply, and apologies for the slow response - in South African time!
I would prefer to transmit json data. Here is a short section of code, in which I'm trying to pick up a connection and also receive the simple json that you provide - 
"{type:'myEvent',data:{a:1}}"

const ipc = require('node-ipc');

ipc.config.id = "testIPC";
ipc.config.retry= 1500;

ipc.serve("\\\\.\\pipe\\testIPC",
    function(){
        ipc.server.on(
            'connect',
            function(socket){
                ipc.log("Connected");
            }
        );

        ipc.server.on(
            'myEvent',
            function(data,socket){
                ipc.log('got a message', data);
            }
        );
    }
);

ipc.server.start();

It will help a lot to know that I am on the right track with this server. I will then know that my issue is on the JUCE C++ side.
Thanks!

**Comment by RichardFoss** [comment]
Sorry, that code didn't come out right:

const ipc = require('node-ipc');

ipc.config.id = "testIPC";
ipc.config.retry= 1500;

ipc.serve("\\\\.\\pipe\\testIPC",
    function(){
        ipc.server.on(
            'connect',
            function(socket){
                ipc.log("Connected");
            }
        );

        ipc.server.on(
            'myEvent',
            function(data,socket){
                ipc.log('got a message', data);
            }
        );
    }
);

ipc.server.start();

**Comment by RIAEvangelist** [comment]
I suggest you use unix style pathing, this will be simpler for you and work on windows too. Also, don't use relative paths. I appreciate you want to just get started sending json, but before I help you with that, I would like to know that you are or are not able to connect to the socket.

https://github.com/RIAEvangelist/node-ipc#types-of-ipc-sockets

Please start by debugging your ability to connect to the socket.

**Comment by RIAEvangelist** [comment]
This link might give you a better example of unix style pathing.

https://github.com/RIAEvangelist/node-ipc#serve

**Comment by RichardFoss** [comment]
Thank you very much for your continued help!
I'm unclear about what to provide as a path name. I read the following from Microsoft documentation:
```
Use the following form when specifying the name of a pipe in the CreateFile, WaitNamedPipe, or CallNamedPipe function:
\\ServerName\pipe\PipeName
where ServerName is either the name of a remote computer or a period, to specify the local computer
```
Hence my use of:
` "\\\\.\\pipe\\testIPC"`

On the JUCE C++ side I had:
`juce::String testIPC = "\\.\pipe\testIPC";` followed by:
`currentPipe->connectToPipe(testIPC, 1000);`

I don't get the connect message showing. I seem to be missing something with my usage of the node-ipc module. I tried working with sockets (I presume TCP/IP), rather than the path approach:

```
//With sockets
const ipc = require('node-ipc');

ipc.config.id = "testIPC";
ipc.config.retry= 1500;
ipc.config.networkPort = 8124;

ipc.serve(
    function(){
        ipc.server.on(
            'connect',
            function(socket){
                ipc.log("Connected");
            }
        );
        ipc.server.on(
            'myEvent',
            function(data,socket){
                ipc.log('got a message', data);
            }
        );
    }
);

ipc.server.start();
```
I didn't see the Connected message here either (I'm assuming that ipc.log prints to the console)

I then tried using the in-built net module, and this worked for me. 

```
//Now with npm net
const net = require('net');
const server = net.createServer((c) => {
  // 'connection' listener.
  console.log('client connected');
  c.on('end', () => {
    console.log('client disconnected');
  });
  c.on('data', function(data){
    console.log(data);
    textChunk = data.toString('utf8');
    console.log(textChunk);
    c.write(textChunk);
   });
  //c.write('hello\r\n');
  //c.pipe(c);
});
server.on('error', (err) => {
  throw err;
});
server.listen(8124, () => {
  console.log('server bound');
}); 

```
I got the Client connected message and was able to transmit messages and have them displayed.

I would however really like to use a named pipe, and particularly with the elegance of node-ipc code structure.

Thanks again for your help!

**Comment by RIAEvangelist** [comment]
Did you try my last suggestion or the examples I linked to? 

The best thing to do would be to use the examples and confirm a connection can be made. I know you want to do things the way you describe, but I think it would be best to try the feedback I provided.

Testing the basics as they are given without making changes would be an ideal test.

**Comment by RIAEvangelist** [comment]
Again just to reiterate, I think it's the way you are doing the path.  I modified the example I linked above :

https://github.com/RIAEvangelist/node-ipc#serve

try connecting to `/tmp/myapp.myservice`

your OS should be able to handle the conversion of the `/` automatically.



```js


const ipc=require('node-ipc');

ipc.serve(
    '/tmp/myapp.myservice',
    function(){
        ipc.server.on(
            'connect',
            function(socket){
                console.log('connected');
                ipc.server.emit(
                    socket,
                    [0xaa]
                );
            }
        );
    }
);

ipc.server.start();

```

**Comment by RichardFoss** [comment]
Thanks for making time to follow up on this issue, and to provide test code, much appreciated!
Unfortunately, I am not able to make a connection from the JUCE C++ client side. I don't get the console log message displayed. I do think that its on the client side where my problem lies. I have the following code:
```
    currentPipe = new pipeIPC(this);
    bool connectOK = currentPipe->connectToPipe("/tmp/myapp.myservice", 1000);
	if (connectOK)
		DBG("Connected to pipe!");
	else 
		DBG("Not Connected to pipe!");
}
```
and it displays 'Not Connected to pipe'.
So I think that I am going to have to go for a socket-based inter process communication.

Something that was interesting to me - I tried a net-based implementation:

```
//Now with npm net
const net = require('net');
const server = net.createServer(() => {
  // 'connection' listener.
  console.log('client connected');
});
server.on('error', (err) => {
  throw err;
});
//server.listen("\\\\.\\pipe\\testIPC", () => {
server.listen('/tmp/myapp.myservice', () => {
  console.log('server bound');
}); 
```
and this gave the error:
`Error: listen EACCES: permission denied /tmp/myapp.myservice`
but it was was fine with:
`server.listen("\\\\.\\pipe\\testIPC", () => {`
Although still no connection to it from the JUCE app :(

Thanks again,
Richard.

**Comment by RIAEvangelist** [comment]
In C++ try flipping the ` / `

**Comment by RichardFoss** [comment]
Thanks for the suggestion - unfortunately still no connection. I have tried every permutation of forward and back slash(es).
I have laid out my problem on the JUCE forum, and have had many views, but no suggestions.
So I think its back to sockets!

**Comment by RIAEvangelist** [comment]
Have you tried connecting in just plain C++ instead of just the juice
framework?

These are posix/unix sockets

**Comment by RIAEvangelist** [comment]
Even just trying just two node instances... To make sure the server is
spinning up as expected.

**Comment by RichardFoss** [comment]
Thank you very much for further suggestions, and apologies for my slow response.
For the project I'm working on, I have to have interaction between a JUCE program and a nodejs program. I do need to move on to coding the application, so I'm going to go with the socket approach that I have working, and as a background task will keep trying the named pipe approach. I will let you know how it goes.
Thanks again for all your help!!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
