### ISSUE TITLE
Make log lines clearer

### ISSUE THREAD

**Issue by mount2010** [RIAEvangelist/node-ipc#196]
I was debugging an issue in an app using node-ipc and encountered the log message "retrying reset". The wording of the log message made me think that there was an issue connecting to the IPC server, when in reality, it meant that the number of retries that node-ipc would attempt was reset. Could this be made clearer to save the time of developers? Thanks.

**Comment by RIAEvangelist** [comment]
Please fork the repo and make an update then do a PR. So long as the change is not confusing, it will be merged.
