### ISSUE TITLE
RawBuffer concatenating messages?

### ISSUE THREAD

**Issue by SupremeTechnopriest** [RIAEvangelist/node-ipc#197]
Hello,

I have a few questions about the `rawBuffer` messages.  It seems like the `data` event is not emitted every time a message is emitted from the server.  For instance, if I send multiple small messages in a loop, the first one arrives in tact, but then the subsequent message is not the buffer I sent.  The byteLength is much larger and the message count is fewer than what I send, which leads me to believe messages are being concatenated?  

Does the `data` act like a stream?  Do I have to collect all messages and each time the delimiter is detected, that constitutes one event?  I know how Node Buffers can share a chunk of memory and I'm slicing the received buffer appropriately:

```typescript
export const toArrayBuffer = (buffer: Buffer): ArrayBuffer => {
  return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength)
}
```

However, some times messages come in too large, too small, out of order etc.  The documentation doesn't have very much on the `rawBuffer`. Am I missing something?

My ipc config settings are:

```typescript
ipc.config.id = 'world'
ipc.config.retry = 200
ipc.config.silent = true
ipc.config.rawBuffer = true
ipc.config.encoding = 'hex'
```

and I am constructing my messages like this:

```typescript
const packet = Buffer.from(arrayBuffer)
ipc.server.emit(socket, packet)
```

I would expect that each `data` event would be one `ipc.server.emit`, but that does not seem to be the case.  Any insight would be greatly appreciated.

Thanks!

**Comment by zsjinwei** [comment]
I am newer to use this library, and met the same issue. some solution?

**Comment by SupremeTechnopriest** [comment]
I haven't found a solution yet, but I'm going to try to figure it out today.  Something tells me this is a bug or possibly an undocumented feature... but I would expect an `emit` to correspond to an `on` 1:1.  Ill report back if I can figure it out.

**Comment by SupremeTechnopriest** [comment]
if @RIAEvangelist could point me in the right direction it would save me many hours of pain reverse engineering :)

**Comment by RIAEvangelist** [comment]
I'll be online tomorrow to help.

**Comment by SupremeTechnopriest** [comment]
Awesome! Looking forward to it!

**Comment by SupremeTechnopriest** [comment]
@RIAEvangelist Glad you are back!  Do you have anything I can go on to try and solve this?  Im currently blocked from finishing my project because I cant figure out how to parse these buffer messages.  Before I turned all my messages to buffers all the event emission and event reception were 1:1, now it seems like something is happening under the hood based on message rate or emission timing.

**Comment by RIAEvangelist** [comment]
@SupremeTechnopriest 

Can you provide a sample snippit that shows the issue?

Just wrote a basic example of what you are doing that shows it not working. Messages can even be hard coded if you want.

**Comment by SupremeTechnopriest** [comment]
Sure coming right up.

**Comment by SupremeTechnopriest** [comment]
So here is my message creator:

```typescript
export enum MessageType {
  INIT,
  READY,
  HEALTH,
  IMPORT,
  EXPORT,
  REMOVE,
  CONNECT
}

export const createMessage = (type: MessageType, data?: IObject<any> | ArrayBuffer) => {
  const header = Buffer.from([type])
  let body: Buffer
  if (
    data instanceof ArrayBuffer ||
    typeof data === 'string'
  ) {
    body = Buffer.from(data)
  } else if (typeof data === 'object') {
    body = Buffer.from(JSON.stringify(data))
  } else {
    body = Buffer.alloc(0)
  }

  return Buffer.concat([header, body])
}

export const toJSON = (buffer: Buffer) => {
  return JSON.parse(buffer.slice(1).toString())
}

export const toArrayBuffer = (buffer: Buffer) => {
  return buffer.buffer.slice(buffer.byteOffset + 1, buffer.byteOffset + buffer.byteLength)
}```

This is responsible for creating the buffers (prepending the message type) and turning the buffer back into the original type.

Here is a subset of my message handler on the client process:

```typescript
import { MessageType, toArrayBuffer, toJSON } from './utils/Messaging.js'

ipc.of.world.on('data', (buffer: Buffer) => {
  switch (buffer[0]) {
    case MessageType.INIT: {
      console.log('init')
      const init = toJSON(buffer)
      // Do something with the json
      console.log(init)
      break
    }
    case MessageType.IMPORT: {
      console.log('import')
      const packet = toArrayBuffer(buffer)
      // Do something with the packet
      console.log(packet.byteLength)
      break
    }
  }
})
```

Then on the main world (server) we can simulate a bunch of import events:

```typescript
// Handle connection logic and store reference to client sockets.

for (let i = 0; i < 1000; i++) {
  const packet = new ArrayBuffer(90)
  const buffer = createMessage(MessageType.IMPORT, packet)
  ipc.server.emit(socket, buffer)
}
```

This is pretty much the gist of it.  Sending many messages in a loop, the first one arrives perfectly, but subsequent ones look like they are being concatenated.  The parsed size from the message is much larger than 91 bytes.  I ended up doing a little extra preprocessing on the packets to reduce the number of messages and sending one large buffer instead.  It works, but then when other message types are sent there seems to be some sort of race condition whether or not it will be able to be parsed by the client.

**Comment by SupremeTechnopriest** [comment]
So im working on a sample for you.  Its not complete yet, but here you can see some issues.

https://stackblitz.com/edit/node-ipc-example?devtoolsheight=33&file=server.js

If you run: `node server.js` in one terminal and `node  client.js` in another, you will see the server attempting to send 100 messages but the client only receiving 10.  Im going to try to get a more complete example of my use case together.

**Comment by RIAEvangelist** [comment]
thanks.

one reason I'm not a fan of typescript is that the code has to be
transpiled, which changes how things are written. I know its an important
tool for people, but I use the `strong-type` module instead. This gives me
strong typing without transpiling my code. I like my code to run as I wrote
it. Makes it a lot easier to debug.

**Comment by RIAEvangelist** [comment]
I updated your server dispatch with a delay just to see what would happen, and it works now. So the buffer portion seems like it may need an update in the module. I think it should be saved if you check it out.

```js

     let z = 1e8;
      while (z > 0) {
        let a = 0;
        z--;
        a++;
      }
      
```

**Comment by RIAEvangelist** [comment]
I think I have a way to send the messages as volatile or non volatile as well. so the pipe doesn't have collisions.

**Comment by RIAEvangelist** [comment]
Yeah, you could use [`js-queue`](https://github.com/RIAEvangelist/js-queue) or [`easy-stack`](https://github.com/RIAEvangelist/easy-stack) to handle your volatility issue. Queue is FIFO and the Stack is LIFO.

**Comment by SupremeTechnopriest** [comment]
So in the actual implementation I am filling and draining a queue. Is the emit method sync or async?  I think the message rate will get pretty high as the project I'm working on is a networking engine for games. 

Is this something you can patch inside of `node-ipc` or will I have to introduce some kind of synthetic latency to the message queue?  Adding latency isn't really ideal since this will be used for game networking and speed is pretty important.

**Comment by SupremeTechnopriest** [comment]
It might have saved as a fork, the original doesn't have your additions.  I'm working on a more complete example that has all the abstractions and queues.  Maybe we can take a look at that together and figure out the best way to solve this.

**Comment by RIAEvangelist** [comment]
please use the `js-queue` module to send your messages synchronously.

**Comment by NateTheGreatt** [comment]
hey @RIAEvangelist, thanks for taking the time to help us out. i tried using `js-queue` but unfortunately the problem persists.

this may be a bug with node itself, see this issue here:
https://github.com/nodejs/help/issues/521

**Comment by RIAEvangelist** [comment]
@SupremeTechnopriest you were correct it made a clone for me. Here is the [link](https://stackblitz.com/edit/node-ipc-example-jf6cyc)

@NateTheGreatt Since this is a bug in node, We will need to use a slight work around until the issue is fixed. Add this into your loop to slow it down. I tested and it works. You can run my version of @SupremeTechnopriest's code above to confirm.

```js

      let z = 1e8;
      while (z > 0) {
        let a = 0;
        z--;
        a++;
      }

```

I know its hacky, but it does the trick until the issue is fixed. You might also try using a more stable version of node. 🤷🏻‍♂️

**Comment by SupremeTechnopriest** [comment]
Doesn't look like this is unix socket related.  I switched all the code to use TCP and its the same problem. Its definitely buffer related.  Using objects everything works fine. Sending two buffer encoded messages consecutively only the first arrives unless synthetical latency is introduced.

**Comment by RIAEvangelist** [comment]
Interesting. I'll create another branch to test a fix with you.

**Comment by SupremeTechnopriest** [comment]
I actually am not convinced the issue is related to your module.  We implemented a really simple use case using the `net` package only and the issue persists.  Pretty sure it's a node bug.  UTF-8 encoded string packets: no loss, binary encoded buffer packets: unpredictable loss.

Perhaps we can work together to get the issue solved in node, it seems to happen in v14-v16.  I cant imagine how no one else has hit this yet.  I guess people don't use buffers?

**Comment by RIAEvangelist** [comment]
Yeah, rapid buffer transfers are not so common.

You might try converting the buffers to UTF8 and transmitting them that way.

**Comment by RIAEvangelist** [comment]
Or even base64

**Comment by SupremeTechnopriest** [comment]
we tried every encoding... unfortunately they all have the same results.

**Comment by RIAEvangelist** [comment]
did you try setting `.rawbuffer` to false first? Then sending the utf8 or base64 data?

**Comment by SupremeTechnopriest** [comment]
Sending strings works fine, but we have to send ArrayBuffers as well, so rather then create multiple channels I decided to just make all messages buffers.

The ArrayBuffers are serialized game data and cant really be represented as strings.  Wouldn't want to if we could, would be much too large.

**Comment by RIAEvangelist** [comment]
Also... you might try
`ipc.config.sync = true;`

here is an example, there is also a client example. not sure if it will help, but it very well might. this is a link to the basic TCP sync server example.

https://github.com/RIAEvangelist/node-ipc/blob/master/example/TCPSocket/basicSync/world-server.js

**Comment by SupremeTechnopriest** [comment]
I will give that a go this evening.  What is the difference when you set sync to true?  Is it going to slow things down?

**Comment by RIAEvangelist** [comment]
It should make the messages non-volitile or synchronous. I wrote a bunch of examples in the example folders like `basicSync` The sync should also be documented in the readme. I wrote it so long ago I would need to look at the docs myself.

**Comment by RIAEvangelist** [comment]
I just looked, it is like ack/nack. Set it on the client and it will not send a message until it receives something from the server. Any message will work.

|||
|sync | synchronous requests. Clients will not send new requests until the server answers.|

**Comment by SupremeTechnopriest** [comment]
Hmm okay, sounds like it would fix it but its going to add latency.  Maybe I can use it as a workaround to get unblocked, but we should file an issue with node.js as the buffer packet loss is present in the `net` package. 

Since we are using this for gaming applications, latency is our main enemy.  We need to avoid adding latency where every possible.

**Comment by RIAEvangelist** [comment]
@SupremeTechnopriest is this different than the one @NateTheGreatt linked us to above?

**Comment by RIAEvangelist** [comment]
Also, you could always switch to node v12 if this is a critical issue for you.

**Comment by RIAEvangelist** [comment]
I'm going to close this one for now as this is confirmed a bug in node core.

**Comment by SupremeTechnopriest** [comment]
Same project. We will try a few things and let you know where we land.

**Comment by RIAEvangelist** [comment]
OK. Also, under the discussions tab of this project, I just announced that `v10` will be `ESM`. So if you want to keep using `commonjs`, you will need to explicitly have v9.5.0 or earlier in your `package.json`

**Comment by SupremeTechnopriest** [comment]
ESM would be great!  Looking forward to it.

**Comment by RIAEvangelist** [comment]
Great almost about to start rewriting code. I kept everything the same from a functional and layout perspective to reduce upgrayedd shock.

![](https://media1.tenor.com/images/4601bf352e41795f067486524daf1958/tenor.gif?itemid=4134185)

**Comment by SupremeTechnopriest** [comment]
Sounds good!  Let me know when its ready and I can test it out for you.

**Comment by SupremeTechnopriest** [comment]
Doesn't look like sync did it https://stackblitz.com/edit/node-ipc-example?file=client.js

**Comment by RIAEvangelist** [comment]
@SupremeTechnopriest  I think I may see an issue, you are using the data event. This is triggered with each chunk of data received, Let me adjust your examples. I'll let you know when I'm done here. I reopened because we are still actively working on it together.

**Comment by RIAEvangelist** [comment]
Here is one example, let me know if this helps. I didn't use `rawBuffer=true`, but none the less I did transmit a raw buffer as the payload.

https://stackblitz.com/edit/node-ipc-example-5itt8h?file=server.js

![Capture](https://user-images.githubusercontent.com/369041/124370907-088e8c00-dc31-11eb-81cb-6d215631afd3.PNG)

**Comment by RIAEvangelist** [comment]
Now that example is using `sync` so it adds some latency. I am going to update it to not use sync next and see if that works as well.

**Comment by RIAEvangelist** [comment]
![Oh YEAH](https://media1.tenor.com/images/f94628863c2a4f8122d2ec138a7281d4/tenor.gif?itemid=8291586)

Lightning fast

https://stackblitz.com/edit/node-ipc-example-5itt8h?file=client.js

![Capture](https://user-images.githubusercontent.com/369041/124370942-75098b00-dc31-11eb-9d6d-8ed38c3919ff.PNG)

**Comment by RIAEvangelist** [comment]
Close the issue if this meets your needs plz

**Comment by SupremeTechnopriest** [comment]
This looks good! Thanks for working this out.  Gonna try it in my project and I will reopen if I find any more issues!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
