### ISSUE TITLE
[Question] Communication between clients

### ISSUE THREAD

**Issue by LynMoe** [RIAEvangelist/node-ipc#198]
Hello, thanks for your great library first. I’m working on a project which use cluster and the workers need to access each other. What I’m doing now is create a unix socket from the master and connect that socket from the workers. 
However I find that event can only be emitted by one side(master/worker) and received by another side which is kind of annoying. 
I think it’s like broadcast but not exact it is and some Googling can’t help. So I’m trying to find an answer here: is there a way to emit an event from a client that could be visible to every node listened on the socket?
Thanks in advance.

**Comment by SupremeTechnopriest** [comment]
I solved this by mesh connecting all the nodes. Basically on your main you keep a map of all the sockets that are connected to main.  Each client node is also a server with its own unique unix socket path.  Then a client comes up, connects to main and then main tells that client to connect to all the currently connected nodes, effectively becoming a client to each connected node.

**Comment by LynMoe** [comment]
It seems massive and kind of complex but actually I solved the problem by building a mesh network  either, lol.
The issue could be closed now I think.

**Comment by RIAEvangelist** [comment]
Apologies I was in the hospital for a couple of days, nothing serious.

It looks like y'all (most PC way I could think of to say "yous guys")
worked it out together which is the beauty of open source!

Thanks for making my day a little brighter.

**Comment by SupremeTechnopriest** [comment]
Glad you are okay! Just trying to help out where I can :)

**Comment by RIAEvangelist** [comment]
use UDP. This will allow many to many client to client.
