### ISSUE TITLE
client cant connect to server if server running as service

### ISSUE THREAD

**Issue by si458** [RIAEvangelist/node-ipc#199]
Hi,

if i start the server side code as the `localsystem` user as a windows service,
and run the client as a standard logged in user,

the client never connects to the server?

im starting the server using [winsw](https://github.com/winsw/winsw)
then running the client with `node client.js`

i have just simply copied and pasted from the windowsunix example

**Comment by si458** [comment]
i believe i have found my issue
then the ipc runs the listen command its using the default `false` for `readableAll` and `writeableAll`
https://nodejs.org/docs/v14.17.1/api/net.html#net_server_listen_options_callback
these need to be set as `true` for the pipes to be access by other users 
like running the server as admin/service and the client as a general user

https://github.com/RIAEvangelist/node-ipc/blob/50c0ec6735497c4dbeb2bfe7290b837dc1bf3aeb/dao/socketServer.js#L311-L314

**Comment by si458** [comment]
You could have this option configurable maybe via a variable? That allows the developer to decide if all users or the same user should be used for security reasons

**Comment by si458** [comment]
@RIAEvangelist i believe #205 should allow developer to specify it themselves with defaults of false for security 👍

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
