### ISSUE TITLE
consider adding stop() command to socketServer

### ISSUE THREAD

**Issue by wplittle** [RIAEvangelist/node-ipc#2]
I could see a use case where someone might want to shut down the ipc in their implementation before (or instead of) the process is killed. In a way where the ipc could be started back up later if needed

 e.g. ipc.server.stop();

For instance:

    events.on(
        'shutdown',
        function() {
            ipc.server.close();
            dbConnection.end();
        }
    );

Another use case that I can envision would be to suspend connectivity via IPC due to an issue somewhere else, for instance say the ipc server is also connected to a database server, the database connection goes down for some reason, so until the database connection is restored, I might want to make that whole service inaccessible.

Just a thought, trying to envision this ipc as generic as possible as it will be useful for all kinds of stuff....

**Comment by RIAEvangelist** [comment]
I think this issue is still valid and would be good to implement

**Comment by dj-hedgehog** [comment]
I'm interested in this too.
Why do I get  `ipc.server.end is not a function` when all you use is `net.socket` ?

**Comment by RIAEvangelist** [comment]
We definitely need to document how to properly use this.

The lack of documentation means we expect the user to understand whats going on which is not good practice.

@dj-hedgehog what we'll need to create is a method called ` stop ` which does :

    ipc.server.stop= function(){
        ipc.server.server.close();
        ipc.server.server.destroy();
    }

I think.

So for now you can use either of the calls displayed inside of the code above.

**Comment by RIAEvangelist** [comment]
@mayberex
wanna handle this?
