### ISSUE TITLE
Some TCP tests failing on ubuntu

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-ipc#207]

**Comment by RIAEvangelist** [comment]
Looks like it may be something to do with pathing

**Comment by RIAEvangelist** [comment]
the issue seems to be git ignoring capitalization changes in file names

**Comment by RIAEvangelist** [comment]
fixed test UDP file name capitolization

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
