### ISSUE TITLE
CommonJS support (for Electron)

### ISSUE THREAD

**Issue by mckravchyk** [RIAEvangelist/node-ipc#208]
I want to use node-ipc in an Electron app, and as far as I know, [Electron does not support ESM at all](https://github.com/electron/electron/issues/21457).

Is there a way to use this module via `require`? If not, would you consider supporting CommonJS alongside ESM?

**Comment by mckravchyk** [comment]
I see that ESM was added very recently and the v9.x.x will support CommonJS.

**Comment by RIAEvangelist** [comment]
As far as I am awaer electron is ESM only from v5 on and the current rev is 13.x thanks for closing and updating though.

**Comment by RIAEvangelist** [comment]
Also, electron should support esm fully as well.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
