### ISSUE TITLE
10.0.1 no longer usable in standard node 14

### ISSUE THREAD

**Issue by si458** [RIAEvangelist/node-ipc#209]
after installing the newest version 10.0.1 its now unusable with nodejs

```
PS C:\Users\Simon\Documents\ourmonitoring\nodejs> node .\index.js
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\Simon\Documents\ourmonitoring\nodejs\node_modules\node-ipc\node-ipc.js
require() of ES modules is not supported.
require() of C:\Users\Simon\Documents\ourmonitoring\nodejs\node_modules\node-ipc\node-ipc.js from C:\Users\Simon\Documents\ourmonitoring\nodejs\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename node-ipc.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\Simon\Documents\ourmonitoring\nodejs\node_modules\node-ipc\package.json.
```

**Comment by si458** [comment]
its ok i worked it out, totally missed the notes in the releases page haha
(could you maybe add some info into the readme about this?)
in my `package.json` i set a version less than 10.0.0 `"node-ipc": "<10.0.0"`

**Comment by RIAEvangelist** [comment]
Sure, thats a cool idea. Thanks once again!

**Comment by RIAEvangelist** [comment]
Glad you caught this because i have other issues in the docs lol!

**Comment by RIAEvangelist** [comment]
ahhh crap I need to fix the examples too !!! 

THANK YOU SO MUCH!

**Comment by si458** [comment]
@RIAEvangelist no worries! brilliant module! always happy to help!
it was just what i needed for my node app running as a windows service to talk to my normal node app the user is running to take a screenshot haha!

**Comment by RIAEvangelist** [comment]
Whew, it was just the cluster example that I hadn't updated.

Glad you found use for it. If you do any front end work, keep an eye on my `noaki` and `nozaki-components` repos. I hope they help to promote vanilla web components.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
