### ISSUE TITLE
Connect to node-ipc in Golang

### ISSUE THREAD

**Issue by phuonghuynh** [RIAEvangelist/node-ipc#211]
I was using this great IPC Library for my nodejs server and now I would like to create a Golang Client connect to this server. Is there any suggestion on implement Golang client connect to "node-ipc" service?

Thanks

**Comment by RIAEvangelist** [comment]
yes, just open a socket in golang and parse the incoming information with a delimiter of `\f` or `\d` whatever you use as a deliminator in your `node-ipc` code config

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
