### ISSUE TITLE
Destroy Unix/Windows socket server from another process

### ISSUE THREAD

**Issue by mckravchyk** [RIAEvangelist/node-ipc#213]
Is there a way to destroy a Unix/Windows socket by name if it exists before starting the server?

I'm running into a problem with "unwanted caching" in my app where the client connects to an older instance of the server from previous run rather than the new (because the socket name is the same and the old "rogue" server process is still running).

I understand this is an issue with my app because I should kill the process that hosts the server when app quits, but I want to anticipate a scenario where the serving process does not exit for any reason (i.e. app crashes).

Ideas I thought about:
- I noticed that if I manually remove the socket file before running the app, the new server will be used. Would that be a viable  solution? Is it going to work on Windows too? (does Windows socket use files?).
- Perhaps I  could expose an 'exit' handler that would wait for an exit message and quit the server when  such a message is received. It adds up to the startup time though
- I could generate a unique id so a socket in each run has a different name but it has an additional overhead to pass the  id between processes before the server is started

Is there a better way to do this? 

I also tried to use `config.unlink` but it didn't seem to have an effect.

**Comment by mckravchyk** [comment]
I can detect and kill any rogue leftover processes when the app initializes and this is the most universal solution for this case.

The exact solution is to create a lock file for the process that is hosting the IPC server, the lockfile contains the process pid. Then when the app starts, it checks if the lockfile is present, gets the pid, gets the name of the process running that pid and if it exists and name matches, kills it.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
