### ISSUE TITLE
Using node-ipc with react results an additional loader problem

### ISSUE THREAD

**Issue by Abdulrahman-Khalid** [RIAEvangelist/node-ipc#214]
I am trying to use node-ipc with react because I want to connect to unix socket

I tried the following piece of code

```
import ipc from 'node-ipc';
var socket = RootIPC.connectTo('unit-hal', UnixSocketPath);
socket.on('message', (data) => {
// Some Code
});

```

But I am getting this error while compilation

```
./node_modules/node-ipc/node-ipc.js 8:6
Module parse failed: Unexpected token (8:6)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   }
| 
>   IPC = IPC;
| }
|
```

**Comment by RIAEvangelist** [comment]
The module is a vanilla ESM. You may need an ES6 ESM. 

Also, just to make sure, you are doing this on the server-side right? Never hurts to ask.

**Comment by RIAEvangelist** [comment]
Any updates on this? Were you able to get what you expected working?

**Comment by RoelVB** [comment]
I had the same issue, not doing anything special, just trying to bundle using Webpack.
Solved it for now by going back to node-ipc 9.x. This works without any issues.

**Comment by RIAEvangelist** [comment]
That's super weird. You might try not transpiling, just bundling.

**Comment by wips** [comment]
Having the same issue with v10, downgrading to v9 helped. I use node-ipc with typescript and among few dozen packages this was the only issue. Just in case here's my TS config:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "noImplicitOverride": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "target": "ES2020",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": ".",
    "incremental": true
  },
  "include": [
    "src",
    "scripts",
    ".eslintrc.js",
    "e2e"
  ]
}
```

**Comment by RIAEvangelist** [comment]
Additional functionality should now be added via v10.1.0

CJS support added in PR #219 by @tripodsgames

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
