### ISSUE TITLE
IPC Unix Socket Multi Server 

### ISSUE THREAD

**Issue by NN-Binary** [RIAEvangelist/node-ipc#216]
Hello,

How can I open multiple servers (socket) at the same time?

```
        ipc.serve(IPCPath, function() {
                       
           //ipc.server

});
ipc.server.start();

```

It works well with 1 server but with multiple servers all messages get lost, my first hint is simply because everything is in ipc.server.

How can I do? I want 20 IPC servers (different paths running) and unlimited amount of clients for each.
Thanks for the help

**Comment by RIAEvangelist** [comment]
Looks like you figured it out?

**Comment by inceabdullah** [comment]
I think he did.
in these lines, Class was exported, in
https://github.com/RIAEvangelist/node-ipc/blob/master/node-ipc.js#L14-L17
```
export {
    singleton as default,
    IPCModule
}
```

`const singleton=new IPCModule;`
singleton was exported as default.

Anyone could use another server, with like:
```
import ipc from "node-ipc"
const _ipc2 = ipc.IPCModule
```

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
