### ISSUE TITLE
require('node-ipc') is not work.

### ISSUE THREAD

**Issue by radiorz** [RIAEvangelist/node-ipc#218]
I use node with commonjs how to require this module
environments:
- nodejs v14.17.5
- node-ipc v10

**Comment by radiorz** [comment]
The document say that new version didnt suit for commonjs. but how to make it work ?

**Comment by RIAEvangelist** [comment]
You would probably want to use the `import()` function instead of the
require statement.

Maybe something like :

```js

//in v14+ versions of node
const IPC = await import('node-ipc');

//in older than v14
(async () => {
const IPC = await import('node-ipc');
})();

```

**Comment by tripodsgames** [comment]
I'm working on a PR to add commonjs support to v10.

https://github.com/RIAEvangelist/node-ipc/pull/219

**Comment by RIAEvangelist** [comment]
not sure, I will have a look, it should be compatible with commonJS

**Comment by patricthysell** [comment]
Hi, I had the same issue, when using node v10.24.1 and node-ipc v10.1.0. Theres kind of a migration situation with the ie6 modules (I guess) that sometimes creates problems using the old-fashioned require() for older node versions (like the 10.24.1)
I took the easy way out and used **node-ipc v9.1.1** I knew to work from a previous version - that did everything for me back then, and it looks perfectly fine for the demo I'm currently putting together.

**Comment by frzsombor** [comment]
Related to #221 and you can find the solution here: https://github.com/RIAEvangelist/node-ipc/issues/221#issuecomment-963206238

**Comment by RIAEvangelist** [comment]
I added this to the read me as in the past week or two we have had 3 issues filed on people not knowing this.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
