### ISSUE TITLE
ipc.config undefined with the latest version and node >= 16

### ISSUE THREAD

**Issue by ryanocf** [RIAEvangelist/node-ipc#221]
node: v16.13.0
npm: 8.1.2
OS: Windows 10 21H1 19043.1320

Hello,

I just installed the latest version of node-ipc (10.1.0) and want to use it that 2 different independent node processes can communicate with each other.
I straight copied the example and tried to run my server but for some reason the config property is undefined.
I created and tried it with a complete new project but it doesn't seem to work there either.
I tried the node-ipc^9.0.0 version and there it seems to work.

But I wonder why it doesn't work with the latest node-ipc version when in the readme it states: node >= 14

node-ipc^10.1.0
```js
const ipc = require('node-ipc');
console.log(ipc.config);

/* console output:

D:\Projects\test>node index.js
undefined

*/
```

node-ipc^9.0.0
```js
const ipc = require('node-ipc');
console.log(ipc.config);

/* console output:

D:\Projects\test>node index.js
Defaults {
  appspace: 'app.',
  socketRoot: '/tmp/',
  id: 'DESKTOP-RS66GLD',
  encoding: 'utf8',
  rawBuffer: false,
  sync: false,
  delimiter: '\f',
  silent: false,
  logDepth: 5,
  logInColor: true,
  maxConnections: 100,
  retry: 500,
  maxRetries: Infinity,
  stopRetrying: false,
  IPType: '',
  tls: false,
  networkHost: '127.0.0.1',
  networkPort: 8000,
  interface: {
    localAddress: false,
    localPort: false,
    family: false,
    hints: false,
    lookup: false
  }
}

*/

**Comment by RIAEvangelist** [comment]
have you tried logging out ipc?

**Comment by getlarge** [comment]
@ryanocf Try with `const ipc = require('node-ipc').default;`

**Comment by ryanocf** [comment]
> @ryanocf Try with `const ipc = require('node-ipc').default;`

Ah lol.
That works. Thanks a lot.

**Comment by RIAEvangelist** [comment]
@getlarge or @ryanocf what sort of use leads to this, I would like to add it to the docs.

@getlarge thanks  btw

**Comment by getlarge** [comment]
@RIAEvangelist Not sure i understand your question...
Between v9 to v10, it seems you added support for ESM and i guess the way you export the singleton in `node-ipc.js` has an influence on how the build will assign `singleton` in `node-ipc.cjs`.

That's `node-ipc.cjs` l.185 :
```js
__export(exports, {
  IPCModule: () => IPCModule,
  default: () => singleton
});
```

**Comment by RIAEvangelist** [comment]
Yeah it's just he was running in CommoJS and that's what esbuild made... Can document that.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
