### ISSUE TITLE
Unlink of the unix domain socket

### ISSUE THREAD

**Issue by tenbits** [RIAEvangelist/node-ipc#223]
Hello Team,

I haven't found the discussion regarding the `unlink` option and the the unix domain sockets.  

Consider this line of code: 

[https://github.com/RIAEvangelist/node-ipc/blob/7a614ce9bee54a7f9348e6397a4b0c4b0a08a34d/dao/socketServer.js#L54](socketServer.js#L54)
```js
if(this.config.unlink){
    fs.unlink(
        this.path,
        startServer.bind(this)
    );
 }
```

This could be dangerous, as there are no check if a server already running. And if it does, that one will get stuck, as this process takes the server role over.
Running the `node-ipc` with `unlink: false` could be also not a good option, as Unix doesn't clean the socks files by itself, means if there was already a server running, and has existed without cleaning the file, the next time the server won't be started. _Unfortunately, it seems, it is not possible to lock the file during the server is running, to be sure any other process won't unlink the file and won't take the server role over._

What I'm proposing is:

1. Add a new option smth. like `unlinkChecked`
2. Try to start the server without any `unlinking`
3. if we get  `EADDRINUSE` error(means the file already exists) we double check the socket:
4. Try to connect with this `path`, 
5. if successful, means the server is already running, so we throw the exception.
6. if we get `ECONNREFUSED` means nobody listens to the socket, so we are safe to `unlink` the file, and start the server over again.

Would you be interested in such a PR? Or maybe somebody has any other thoughts?

**Comment by RIAEvangelist** [comment]
I think a PR for this could be helpful provided it is simple and limited to this functionality. We don't want to change other functionality by handling this as these scenarios can be handled currently by checking and handling errors in the code which uses node-ipc. We also do not want to create further edge cases with the PR.
