### ISSUE TITLE
Looking for guidance with node-ipc 9

### ISSUE THREAD

**Issue by ed4becky** [RIAEvangelist/node-ipc#224]
I am writing an electron app, so stuck with commonjs modules - thus the v9 constraint.

When I create a connection, then try to register any listener, node-ipc fails.  That is, event-pubsub fails when doing the !this._event_[type] check.

It seems that "this" is referring to the function "on" instead of the event-pubsub instance, and find a non-existent _event_

not sure how to make it work.

    const ipc = require('node-ipc');
        this.ipcConnect(name, function (client) {
          client.on('connect', () => {   << client looks good, but "this" in the "on" function is not for the class

**Comment by RIAEvangelist** [comment]
You can use es6 in electron if you want to, there is no hard limitation. If you wrote your code base in commonjs though, just use the latest revision and do the following:

```js
const ipc = require('node-ipc').default;
```
