### ISSUE TITLE
How to know if a rawbuffer is done? 

### ISSUE THREAD

**Issue by gebrits** [RIAEvangelist/node-ipc#225]
I'm trying to send a buffer of multiple MBs over IPC with settings: 

```
ipc.config.rawBuffer = true
ipc.config.encoding='hex';
```

This results in the client receiving this buffer in chunks of 8192 bytes. 
is there a robust way to know when the server is done sending the entire buffer? 
Atm, I'm doing the following, but this feels really brittle: push all the chunks in an array until a chunk is received with length !== 8192. In that case combine all chunks using `Buffer.concat(chunks)` and proceed from there. 

Specifically, the edge-case where `buffer.length % 8192 === 0` would fail. Also I'm not entirely sure if chunk-size 8192 is OS-specific.

Is there a better way?

**Comment by RIAEvangelist** [comment]
I think you would use the delimiter.

But also, I think this is all already handled in the library no?

**Comment by gebrits** [comment]
> But also, I think this is all already handled in the library no?

Handled by node-ipc you mean? Afaik, no. I don't think there's a way to listen to an end-message event or something if that's what you mean. It might well be that I'm mistaken there of course. 

The client code I'm using now listens to the 'data'-event. It this too low level? 

```
const chunks = []
await new Promise(resolve => {
    ipc.of.arrow.on('data', async (chunk) =>{
      chunks.push(chunk)
      if(chunk.length === 8192) return
      resolve()
    });
})
const buf = Buffer.concat(chunks);

```

**Comment by gebrits** [comment]
Does anyone have an idea? I'm currently testing this out on another platform which uses totally different IPC buffer sizes so the above breaks pretty bad

**Comment by RIAEvangelist** [comment]
I would recommend you either use a static buffer size OR you parse the buffer as you get it looking for a message delimiter.

**Comment by RIAEvangelist** [comment]
The message size part is baked into the library. As are delimiters, but I think the delimiter is ignored for raw buffers. 

When I have integrated with c, the message sizes were always predefined.

**Comment by gebrits** [comment]
I'm using node-ipc for the server as well as client. On (my) ubuntu 21.04 the buffer-size is 65536 where on Mac OS Big Sur it's 8192. I solved my adding an explicit delimiter  as follows: 

server: 
------
```
// dfSer is the original buffer I want to send
const delimiterBuffer = new TextEncoder("utf-8").encode("\n");
const buf = new (dfSer.constructor)(dfSer.length + 1); // add delimiter
buf.set(dfSer, 0);
buf.set(delimiterBuffer, dfSer.length);
ipc.server.emit(socket,buf);

```
client
--------

```
await new Promise(resolve => {
  ipc.of.arrow.on('data', async (chunk) =>{
    chunks.push(chunk)
    if(new TextDecoder("utf-8").decode(chunk.slice(-1)) !== '\n') return // not done yet until delimiter found
    resolve()
  });
})

```

**Comment by RIAEvangelist** [comment]
Awesome!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
