### ISSUE TITLE
Bottleneck when connecting multiple clients over same socket

### ISSUE THREAD

**Issue by gebrits** [RIAEvangelist/node-ipc#226]
I'm communicating between 1 server and multiple clients where both clients and server use node-ipc. I use 'rawBuffer' to communicate. 

While request time on the server side stays a respectable 50-100ms per 50MB, when increasing clients I see performance go up from 100-150ms for 1 client to 2000-4000ms for 10 clients. I'm not cpu bound on the client. 

I'm connecting all clients to the same socket. Flow per client: 

- make connection to socket
- do request
- receive response
- close connection. 

Is it best practise to: 

- connect multiple clients to the same socket?  Can it be that somehow the throughput of 1 socket is the bottleneck, and that using 1 socket per client (negotiate name of the socket to create in first communication over 'admin-socket) would be a better approach?
- open/close a new connection per request? Is there much overhead in this?

**Comment by gebrits** [comment]
Forgot to ask: share memory buffers doesn't exist as an option for Node-ipc correct? afaik, that should be the fastest by far. Is there a particular reason you choose not to implement it?

**Comment by RIAEvangelist** [comment]
what you are running into is the queuing system. Sadly the code is being run by JS so the server may be be able to handle the requests in 50-100ms however when you include piping the 50MB request out to the client this likely causes some delay between client requests.

I would suggest doing a cluster of node-ipcs or spinning up a couple of them to load balance with. 

The cluster is probably the simplest solution provided the NAT is not your bottleneck.

I haven't actually tried this code, just pseudocoding off the top of my head here but :

```js

import cluster from 'cluster';
import ipc from 'node-ipc';
import { cpus } from 'os';
import process from 'process';

const numCPUs = cpus().length;

if (cluster.isPrimary) {
  console.log(`Primary ${process.pid} is running`);

    // Fork workers.
    for (let i = 0; i < numCPUs; i++) {
        cluster.fork();
    }

    cluster.on(
        'exit', 
        (worker, code, signal) => {
            console.log(`worker ${worker.process.pid} died`);
        }
    );
} else {
  // Workers can share any network socket connection.... maybe any local one too??? IDK
  ipc.serve(blah blah blah)

  console.log(`Worker ${process.pid} started`);
}

```

**Comment by RIAEvangelist** [comment]
Also, to answer your question about shared buffers, I wrote this originally with node v6 I think and SharedArrayBuffer wasn't available until 8.

I would be happy to accept a PR if you offered though. Otherwise, the cluster should get it done pretty well for you I think.

**Comment by gebrits** [comment]
Cheers, I'll look into the cluster-variant. 
BTW: had a look into SharedArrayBuffer. It seems this only works between parent-child and/or worker-threads. But not the general case of sharing memory between 2 separate processes (client + server)

**Comment by RIAEvangelist** [comment]
Good to know about the SharedBuffer. Thanks for the information.

Sharing the same memory between two processes might create a bit of a chimera if it did work, it would be fast though.

**Comment by gebrits** [comment]
Happy to report clustering enabled a factor 2 improvement in overall throughput. 
The bottleneck now is the client (cpu). 

To that end I now start a worker-thread in which I start the IPC client -> do the call -> receive the buffer and return using parentPort.postMessage() the the parent. Overall another factor 2.5 improvement. 

I'm sure there's still some low hanging fruit somewhere, but I can live with the throughput for now :)
Many thanks

**Comment by RIAEvangelist** [comment]
woot!!! Thanks for the update. I'm quite relieved that my ideas were
correct. I just made the comments off the cuff so I was only giving my own
thoughts a 50/50 chance until I knew more about how they worked with your
specific code.
