### ISSUE TITLE
[EDITED] Switch to nozaki-colors module

### ISSUE THREAD

**Issue by waynebloss** [RIAEvangelist/node-ipc#227]
The README has some code examples that use these unexplained string fields. What are they and where do they come from?

.e.g.
```js
ipc.log('got a message : '.debug, data);
ipc.log('## connected to world ##'.rainbow, ipc.config.delay);
ipc.log('disconnected from world'.notice);
```
I searched your codebase and I couldn't find any implementation of these.

So, is `node-ipc` using a dependency that modifies the `String` prototype to include those fields or is that just something you have setup for your own examples environment?

**Comment by waynebloss** [comment]
OK, so it looks like you're using `colors` [npm](https://www.npmjs.com/package/colors), but only in your examples, not as part of your package.

Pretty easy to test over at [runkit](https://npm.runkit.com/node-ipc) with `var ipc = require("node-ipc").default; ipc.log('Hello'.rainbow);`

**Comment by waynebloss** [comment]
I'm embarrassed now :blush: since I've been using Node.js since 2010 and I also just read about the whole `colors` debacle last week or so... but I just never used it! :rofl:

**Comment by RIAEvangelist** [comment]
@waynebloss I am reopening this ticket to aswitch to using the `nozaki-colors` module! Thanks sop much for pointing this out!!
