### ISSUE TITLE
Windows Sockets not sending EADDRINUSE in IPC error event

### ISSUE THREAD

**Issue by ShubhenduVaid** [RIAEvangelist/node-ipc#228]
Looks like the the [issue ](https://github.com/RIAEvangelist/node-ipc/issues/112) has reappeared.

I am using the version 9.2.1 of node-ipc library.
While using Windows Sockets EADDRINUSE is not being sent to IPC error event.

I could see a log from SocketServer.js at
https://github.com/RIAEvangelist/node-ipc/blob/master/dao/socketServer.js#L289

but the error is not transmitted to error handler.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
