### ISSUE TITLE
Is IPC viable to communicate native addons (n-api) with the front-end? is:question 

### ISSUE THREAD

**Issue by jared-ortega** [RIAEvangelist/node-ipc#229]
I'm trying to send numbers generated by a nodejs native addon (n-api) via socket.io. The problem is that simply socket.io does not send the data when I ask it, it does not work.

https://github.com/nodejs/node-addon-examples/tree/main/async_work_thread_safe_function/napi

The following code is used to print in the server console the generated numbers: 

```
addonnative.startThread((thePrime) =>
  console.log("Received prime from secondary thread: " + thePrime));
```

I tried to send them to my front-end with this code:

```
socket.on('addonexe', ( ) => {
addon.startThread((thePrime) => socket.emit('dataout', thePrime));
});
```

Well, what should I use node-IPC to send data from the addon?

Node-ipc allows to send napi_value variables?

**Is my approach correct or should I implement sockets in c++?**

Any suggestion would be useful, thanks.

**Comment by jared-ortega** [comment]
It was not a problem, it was a lack of documentation on my part, sorry.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
