### ISSUE TITLE
No documentation for `.once()`?

### ISSUE THREAD

**Issue by dush-t** [RIAEvangelist/node-ipc#231]
In the source, there is a function named `once` which can be used to listen to one-off events, and it seems to be working as well. However, it is not mentioned anywhere in the documentation.

I have the following questions - 
1. Does this mean this API may be deprecated soon? 
2. Should I not use it in my code? 
3. If so, how can I listen for one-off events?
4. Is there a way I can de-register a listener for a certain event? Something like `document.removeEventListener` in DOM.

TIA!

**Comment by RIAEvangelist** [comment]
This is actually a part of [event-pubsub](https://github.com/RIAEvangelist/event-pubsub)

**Comment by RIAEvangelist** [comment]
LMK if you have any other questions.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
