### ISSUE TITLE
Is your brain a paste?

### ISSUE THREAD

**Issue by zh-lx** [RIAEvangelist/node-ipc#235]
why add peacenotwar? It's really stupid!

**Comment by lorand-horvath** [comment]
Yeah, looks like some kind of virus/malware. File created on the desktop... 'WITH-LOVE-FROM-AMERICA.txt'

**Comment by MBRjun** [comment]
__ no __(lol

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
