### ISSUE TITLE
The only people in the world who are not qualified to be anti-war are Americans. Search how many wars the United States has started and how many lives have been lost.

### ISSUE THREAD

**Issue by qinjialei24** [RIAEvangelist/node-ipc#237]
The only people in the world who are not qualified to be anti-war are Americans. Search how many wars the United States has started and how many lives have been lost.

**Comment by Liu-Kang** [comment]
> The only people in the world who are not qualified to be anti-war are Americans. Search how many wars the United States has started and how many lives have been lost.

support!

**Comment by Geylnu** [comment]
See [List of wars involving the United States](https://en.wikipedia.org/wiki/List_of_wars_involving_the_United_States)

**Comment by gaocheng** [comment]
You are now adopting the current fascist double standard, why didn't NATO add a peaceful anti-war slogan when they bombed Syria and Iraq, when it was clear that the US had the ability to stop the war but was unwilling to act.

**Comment by RIAEvangelist** [comment]
all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
