### ISSUE TITLE
Sabotaging Users, Poisoning Open Source, Fake Anti War

### ISSUE THREAD

**Issue by jukrb0x** [RIAEvangelist/node-ipc#238]
# 1. It is never a proper way to protest and advocate anti-war, by writing irrelevant and `malicious` code to open source users to broadcast `your personal sentiment`.

# 2. You should be `shamed` on node community, whatsoever the Stars or Forks of your project, You are `poisoning` innocent developers and the network, your personal morality should never ever be a `major part` in the supply chain. You are responsible for the code you opensouced, even there is no bottom line for this, I believe an entity like you has no bottom line of morality for being a real protester or a fighter, you are being a joke, a kindergarten kid.

# 3. I just want to ask, Is R&U war the ONLY war now? Are you a _real_ protester to war, or just advocate your personal political belief? You are so `naive`

# 4. The case shows the `vulnerability` of nodejs package system, a lunatic changes lines of code, the trust chain is already broken by what you did, You are just trash, Open Source Community ashamed of you.

**Comment by jukrb0x** [comment]
Personally, I want to say, you mothf**er , go to the fucking hell @RIAEvangelist

**Comment by RIAEvangelist** [comment]
all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented. 

feel free to lock the dep version.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
