### ISSUE TITLE
A MADMAN'S DIARY

### ISSUE THREAD

**Issue by ChloePrime** [RIAEvangelist/node-ipc#241]
I tried to look this up, but my history has no chronology, and scrawled all over each page are the words: "Peace from America" Since I could not sleep anyway, I read intently half the night, until I began to see words between the lines, the whole book being filled with the two words—"War and Sabotage!"

**Comment by Nauxscript** [comment]
Lu xun damn genius！

**Comment by SimonGH0STRiley** [comment]
迅哥：我真说过！

**Comment by lyscf** [comment]
老周树人了

**Comment by RIAEvangelist** [comment]
all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented.
