### ISSUE TITLE
SHAME ON YOU, ASSHOLE. YOU JUST FUCKING BROKE OUR COMPUTER AND MAKE THE CONDITION OF UKRAINE WORSE

### ISSUE THREAD

**Issue by kenvix** [RIAEvangelist/node-ipc#245]
# FUCK YOU AND FUCK AMERICA
# SHAME ON YOU, ASSHOLE. YOU JUST FUCKING BROKE OUR COMPUTER AND MAKE THE CONDITION OF UKRAINE WORSE
# THE WORLD WILL BECOME PEACE IF THERE IS NO FUCKING AMERICA

**Comment by MBRjun** [comment]
https://en.wikipedia.org/wiki/List_of_wars_involving_the_United_States

**Comment by SngBlog** [comment]
I agree, America is just a diabolical capitalist, war madman, and a villain with good words behind his back

**Comment by VirensCn** [comment]
I agree

**Comment by JeffyLapter** [comment]
I agree

**Comment by MBRjun** [comment]
很难不同意

**Comment by xukaijie111** [comment]
I agree

**Comment by RIAEvangelist** [comment]
all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented.

**Comment by Wojnr** [comment]
so why the fuck you xenophobic fucks use american github?

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
