### ISSUE TITLE
Please put this on NATO's computers

### ISSUE THREAD

**Issue by ChloePrime** [RIAEvangelist/node-ipc#246]
Russia lives matter!

**Comment by ChloePrime** [comment]
Moved to [https://github.com/RIAEvangelist/peacenotwar/issues/8](url)

**Comment by RIAEvangelist** [comment]
all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented. 

This will go on any computer that uses it too.

**Comment by RhinoCodes** [comment]
@ChloePrime All people in NATO countries lives matter too

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
