### ISSUE TITLE
IF U REALLY ANTI-WAR, U SHOULD GO FK USA, NOT RUSSIA

### ISSUE THREAD

**Issue by Dr3amdiv3r** [RIAEvangelist/node-ipc#250]
People who start the war again and again shout for the peace, lmao
How many kids were killed by U.S. Army and its servants in Afghanistan?
And now, focking nz is killing people, threating the real democracy and freedom and u jumped out like a poor clown?
Go fk yourself u shameless SS, U WILL BE DROPPED INTO HISTORICAL TRASH CAN WITH YOUR FKING GOVERNMENT!!!
SON OF A BEACH

**Comment by ZhuoranLyu** [comment]
All Americans should be killed.

**Comment by lyscf** [comment]
> All Americans should be killed.

这倒不至于兄弟，偏激了

**Comment by Dr3amdiv3r** [comment]
> All Americans should be killed.

Cmon, don't go to the other extreme, we should seperate enemy and friend, our enemy is those capitalists and their "honest" henchman, not the people of America, what we should do is to let them wake up from being brainwashed, let them see the disgusting essence of their facist government. They'll be happy to stand up and fight for their own sunshine. :-)

**Comment by broodje-kroket** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by BitesizedLion** [comment]
> 动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

Sorry pal, won't work.

**Comment by dingyx99** [comment]
> 动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

Using an account registered an hour ago just for poring such kind of garbage? 
And don't you know owing one more GitHub account against the ToS?

Reference: https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#3-account-requirements

**Comment by Nugine** [comment]
@broodje-kroket North Dakota Access Pipeline Protests 北达科他州接入管道抗议 Ferguson Riots 弗格森暴动 2017 St. Louis protests2017年圣路易斯抗议活动 Nuclear testing at Bikini Atoll 比基尼环礁的核试验 Unite the Right rally 团结右集会 Charlotte riots 夏洛特暴动 Attack on the Sui-ho Dam 袭击穗河水坝 Milwaukee riots 密尔沃基骚乱 Shooting of Alton Sterling and Philando Castile 奥尔顿·斯特林和菲兰多·卡斯蒂利亚的射击 Occupation of the Malheur NationalWildlife Refuge Malheur国家野生动物保护区的占领 death of Freddie Gray 弗雷迪·格雷的死 Shooting of Michael Brown迈克尔·布朗的拍摄 death of Eric Garner, Oakland California 奥克兰奥克兰市埃里克·加纳（Eric Garner）逝世 Operation Condor 神鹰行动 Occupy WallStreet 占领华尔街 My Lai Massacre 我的大屠杀 St. Petersburg, Florida 佛罗里达州圣彼得堡 Kandahar Massacre 坎大哈屠杀 1992Washington Heights riots 1992年华盛顿高地暴动 No Gun Ri Massacre 无枪杀案 L.A. Rodney King riots 洛杉矶罗德尼·金暴动 1979 Greensboro Massacre 1979年格林斯伯勒大屠杀 Vietnam War 越南战争 Kent State shootings肯特州枪击案 Bombing of Tokyo 轰炸东京 San Francisco Police Department Park Station bombing 旧金山警察局公园站爆炸案 Assassination of MartinLuther King, Jr. 小马丁·路德·金遭暗杀。 Long Hot Summer of 1967 1967年炎热的夏天 Bagram 巴格拉姆 Selma to Montgomery marches 塞尔玛到蒙哥马利游行 Highway of Death 死亡之路 Ax Handle Saturday 星期六斧头 Battle of Evarts 埃瓦茨战役 Battle ofBlair Mountain 布莱尔山战役 McCarthyism 麦卡锡主义 Red Summer 红色夏天 Rock Springs massacre 岩泉大屠杀 Pottawatomie massacre 盆大屠杀 Jeju uprising 济州起义 Colfaxmassacre 科尔法克斯大屠杀 Reading Railroad massacre 阅读铁路大屠杀 Rock Springs massacre 岩泉大屠杀 Bay viewMassacre 湾景大屠杀 Lattimer massacre 拉蒂默大屠杀 Ludlow massacre 拉德洛屠杀 Everett massacre 埃弗里特屠杀Centralia Massacre 中部大屠杀 Ocoee massacre Ocoee大屠杀 Herrin Massacre 赫林大屠杀 Redwood Massacre红木大屠杀 Columbine Mine Massacre 哥伦拜恩矿难 Guantanamo Bay 关塔那摩湾 extraordinary rendition 非凡的演绎 Abu Ghraib torture and prison abuse 阿布格莱布的酷刑和监狱虐待 Henry Kissinger 亨利·基辛格

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
