### ISSUE TITLE
Conditional Chaining of peacenotwar breaks my build

### ISSUE THREAD

**Issue by davemoser** [RIAEvangelist/node-ipc#253]
Despite the fact that I am not happy with your approach to bring political topics into the code, I also have the problem that this new extension breaks my build.

I use node-ipc and until now I have used always the newest version of the Node <14 versions.
So 9.2.2 is my current choice.

But now my build breaks, because peacenotwar is using **conditionalChanining**.
This is not supported by my build-tools. ConditionalChanining is a new technology that is still experimental based on [Mozilla](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

It would be nice if you could fix this so that your extension at least does not break builds! Thanks in advance!

**Comment by RIAEvangelist** [comment]
Thanks. I will have a look at it. I used ESbuild to transpile. I'll try to update tonight.

**Comment by BobHassok** [comment]
> Thanks. I will have a look at it. I used ESbuild to transpile. I'll try to update tonight.

Sure will be difficult for you to make changes to the code when you're in prison. I hope you are arrested. 

#390
