### ISSUE TITLE
peacenotwar

### ISSUE THREAD

**Issue by xukaijie111** [RIAEvangelist/node-ipc#254]
fuck U PeaceNotWar
No quality, no education

**Comment by RIAEvangelist** [comment]
all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
