### ISSUE TITLE
--

### ISSUE THREAD

**Issue by height** [RIAEvangelist/node-ipc#255]
<img width="977" alt="CleanShot 2022-03-16 at 17 35 45@2x" src="https://user-images.githubusercontent.com/1542746/158560661-6dd39b33-ce2d-42b5-9081-9484aa2b140d.png">

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
