### ISSUE TITLE
Please do not add malicious code to open source repositories, this should be discussed in the community

### ISSUE THREAD

**Issue by polarbear88** [RIAEvangelist/node-ipc#262]
Please do not add malicious code to open source repositories, this should be discussed in the community

**Comment by RIAEvangelist** [comment]
all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented.

**Comment by vshymanskyy** [comment]
[![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)
