### ISSUE TITLE
Remove malicious code

### ISSUE THREAD

**Issue by mewforest** [RIAEvangelist/node-ipc#265]
Remove peacenotwar completely, you have no argue for keeping that harmful behavior in your library.

Note: If I'm born in Russia, then I'm not responsible for Putin's choices, because in Russia there is no democracy. It's a myth. You can see it by analyzing the destiny of Navalny. You also can't see a real statistics of opinions in Russia, because there is no freedom of speech in that.

By the way, what if I create site with your library against the war, for example? You will drop my files then too. But did you ask me about supporting the war? Not. So, you are the same as Russian government.

**Comment by RIAEvangelist** [comment]
all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented. 

You can lock the dep version if you do not like it.

**Comment by foxodever** [comment]
Ran out of arguments and closed all issues XD

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
