### ISSUE TITLE
Черт

### ISSUE THREAD

**Issue by jora535** [RIAEvangelist/node-ipc#266]
Соси хуй пидар

**Comment by Eugeny** [comment]
@jora535 иди нахуй, русский оккупант.

**Comment by RhinoCodes** [comment]
@Eugeny Dude, just because they speak russian does not mean he is a russian, and even if they are they probably dislike the war.

**Comment by 0loli** [comment]
> @jora535 иди нахуй, русский оккупант.

Хохол, спокуха

**Comment by jora535** [comment]
Конченные мрази гореть вам в аду

**Comment by Eugeny** [comment]
> @Eugeny Dude, just because they speak russian does not mean they are a russian, and even if they are they probably dislike the war.

Their avatar is saying it all.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
