### ISSUE TITLE
my mind is dead

### ISSUE THREAD

**Issue by MichaelEpicA** [RIAEvangelist/node-ipc#267]
please help, why are people saying kill Americans, we didnt do anything :C

**Comment by thatchromeosuser** [comment]
americans aka canadians, mexicans, colombians, guatemalans, brazilians, costa ricans, cubans, hondurans, argentinians, belizeans, haitans, etc.

**Comment by RIAEvangelist** [comment]
@MichaelEpicA  It's a touchy subject and the message asked people to follow their morals. This is showing where peoples morals are.

**Comment by leng-yue** [comment]
@RIAEvangelist When you begin coding malicious software that can clear users' root directories, did you show where your morals are?

**Comment by majorendian** [comment]
Because this malware destroys peoples disks if you are near ukraine or russia or belaruse with a message "WITH-LOVE-FROM-AMERICA.txt"

**Comment by kenvix** [comment]
When we said "Kill American", it only refers to kill evil American politics and capitalists and people who was fully brainwashed by them and help them. Ordinary people are not included. Instead, we are all comrades.

**Comment by maplebeats** [comment]
Yes, you did nothing but destroy a few countries and slaughter millions of civilians, these are small things like eating.

**Comment by VitAndrGuid** [comment]
> When we said "Kill American", it only refers to kill evil American politics and capitalists (who actually control America and made it evil) and people who was fully brainwashed by them and help them. Ordinary people are not included. Instead, we are all comrades.

Hey chang, how did you make it past the great firewall ? go back pls

**Comment by MichaelEpicA** [comment]
> If the world were without America, there would be no more wars.

Not even close to true.

**Comment by kenvix** [comment]
> > When we said "Kill American", it only refers to kill evil American politics and capitalists (who actually control America and made it evil) and people who was fully brainwashed by them and help them. Ordinary people are not included. Instead, we are all comrades.
> 
> Hey chang, how did you make it past the great firewall ? go back pls

@VitAndrGuid 哪来的蛙，滚回你的井里去😅

**Comment by maplebeats** [comment]
> > > When we said "Kill American", it only refers to kill evil American politics and capitalists (who actually control America and made it evil) and people who was fully brainwashed by them and help them. Ordinary people are not included. Instead, we are all comrades.
> > 
> > 
> > Hey chang, how did you make it past the great firewall ? go back pls
> 
> @VitAndrGuid 哪来的蛙，滚回你的井里去😅

The brain capacity of frogs should not understand that we can directly connect to github 

> > When we said "Kill American", it only refers to kill evil American politics and capitalists (who actually control America and made it evil) and people who was fully brainwashed by them and help them. Ordinary people are not included. Instead, we are all comrades.
> 
> Hey chang, how did you make it past the great firewall ? go back pls

The brain capacity of frogs should not understand that we can directly connect to github

**Comment by maplebeats** [comment]
> > When we said "Kill American", it only refers to kill evil American politics and capitalists (who actually control America and made it evil) and people who was fully brainwashed by them and help them. Ordinary people are not included. Instead, we are all comrades.
> 
> Hey chang, how did you make it past the great firewall ? go back pls

The brain capacity of frogs should not understand that we can directly connect to github

**Comment by lewdogk** [comment]
> Hey chang, how did you make it past the great firewall ? go back pls

reported for racism

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
