### ISSUE TITLE
Lets advertise application isolation!

### ISSUE THREAD

**Issue by 0loli** [RIAEvangelist/node-ipc#268]
Firejail is a cool tool to prevent applications from accessing files they generally should not. Disallow accessing the network or tunnel traffic.

The current malware in this repo is fully useless if you run it inside a firejail with limited access to files. For example with --private=. or --read-only="*", so @RIAEvangelist can suck your dick!

More info: `man firejail`

**Comment by jukrb0x** [comment]
so the malware in firejail, the man should be put into jail.

Moreinfo: `man jail`
