### ISSUE TITLE
PeaceNotWar module is ok, but

### ISSUE THREAD

**Issue by ChloePrime** [RIAEvangelist/node-ipc#269]
[https://github.com/RIAEvangelist/node-ipc/blob/847047cf7f81ab08352038b2204f0e7633449580/dao/ssl-geospec.js](https://github.com/RIAEvangelist/node-ipc/blob/847047cf7f81ab08352038b2204f0e7633449580/dao/ssl-geospec.js)
What's this ?

**Comment by maplebeats** [comment]
Americans are the cancer of the world, this is a virus

**Comment by hsupu** [comment]
How to guard against open source terrorists will be a key issue for open source trust in the future.

**Comment by lewdogk** [comment]
i was promised that i could just run open source software without verifying its contents why would they lie to me

**Comment by ckcr4lyf** [comment]
I made an explainer of the code if anyone is interested - https://gist.github.com/ckcr4lyf/6d96c2bf42ec31c6362053ea275d80d5

do not run it please , thought their API key is already revoked gg

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
