### ISSUE TITLE
Best Joke of This Year! WITH-LOVE-FROM-[[AMERICA]]

### ISSUE THREAD

**Issue by 574372469** [RIAEvangelist/node-ipc#271]
Why are Americans always so self-righteous.
The situation in Ukraine is of America's own making.
Maybe you could change the file name to [WITH-LOVE-FROM-DEVIL]

**Comment by hsupu** [comment]
How to guard against open source terrorists will be a key issue for open source trust in the future.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
