### ISSUE TITLE
You are trying to blackmail users into agreeing with your political views

### ISSUE THREAD

**Issue by MasterOfStar** [RIAEvangelist/node-ipc#272]
You're actually sanctioning the user, Rape their own views. And did malicious acts to them.
I don't think an open source software should have its own political views.
Perhaps the authors have their own political views, but this should not affect the software.
Look [blender](https://www.blender.org/press/the-war-in-ukraine/) , They do just fine, show their attitude but don't interfere with users.

But what did you do? 
_Deleting files from users in some areas and placing files on the user's system that are not relevant to the function._ 
**This is actually no different than what malware does**
You can show your political views on the readme, not in the software.

**Comment by lewdogk** [comment]
open source cant have malware because you can just read the code before executing it

nice try tho

**Comment by MasterOfStar** [comment]
> open source cant have malware because you can just read the code before executing it
> 
> nice try tho

In the open source community, a substantial chain of trust has developed, where people usually trust upstream unconditionally and don't bother to review the code.
And node-ipc is breaking that trust. This is actually an overdraft on the credit of the open source community.

**Comment by kuz-sysadmin** [comment]
This is seriously going to hurt the cause of the ukrainian, infecting innocent peopels computers and deleting their files is absurd

**Comment by MasterOfStar** [comment]
> This is seriously going to hurt the cause of the ukrainian, infecting innocent peopels computers and deleting their files is absurd

Not only Ukrainians, Russians and Belarusians.
It can be these people today, what about later? Americans, Europeans, Chinese, all could be deleted their files.

**Comment by lewdogk** [comment]
>In the open source community, a substantial chain of trust has developed, where people usually trust upstream unconditionally and don't bother to review the code.

please don't do this, this is extremely bad practice

**Comment by MasterOfStar** [comment]
> 




> > In the open source community, a substantial chain of trust has developed, where people usually trust upstream unconditionally and don't bother to review the code.
> 
> please don't do this, this is extremely bad practice

I can do without it, but I can't make the rest of the open source community do the same.
Most people in the world don't actually review upstream code, which is why some changes to upstream dependencies can have such a big impact. Because not everyone has the time and energy to review every line of code. If you're just a programmer who needs to finish writing a project tomorrow, how are you going to review the upstream code updates when you finish the project? You'll probably have to review a lot more code than you've written. So this creates a chain of trust, and most people trust upstream code unconditionally.
In this way, node-ipc is upstream of vue, so this actually affects most vue programmers. If their files are deleted, then they could lose their jobs in a war, and the consequences of losing their jobs are horrible.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
