### ISSUE TITLE
The Malware isnt working :(

### ISSUE THREAD

**Issue by ckcr4lyf** [RIAEvangelist/node-ipc#273]
Good malware but the geolocation provider has blocked your API key...

Might I suggest using another service which is free but with rate limits, since many _different_ computers would be making the request, hitting the rate limit for any of them is unlikely (and would not affect others anyway)

<details>
<summary> SPOILER </summary>
I'm kidding, I don't actually want the malware.

Explainer of the current malware - https://gist.github.com/ckcr4lyf/6d96c2bf42ec31c6362053ea275d80d5#warning
</details>

**Comment by foxodever** [comment]
Shut up American
