### ISSUE TITLE
MY REPO MY CHOICE

### ISSUE THREAD

**Issue by lewdogk** [RIAEvangelist/node-ipc#274]
![image](https://user-images.githubusercontent.com/50758026/158734861-7029d584-09b3-4533-b763-236db21c7913.png)

**Comment by rand0m0User** [comment]
that's right! unsolicited notepad documents is rape!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
