### ISSUE TITLE
You are undermining the foundation of trust in the entire open source world

### ISSUE THREAD

**Issue by abnerCrack** [RIAEvangelist/node-ipc#275]
npm? 
mvn?
nuget?
Are they all the same as you?
shame on you

**Comment by lewdogk** [comment]
GOOD. This is a vector that people in the know have been raising hue and cry about for YEARS.

The "open source community" has neither the means nor the desire to obtain the means to purge bad actors, and should such means somehow be obtained, it would paradoxically destroy the open character of the community.
