### ISSUE TITLE
Shame on you

### ISSUE THREAD

**Issue by kuz-sysadmin** [RIAEvangelist/node-ipc#276]
Absolute disgrace, you should be ashamed of yourself for betraying the trust of the community

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
