### ISSUE TITLE
ALL OF YOUR REPO SHOULD BE DELETED

### ISSUE THREAD

**Issue by aimerneige** [RIAEvangelist/node-ipc#279]
NO ONE WILL TRUST ANY OPEN SOURCE PROJECT FROM A GUY NAMED @RIAEvangelist

**Comment by shamazmazum** [comment]
All your repo are belong to us :)

**Comment by rand0m0User** [comment]
i wonder what kind of other antics he has been up to in all the private repositories... especially if they are going to be this unprofessional

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
