### ISSUE TITLE
Programming is outside of politics 

### ISSUE THREAD

**Issue by foxodever** [RIAEvangelist/node-ipc#284]
Are people to blame for the war? You're seriously removing the system for revular users. You are worse than ransomware hackers

**Comment by foxodever** [comment]
I don't care that all the library does is add files, you started a war, but an online war.

**Comment by foxodever** [comment]
Programming outside of politics. Why should ordinary coders suffer from the actions of their President?

**Comment by foxodever** [comment]
For example, my friend, he is 14 years old, he just writes codes and lives his life. How is he to blame for the war!?

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
