### ISSUE TITLE
LOOK AT HIM HE IS DELETING ISSUES

### ISSUE THREAD

**Issue by skaneprime** [RIAEvangelist/node-ipc#288]
Shame on you. You are a disgrace to people

**Comment by ChloePrime** [comment]
😅

**Comment by Maximal98** [comment]
LMAO

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
