### ISSUE TITLE
Project reported to github

### ISSUE THREAD

**Issue by MVDW-Java** [RIAEvangelist/node-ipc#290]
take the L
![image](https://user-images.githubusercontent.com/22998325/158760817-b1d797ac-c810-4110-9701-04a3912a35d5.png)

**Comment by Infidigious** [comment]
He seems to be spending his day today closing issues to hide what he is doing, what a sad life

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
