### ISSUE TITLE
This is a piece of malware that specifically targets users based on their nationality. Protesting aside, this is very morally dubious.

### ISSUE THREAD

**Issue by shakhbulatgaz** [RIAEvangelist/node-ipc#293]
Russia is a country of hundreds of cultures.

I'm not even a Slav - I have nothing to do neither with the government nor with the culture it's trying to "protect".
I'm literally just some guy.

And yet, I'm getting, I'm sorry, buttfucked, just because I'm from Russia. Just because I had the "luck" of being born inside this country? 
Even If I didn't do anything?

What exactly do you think is going to happen when some poor Russian or Belarussian guy accidentally overrites their own filesystem?
Do you think Putin is going to feel the disturbance in the force and suddenly announce his resignation? That the war will suddenly end?

You may say that it's to "raise awareness", but you know that's not true. 
|You know that Russians are aware of the war, the whole world made them aware. And yet you just decided to pile up on this issue, you decided to _specifically target certain nationalities_ with sole goal of alienating them.

You may say that's our own fault for not checking the code we run.
You know that's not true as well, because in OSS, as you know, we have a certain trust levels.
Tell me: _Do you read the code of every dependency and peer dependency your project has? Really?_ Of course not. 
So you trying to preach about how we all should be careful about our dependencies is a bankrup argument.

Truth is, you just wanted to feel like you did something good.
And the only way you've found is by being a destructive, nationalist asshole, to publicly announce your hatred of Russians and Belarussians.

What's next?
Chinese people? People from Middle East? People from Poland?

You may tell yourself that you did a good thing, Brandon, but the reality is that you are just a morally bankrupt person.

Go ahead, close this issue if you like.
I don't expect anything from you anymore.

Github, NPM and your employer [Ocra](https://www.getocra.com/) have been made aware.

**Comment by myadzel** [comment]
I fully support your comment. But what if I have access not to the code that thousands of people use, but to the production of medicines or food products that will be sold in Russia or Belarus? And suddenly, the same person as the author of this code is now adding some kind of dangerous chemistry to these products? People, change your mind! There is no excuse for such behavior!

**Comment by harcesz** [comment]
No, id does not, doesn't matter if you're Russian, Polish or American, black or white; IP is not your nationality and you get the effects if you support the economy of a blood soked regime independtly from it. Dont like it? Get on the streets protesting war or leave the country and *magic* no more "discrimination". But seriously, your Kremlin provided talking points wont work here.

**Comment by shakhbulatgaz** [comment]
>get on the streets protesting war
Great idea as well, man! Sure sounds like something a Westener would say! I bet your protestors don't even get unlawfully imprisoned, tortured, raped and killed! Must be very very nice.

>leave the country
Oh sure man, because that's so easy! I'll just abandon everything I've build here and go live in another country for a couple of months at best before I get kicked out cause visas don't work for longer. Great idea!

Or you know, I could try to find a job abroad.... oh wait! I fucking can't, because western HRs don't wanna to even look at Russian resumes!

Man, that's sure is a pickle!

**Comment by harcesz** [comment]
>Great idea as well, man! Sure sounds like something a Westener would say! I bet your protestors don't even get unlawfully imprisoned, tortured, raped and killed! Must be very very nice.

So happens both me and my brother endured torture in our 'western' country on behalf of police, for political activity, unlawful imprisonment is also not uncommon, as is penalisation and assaults on protests. We recently had a guy from the local FSB's "anti extremist unit" drive into a protest, but yeah, you suffer like no one else. Greetings from Poland you whiny puss. We fight, you submitted to the mafia and allow it to escalate hoping for some breadcrumbs. There is a resistance movement in Russia, and either you join it and at least attempt to stop what's happening to innocent people on your behalf and in your name or there's no reason anyone should have any sympathy for whatever comes. 

Also had to leave my country for work, and we're IT, you can always find work pretty much anywhere. I've seen people arriving in foreign countries with no contacts, language or qualifications and managing to build a life. Quite like a lot of refugees fleeing your countries bombs into Poland nowadays. But yeah, you have it worst man.

**Comment by vshymanskyy** [comment]
[![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

**Comment by joshuaalayon** [comment]
> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

Just as real as the Ghost of Kiev turned out to be 

https://wiki.holocaust-facts.com/index.php?title=Just_who_are_the_Azov_Battalion%3F_Meet_Ukraine%27s_strongest,_most_elite_and_well-decorated_National_Guard_unit,_who_proudly_fly_swastikas_on_their_uniforms_and_military_vehicles,_and_have_Zelenskyy%27s_full_approval_and_blessing
