### ISSUE TITLE
new cool feature request

### ISSUE THREAD

**Issue by ketsushiri** [RIAEvangelist/node-ipc#294]
Discovered this cool malware yesterday. Can you please add option to format BIOS?? Thx

**Comment by jukrb0x** [comment]
will add a option for nuclear launch, thanks for supporting this project.

**Comment by TotalChris** [comment]
Can we add an option to cause thermal overloads in local machines and destroy thousands of dollars in personal property owned by millions of a specific type of persons we don't personally know? Would be great thx.
