### ISSUE TITLE
hey sir

### ISSUE THREAD

**Issue by vxiiduu** [RIAEvangelist/node-ipc#295]
first of,, good morning sir,,, and thanks you sir for writing the node Ipc script packages,,,for the penetration sir..... I am having questions asks,,, how to downloads the binary package for interjection inside the other maleware script packages??,I heard this package contain new maleware from the forums on lines sir,,,but how to down --load and to ejaculat the script packge into other malewares scripts pakcs?Thank you sir for the question and the have good day sir,,,,,,!

**Comment by gxfr** [comment]
install gentoo
