### ISSUE TITLE
You have been reported

### ISSUE THREAD

**Issue by icmx** [RIAEvangelist/node-ipc#296]
Hello @RIAEvangelist! Just came here to notice that I've reported your repository and you as a malware creator because of this: https://github.com/RIAEvangelist/node-ipc/issues/233 [(webarchive)](http://web.archive.org/web/20220316015553/https://github.com/RIAEvangelist/node-ipc/issues/233).

![image](https://user-images.githubusercontent.com/32983315/158764925-ba6c9a26-ed43-4816-8818-737d03a9668e.png)

Please enjoy.

---

**Update:** your employer at [info@getocra.com](https://www.getocra.com/old-home) and the CEO (https://www.linkedin.com/in/ethanglass/) are also notified of this incident. Have a nice day!

**Comment by SCOTT0852** [comment]
seconded.
![image](https://user-images.githubusercontent.com/33875157/158766636-d4c56cd0-d269-4a76-9184-f2489cd88771.png)

**Comment by shakhbulatgaz** [comment]
You can also e-mail his employer at [info@getocra.com](https://www.getocra.com/old-home)

**Comment by icmx** [comment]
[@shakhbulatgaz](https://github.com/shakhbulatgaz) will do, thank you

**Comment by dreamscached** [comment]
Good idea! Seconded that as well.
![obrazek](https://user-images.githubusercontent.com/74068927/158767849-897d236a-801e-4a30-8be4-efaf6be5083b.png)

**Comment by jukrb0x** [comment]
![image](https://user-images.githubusercontent.com/15688641/158771583-544d504d-802f-4e16-8ea7-7b569131898d.png)

the zero patient has deleted who uncovered the whole thing. Ashamed on you! @RIAEvangelist !

**Comment by shakhbulatgaz** [comment]
It's still available in the web archive.

**Comment by akvilibrium** [comment]
Same. Reported him too. Block this malware spreader. It's a shame of all open-source community and breaks its concept at all.

**Comment by nhantr** [comment]
I just did it. very shame for him

**Comment by nhantr** [comment]
> It's still available in the web archive.

github issue stored the history, that's good point. but what if the author remove this issue?

**Comment by jukrb0x** [comment]
> > It's still available in the web archive.
> 
> github issue stored the history, that's good point. but what if the author remove this issue?

Seems the issue cannot be removed, can only be closed, however the event has been elevated to a serious problem to the whole open source and nodejs community. This guy and malware have been reported to some facilities.

**Comment by racofer** [comment]
I have reported him as well. I use Unity and Unity Hub was infected by this malware in its latest version.
