### ISSUE TITLE
Russian malware modules: 0, Nazi lover malware module: yet another

### ISSUE THREAD

**Issue by rowaasr13** [RIAEvangelist/node-ipc#298]
Makes you think.
Also enjoy you report, Nazi collaborator.

Your beloved Nazi bombed Donetsk on 14th March with Tochka-U (https://en.wikipedia.org/wiki/OTR-21_Tochka) in the middle of the day, explicitly targeting center of the city in the middle of business day, with reports day before of several Telegram channels injecting fake calls to meetings in that location . 20+ dead, tons of injured, including kids.

Look with your shitty nazi-loving eyes at those:
https://t.me/boris_rozhin/32250
https://t.me/boris_rozhin/32255
https://t.me/boris_rozhin/32256
https://t.me/boris_rozhin/32265
https://t.me/RtrDonetsk/3401
https://t.me/boris_rozhin/32296

Did your rotten heart bleed for them? No, your piece of shit heart only bleeds for those you feel close to you - Ukro-Nazi military.

Your Western insane toilet newspapers gone as far as use several photos from this terror act as illustration for Russian strikes against military bases:
https://twitter.com/ABC/status/1503495384970272769

Rot in hell, scum.

**Comment by vryazanov** [comment]
Cool story bro, turn off the TV

**Comment by germanmetall** [comment]
> 

got burned, little putinjugend?)
By the way, Donetsk 14' was bombed by russians. Anyway...

**Comment by akvilibrium** [comment]
> Cool story bro, turn off the TV

You should say this yourself first

**Comment by pa3py6aka** [comment]
> By the way, Donetsk 14' was bombed by russians. Anyway...

Ask the residents of Donetsk about it, you will be very surprised. And watch less TV

**Comment by rowaasr13** [comment]
> By the way, Donetsk 14' was bombed by russians.

I didn't expect any other answer from nazionalist scum that shelled it for 8 years and invented and distributed sick "they hit their own air conditioner themselves" "joke" back after Lugansk airstrike (https://edition.cnn.com/2014/06/03/world/europe/ukraine-luhansk-building-attack/index.html).

**Comment by AKopytenko** [comment]
rowaasr13, don't worry so much about all this. You just need to understand that there are ordinary people, programmers, engineers who just work at their job and are not interested in politics. And there are places, like RIAEvangelist, that promote enmity between peoples and try to entice ordinary people and other programmers into their political games. Just don't use what RIAEvangelist is developing and tell others about it. Yes, this creates certain difficulties in the work, but we will not be like the author and will try to work calmly on. 

Good luck to all and labor success :)

**Comment by harcesz** [comment]
Dear Russians, can you truly believe Ukraine would bomb Donbas if at all than specifically during the massive build-up of your countries troops and propaganda all around and against it? Just so very convenient for Putin and utterly stupid and pointless for them, wouldn't it be? 

In this times ignorance is a choice. You choose to support a regime that currently levels whole cities in Ukraine and whine when the "rotten west" takes away it's toys from you. I find it hard to imagine something more laughable, and your cries here are already becoming a meme. No go wipe your eyes and nose with some rubbles and get back to slaving for a kleptocratic regime.

**Comment by pa3py6aka** [comment]
> Dear Russians, can you truly believe Ukraine would bomb Donbas if at all than specifically during the massive build-up of your countries troops and propaganda all around and against it? Just so very convenient for Putin and utterly stupid and pointless for them, wouldn't it be?

Dear dick, I beg you to talk about this not with the TV, but with REAL RESIDENTS of Donbass.
I also advise you to ask them why they are now participating in the war on the side of the Russians? They are subject to Russian propaganda and for 8 years they have not understood that they were bombed by Russians, and not by Ukrainians?

**Comment by vryazanov** [comment]
> > Dear Russians, can you truly believe Ukraine would bomb Donbas if at all than specifically during the massive build-up of your countries troops and propaganda all around and against it? Just so very convenient for Putin and utterly stupid and pointless for them, wouldn't it be?
> 
> Dear dick, I beg you to talk about this not with the TV, but with REAL RESIDENTS of Donbass. I also advise you to ask them why they are now participating in the war on the side of the Russians? They are subject to Russian propaganda and for 8 years they have not understood that they were bombed by Russians, and not by Ukrainians?

by Donbass you mean the territory controlled by L/DNR only? Just want to make sure who REAL RESIDENT is.

**Comment by pa3py6aka** [comment]
> by Donbass you mean the territory controlled by L/DNR only? Just want to make sure who REAL RESIDENT is.

We are talking here about the bombing of Donetsk in 2014 and subsequent years. So I mean the residents of Donetsk.

And what do you mean by the term "REAL RESIDENT"? Are the residents of the L/DNR not real?

**Comment by vryazanov** [comment]
> And what do you mean by the term "REAL RESIDENT"? Are the residents of the L/DNR not real?
 
You used this term first, so I wanted to clarify who you are talking about.  Ok, now It's clear, you meant the residents of Donetsk, not of the whole Donbas. That explains a lot.

**Comment by vshymanskyy** [comment]
[![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

**Comment by pa3py6aka** [comment]
> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

That's all the ukrainian guy can say about the killing of civilians in Donetsk. Hypocritical dumb creature

**Comment by joshuaalayon** [comment]
> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)
> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

Just as real as the Ghost of Kiev turned out to be 

https://wiki.holocaust-facts.com/index.php?title=Just_who_are_the_Azov_Battalion%3F_Meet_Ukraine%27s_strongest,_most_elite_and_well-decorated_National_Guard_unit,_who_proudly_fly_swastikas_on_their_uniforms_and_military_vehicles,_and_have_Zelenskyy%27s_full_approval_and_blessing
