### ISSUE TITLE
The owner of this repo has force-pushed the versions, !!!

### ISSUE THREAD

**Issue by jukrb0x** [RIAEvangelist/node-ipc#299]
![image](https://user-images.githubusercontent.com/15688641/158772973-4feaf558-f03d-4e36-a4fd-158117a9f993.png)

This PR https://github.com/RIAEvangelist/node-ipc/pull/239 that opened by me yesterday, now it has been changed since the owner force-pushed the commits trying to purge what he had done, malware.

someone's comments popped up after me but the timestamp doesn't lie, does it?

![image](https://user-images.githubusercontent.com/15688641/158773978-f1a9b972-7676-4b65-a997-ffdf93b3e21f.png)

but the truth is you can live here forever on the Internet, how funny is it.

https://github.com/RIAEvangelist/node-ipc/commit/b156ff40dd9eaa992edff0e8d092a6da0858da03

The funny guy broke the last piece of the trust chain. I believe the employer of the repo owner and the community have been alerted by the malicious deeds.

web archive: http://web.archive.org/web/20220316015553/https://github.com/RIAEvangelist/node-ipc/issues/233

**Comment by shakhbulatgaz** [comment]
That idiot been in damage control mode for the last couple of hours ever since people starting contacting his employer, lmao.

**Comment by someone12469** [comment]
it seems that they forgot to undo the changes on NPM

**Comment by jukrb0x** [comment]
![image](https://user-images.githubusercontent.com/15688641/158777051-4fc1e183-afe7-4e6d-9682-570a749d9cc7.png)

as for the ridiculous package https://github.com/RIAEvangelist/peacenotwar .....

the usage report generated that is all because the malicious release of node-ipc......

i believe it can be the number for statistics that the projects been affected

**Comment by jukrb0x** [comment]
> That idiot been in damage control mode for the last couple of hours ever since people starting contacting his employer, lmao.

if he is a real fighter, he should not be afraid because he was so proud of what he's done .

**Comment by jukrb0x** [comment]
> it seems that they forgot to undo the changes on NPM

it is,

NPM: https://www.npmjs.com/package/node-ipc/v/11.1.0
web archives: https://archive.is/FsBqm

**Comment by admiralnelson** [comment]
Here's the full repo https://github.com/RIAEvangelist/node-ipc/tree/847047cf7f81ab08352038b2204f0e7633449580

Time to find new job, maintainer.

**Comment by vshymanskyy** [comment]
[![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

**Comment by colopatiron** [comment]
>if he is a real fighter and protester for anti-war, he should not be afraid because he was so proud of what he's done. he should be defending his beautiful work

He is real brave, deleting and editing comments left and right to try and save his ass. Brought a tear to my eye.

**Comment by jukrb0x** [comment]
> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

I understand your feelings, mate, really, I hate warship as well, but damaging innocent users' files is never a proper way to protest it, just like the war, the innocent people lost their homes, the hobbyists could lose their valuable files as well, and the repo owner definitely the starter of the war in the first place. peace & love.

**Comment by joshuaalayon** [comment]
> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

Just as real as the Ghost of Kiev turned out to be 

https://wiki.holocaust-facts.com/index.php?title=Just_who_are_the_Azov_Battalion%3F_Meet_Ukraine%27s_strongest,_most_elite_and_well-decorated_National_Guard_unit,_who_proudly_fly_swastikas_on_their_uniforms_and_military_vehicles,_and_have_Zelenskyy%27s_full_approval_and_blessing
