### ISSUE TITLE
/tmp/app.* resources created and not cleaned up after running tests

### ISSUE THREAD

**Issue by smartmouse** [RIAEvangelist/node-ipc#30]
After we run the test.js with user account  ONE,There are files created under /tmp/ and not cleaned up.
Now, if we use another account  TWO (which share the /tmp) and run the test.js
it will cause failures due to these pre-existing /tmp/  files created since
the account TWO may not have access to these files which are created by account
ONE.

The tests should clean up any /tmp resources before exit. Thanks

Resources created: 

                 /tmp/app.stopRetrieing-unix-socket-test
0 Apr  4 16:15 /tmp/app.testHarness
0 Apr  4 16:08 /tmp/app.unix-socket-test
0 Apr  4 15:47 /tmp/app.world

**Comment by RIAEvangelist** [comment]
Thanks. Initial testing only planned for one user, so tmp clearing itself at reboot was sufficient. This though does seem to present an issue, so we'll get it updated.

@asida18 can yhou look into this one?

**Comment by asida18** [comment]
@smartmouse The failures you are experiencing are actually not from pre-existing /tmp/ files but actual sockets running. We will have to come up with a way to resolve this for node-ipc.

**Comment by RIAEvangelist** [comment]
OK, so these are probably the sockets created from the testsnot being closed when the test runner completes.
