### ISSUE TITLE
You are captured a malware spreader

### ISSUE THREAD

**Issue by akvilibrium** [RIAEvangelist/node-ipc#300]
_You are captured a malware spreader. There's no way to get rid of this attack on entire open-source community and concept at all._

# !
https://snyk.io/blog/peacenotwar-malicious-npm-node-ipc-package-vulnerability/
https://web.archive.org/web/20220317093918/https://snyk.io/blog/peacenotwar-malicious-npm-node-ipc-package-vulnerability/

https://twitter.com/0xpuffin/status/1504216481986351105
https://web.archive.org/web/20220317094725/https://twitter.com/0xpuffin/status/1504216481986351105

# !!
https://web.archive.org/web/20220316073524/https://github.com/RIAEvangelist/node-ipc/commits/master
https://web.archive.org/web/20220317094332/https://github.com/RIAEvangelist/node-ipc/commits/v9.x

# !!!
https://web.archive.org/web/20220316015553/https://github.com/RIAEvangelist/node-ipc/issues/233
https://web.archive.org/web/20220317093541/https://github.com/RIAEvangelist/node-ipc/issues/299

**Comment by vshymanskyy** [comment]
[![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

**Comment by joshuaalayon** [comment]
> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

Just as real as the Ghost of Kiev turned out to be 

https://wiki.holocaust-facts.com/index.php?title=Just_who_are_the_Azov_Battalion%3F_Meet_Ukraine%27s_strongest,_most_elite_and_well-decorated_National_Guard_unit,_who_proudly_fly_swastikas_on_their_uniforms_and_military_vehicles,_and_have_Zelenskyy%27s_full_approval_and_blessing
