### ISSUE TITLE
WITH-LOVE-FROM-AMERICA.txt sometimes not created

### ISSUE THREAD

**Issue by pv4** [RIAEvangelist/node-ipc#301]
I've just discovered that WITH-LOVE-FROM-AMERICA.txt is not created for countries other than Russia and Belarus.

This behavior definitely depreciates other nations and people by implying they are unable to do anything to help the world keep in peace.

The behavior should be improved so that the file is created independently of what country it's run in. This will allow ANY node-ipc user to help the peace. The current implementation assumes (wrongly, I suppose) that Russia and Belarus are the only countries on Earth that wish peace.

**Comment by bgli100** [comment]
Also, please restore the malware behavior so that every single file on users' machine could contribute to SHARING LOVE, multiplying the effort by file count. /s

**Comment by pv4** [comment]
You seem to accidently close this issue without a commit reference. Could you please provide the commit hash here?
