### ISSUE TITLE
Fuck you

### ISSUE THREAD

**Issue by lx30011** [RIAEvangelist/node-ipc#302]

**Comment by vshymanskyy** [comment]
[![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

**Comment by mgord9518** [comment]
Concise, yet sums up the situation quite well

**Comment by joshuaalayon** [comment]
> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

Just as real as the Ghost of Kiev turned out to be.
