### ISSUE TITLE
All you are achieving with this malware shit is just spreading hatred between nations and people and destroying the OSS

### ISSUE THREAD

**Issue by MaksimMedvedev** [RIAEvangelist/node-ipc#303]

**Comment by vparitskiy** [comment]
What you people do are spreading death. So maybe start with that if you don't want you nation to be hated.

**Comment by vshymanskyy** [comment]
[![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

**Comment by akvilibrium** [comment]
.

**Comment by akvilibrium** [comment]
Should I say all developers from UA / USA are *\_very\_very\_bad\_people\_*?
No? Of course no.
But it's exactly what does this  *\_very\_very\_bad\_* malware against russians and belarusians. 
It's real N\_az\_ism. And all you will achieve with this - hate and contempt.

**Comment by joshuaalayon** [comment]
> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

Just as real as the Ghost of Kiev used to be.

OP, guess what? People who sympathize with Nazis like Azov don't care if they breed hatred in the world. They are bitter, small people.
https://wiki.holocaust-facts.com/index.php?title=Just_who_are_the_Azov_Battalion%3F_Meet_Ukraine%27s_strongest,_most_elite_and_well-decorated_National_Guard_unit,_who_proudly_fly_swastikas_on_their_uniforms_and_military_vehicles,_and_have_Zelenskyy%27s_full_approval_and_blessing
