### ISSUE TITLE
Brief rundown on all software which uses node-ipc https://github.com/zlw9991/node-ipc-dependencies-list

### ISSUE THREAD

**Issue by zlw9991** [RIAEvangelist/node-ipc#305]
Could you make a list of all the programs that use node-ipc?
It would be even better if you could make a list of major programs that use NPM, to help the mitigation process.
Thanks.

Done: https://github.com/zlw9991/node-ipc-dependencies-list

**Comment by Actticus** [comment]
VueCLI

**Comment by jacknkandy** [comment]
Unity 3.1.0
https://forum.unity.com/threads/malware-in-unity-hub-3-1-0-with-love-from-america-txt.1253856/
https://unity3d.com/hub/whats-new

**Comment by shakhbulatgaz** [comment]
> Unity 3.1.0

Holy shit

**Comment by dark-swordsman** [comment]
@jacknkandy they thankfully patched it last night, but who knows what other software uses this.

![image](https://user-images.githubusercontent.com/7909209/158802939-1f3c45b2-04a6-4c4d-a2f0-52535fb70536.png)

**Comment by jacknkandy** [comment]
> > Unity 3.1.0
> 
> Holy shit

yep https://github.com/RIAEvangelist/node-ipc/issues/233#issuecomment-1069734526

**Comment by zlw9991** [comment]
Aside from obvious mitigations involving NPM & Node-Ipc, another great (but off topic) question would be how to manage software in a politically charged world in order to avoid situations like this, beyond obvious answers like auditing these updates & waiting for a stable consensus to emerge. Like the ISS or RISC-V (the best examples I can currently think of)

**Comment by vshymanskyy** [comment]
[![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

**Comment by Uzlopak** [comment]
https://www.npmjs.com/package/node-ipc?activeTab=dependents

**Comment by zlw9991** [comment]
Done: https://github.com/zlw9991/node-ipc-dependencies-list

**Comment by wolfsaviorzx** [comment]
This should make everyone be very cautious of this overly dependency based software web we have created. It's open my eyes, what if a Russian based project decided to do this?
