### ISSUE TITLE
sneed

### ISSUE THREAD

**Issue by noneistaken** [RIAEvangelist/node-ipc#306]
formerly chuck
![1647007750939](https://user-images.githubusercontent.com/90960821/158806549-2dc032cf-7587-485b-b20a-9f2aee401855.jpg)

**Comment by vshymanskyy** [comment]
[![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

**Comment by animegrafmays** [comment]
based

**Comment by ddvarpdd** [comment]
> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

The whole crew surrendered lole

**Comment by joshuaalayon** [comment]
> [![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

Just as real as the Ghost of Kiev turned out to be 

Formerly Zelenskyy's
