### ISSUE TITLE
Put me in the screencap

### ISSUE THREAD

**Issue by undulum** [RIAEvangelist/node-ipc#312]
(a)Whoever—
(7)with intent to extort from any person any money or other thing of value, transmits in interstate or foreign commerce any communication containing any—
(A)threat to cause damage to a protected computer;
(B)threat to obtain information from a protected computer without authorization or in excess of authorization or to impair the confidentiality of information obtained from a protected computer without authorization or by exceeding authorized access; or
(C)demand or request for money or other thing of value in relation to damage to a protected computer, where such damage was caused to facilitate the extortion;
shall be punished as provided in subsection (c) of this section.

**Comment by MissPasture** [comment]
Poasting in an epic bread

**Comment by undulum** [comment]
I hope that the FBI will catch him soon, friend, and he will be locked in the federal prison

**Comment by animeavi** [comment]
ogey
rrat

**Comment by AdamShpagin** [comment]
Metal Jannies Rising

**Comment by undulum** [comment]
Negatory, this section of the US code is specifically what he violated when he claimed that the code was unreachable and was only intended as a demonstration of how node-ipc might be patched to cause damage to certain protected computers. Those denials created a second violation, this time of the section quoted in the issue. Thank you for your inquiry and I trust this addresses it.

**Comment by M9C** [comment]
plebbitors are here hide the children

**Comment by Superbadmann** [comment]
It isnt a crime if your AMERICAN. This is WAR. 🇺🇦

**Comment by pete** [comment]
@MissPasture 

> Poasting in an epic bread

(·_·)

( ·_·)>⌐■-■

(⌐■_■)

**Comment by joshuaalayon** [comment]
> It isnt a crime if your AMERICAN. This is WAR. 🇺🇦

Those days are over, American bled out in the Middle East. Chickens coming home to roost

**Comment by markovicaleksandar1312** [comment]
Hi there, sorry for being late. Did I miss something?

**Comment by joshuaalayon** [comment]
btw op you and I have both already been screencapped repeatedly in the chans LOL so based and amazing effect on target my friend. Cheers 🥂 Z for victory

**Comment by zlw9991** [comment]
poa.sters, i kneel!
