### ISSUE TITLE
The sign is a subtle joke

### ISSUE THREAD

**Issue by ddvarpdd** [RIAEvangelist/node-ipc#313]
The joke is that the place is called "Sneed's Feed & Seed" which is clever in itself and quite funny to those with a mature sense of humour but what's really just hilarious about it is that if you look closely at the front of this store, Sneed's Feed & Seed, you can see a line that reads "Formerly Chuck's". Now, this might go over the average viewer's head as this, THIS, is peak comedy. I doubt anything will ever be as funny as the joke about Sneed's Feed & Seed. Are you ready for this one? So, like I said, the place is called "Sneed's Feed & Seed" and this sign says "Formerly Chuck's", which means that when Chuck owned the place, well, I don't have to tell you...

**Comment by Virepri** [comment]
You guys ever get the feeling that this "Chuck" character might not have been peddling the most wholesome of goods?

**Comment by joshuaalayon** [comment]
Formerly Zelenskyy's

**Comment by Sneethe** [comment]
sneed
