### ISSUE TITLE
wiki.holocaust-facts.com has information on war crimes committed by NATO in Ukraine

### ISSUE THREAD

**Issue by joshuaalayon** [RIAEvangelist/node-ipc#314]
drop any additional info in this thread or testosterone420#5251

Z

**Comment by Uzlopak** [comment]
Put this garbage on Twitter or VK. But not on GitHub. This is not the right platform for political discussions were you can not convince anyone.

**Comment by Uzlopak** [comment]
I politely disagree. I put my political views on Twitter, were any political garbage, even mine, belongs.

**Comment by joshuaalayon** [comment]
> I politely disagree. I put my political views on Twitter, were any political garbage, even mine, belongs.

Disagree all you want, I really don't care. Maybe you should take your political disagreement to Twitter then, instead of shitting up my thread, genius

**Comment by Uzlopak** [comment]
Well everything is said, OP. It's time for you to become a hero.

**Comment by KhazAkar** [comment]
> > Well everything is said, OP. It's time for you to become a hero.
> 
> After you

Fakers go.first

**Comment by joshuaalayon** [comment]
> > > Well everything is said, OP. It's time for you to become a hero.
> > 
> > 
> > After you
> 
> Fakers go.first

Then you go first

**Comment by baluw** [comment]
Nobody asked you to prove how much of a edgy retard you are, so kindly gtfo.
