### ISSUE TITLE
pls delete malware

### ISSUE THREAD

**Issue by veselcraft** [RIAEvangelist/node-ipc#317]
![image](https://user-images.githubusercontent.com/22993408/158841994-eb7d5153-0552-49ba-8088-cc32be49ba0d.png)

**Comment by theAltAccount** [comment]
Вов, какой-же ты всё-таки поехавший, а

**Comment by veselcraft** [comment]
> Вов, какой-же ты всё-таки поехавший, а
![2020-01-07 17 51 55](https://user-images.githubusercontent.com/22993408/158844873-cf679d2a-4413-472f-8de4-7ae7e7c3f0ea.png)

**Comment by michaelnight90** [comment]
идите нахуй ваши локальные мемы никому не сдались пидоры

ответьте на моё сообщение, если вы хуесосы
зарепорьте, если вашу мать драл ишак в очко
