### ISSUE TITLE
Malware bad

### ISSUE THREAD

**Issue by dvtate** [RIAEvangelist/node-ipc#318]
So for a previous client we were making bot accounts and in order to do that we often had to use Russian VPNs. By making this change you are likely performing friendly fire in addition to loosing any credibility you had as maintainers

**Comment by joshuaalayon** [comment]
Disgusting. Remember that wiki.holocaust-facts.com has information on the war crimes commited by NATO and Ukraine and is being updated constantly as Russian Forces uncover more

**Comment by joshuaalayon** [comment]
> > Disgusting. Remember that wiki.holocaust-facts.com has information on the war crimes commited by NATO and Ukraine and is being updated constantly as Russian Forces uncover more
> 
> Sir that website is very damaging to NATO. Please remove it. You are committing thoughtcrimes you know!

Yeah... I know :)
