### ISSUE TITLE
Windows 7 TCP issue without internet connection

### ISSUE THREAD

**Issue by iamdriz** [RIAEvangelist/node-ipc#32]
I'm using the TCP connection for two Node applications to talk to each other that run on a local computer that has no connection to the internet.

**However I've found that unless the computer is connected to the internet, then the communications don't get sent!**

Is it possible to communicate without internet access?? I'm using the defaults so it should just be running on localhost and not relying on any internet access...

Running on Windows 7

**Comment by iamdriz** [comment]
Noticed that in the console I see the error:

`Failed to read DnsConfig`

My config is as follows:

SERVER

~~~
var nodeIpc = require('node-ipc');

nodeIpc.config.id   = 'server';
nodeIpc.config.retry = 1500;
nodeIpc.config.silent = true;

nodeIpc.serveNet(
    'localhost',
    8003,
    function(){
    }
);

nodeIpc.server.start();
~~~

CLIENT

~~~
var nodeIpc = require('node-ipc');

nodeIpc.config.id   = 'client';
nodeIpc.config.retry = 1500;
nodeIpc.config.silent = true;

nodeIpc.connectToNet(
    'server',
    'localhost',
    8003,
    function(){
    }
);
~~~

**Comment by RIAEvangelist** [comment]
That is strange, I'll have to take a look into this. Localhost should work without internet connectivity.

Do you have network drivers installed? If there are no network drivers or if you have disabled them, it is possible that no TCP would work as it requires the network stack be atleast installed and running (which is default on most machines) This is how local host etc. works

**Comment by RIAEvangelist** [comment]
That console error is pretty valuable :

` Failed to read DnsConfig ` I'll see what I can find on it.

**Comment by RIAEvangelist** [comment]
@iamdriz can you verify that you can start a server on localhost while you are getting the error you reported?

you can try anything basic like one of the examples from [node-http-server](https://www.npmjs.com/package/node-http-server)

If not, there may be an issue with your network configuration. If so, then we need to dig deeper.

Thanks.

**Comment by iamdriz** [comment]
I have IIS running in my machine for other local development projects so localhost works fine regardless of Internet connection. But if I switch my wireless off then the TCP fails but the IIS sites still work fine.

**Comment by wplittle** [comment]
@iamdriz just out of curiosity, what happens if you change "localhost" in
your client and server code to "127.0.0.1"?  Would that bypass the need to
read the DnsConfig?

**Comment by RIAEvangelist** [comment]
Good call @wplittle ! since the error is DNSConfig related this could fix the issue.

**Comment by iamdriz** [comment]
@wplittle Tried that but I still get the DNSConfig error. As soon as remove my ethernet cable or disable my wireless connection the TCP breaks.

**Comment by wplittle** [comment]
Another thing you can try is to install the Microsoft Loopback Adapter:

1. Click Start, and in the search box type "hdwwiz" and click "hdwwiz.exe"
in the search results
2. Press Next to go to the 2nd page of the wizard, then select "Install the
hardware that I manually select from a list (Advanced)"  Press Next.
3. Select "Network Adapters" in the list and press Next.
4. Select "Microsoft" under Manufacturer, then select "Microsoft Loopback
Adapter" under Network Adapter.  Press Next and finish out the wizard.
5. The additional interface will appear in the Network Connections window
as an additional "Local Area Connection" that you can configure if needed.

Perhaps this will address the issue, as it will provide a minimal network
infrastructure at all times regardless of the state of your ethernet cable
or wireless.

**Comment by iamdriz** [comment]
Still get that error about the DnsConfig.. but noticed that doing the above has created a network that says 'Unidentified Network'... is that correct?

![image](https://cloud.githubusercontent.com/assets/801252/8654740/345dac6e-2984-11e5-9460-de7d8571f2ca.png)

**Comment by wplittle** [comment]
I'll see what it looks like on my Windows 7 machine at the office tomorrow
morning.  In the meantime, can you post the output of ipconfig (from the
command prompt)?

**Comment by wplittle** [comment]
oh and can you ping localhost?

**Comment by iamdriz** [comment]
![image](https://cloud.githubusercontent.com/assets/801252/8670892/88a4ed7a-2a18-11e5-81f9-4b9451c1ff8f.png)

**Comment by iamdriz** [comment]
@wplittle Did you get chance to look at this? Thanks

**Comment by iamdriz** [comment]
@RIAEvangelist @wplittle Did you get any further with this? It's really holding up a project we're working on that requires TCP but won't be connected to the internet in production environments. Thanks.

**Comment by RIAEvangelist** [comment]
@wplittle would it be possible to do a pull and run the tcp exampl on a windows box tomorrow? Just to triple confirm this doesn't happen on our network & boxes?

@iamdriz appologies, just wanted to ask if this is reproduce-able on multiple machines?

**Comment by RIAEvangelist** [comment]
And one final question, does UDP respond the same way?

**Comment by iamdriz** [comment]
@RIAEvangelist No need to apologise. Really apprecitating the help so far, and hopefully we can get it resolved soon :)

**Comment by iamdriz** [comment]
Also just tried it as `UDP4` and as soon as I run it without an internet connection then I see the error about the DnsConfig... So it seems it needs it for this as well.

**Comment by RIAEvangelist** [comment]
OK :(

**Comment by iamdriz** [comment]
@wplittle @RIAEvangelist Just realised that I forgot to mention that the two Node applications are Electron apps (atom-shell) which uses Chromium and some other magic. I wonder if this has an impact on this issue?

**Comment by wplittle** [comment]
@iamdriz  sorry I've not been around for a while.  I noticed when pinging
localhost that it returns the IPv6 address of ::1

Perhaps try hardcoding in ::1 instead of the hostname "localhost" or
127.0.0.1  to again try to bypass the need to do anything with DNS.  The
"Failed to read DnsConfig" looks like it's coming from an operating system
library.

Otherwise another thing to try is to configure the loopback adapter we
installed earlier with a static IP and hostname.  Use an IP address in one
of the ranges standardized for private networks (e.g. 192.168.x.x  or
10.x.x.x) but also it will need to be in a subnet that won't conflict with
other IP addresses when you *are* connected to the network.

**Comment by iamdriz** [comment]
Setting the host to `::1` gave this error:

![image](https://cloud.githubusercontent.com/assets/801252/8804570/c25b4558-2fc4-11e5-9ead-dff330dc9da0.png)

**Comment by RIAEvangelist** [comment]
@iamdriz thanks for working with us on this, it will help others when we get it working.

1. Did you have a chance to run your app on another computer? I am interested in this.
2. can you execute the simple TCP examples (examples dir) in node? If these work but the app does not it would help direct us on how to help.

**Comment by iamdriz** [comment]
Okay I can confirm that this issue ONLY happens when running inside Electron... I'll check over there and see if they have any ideas.

**Comment by RIAEvangelist** [comment]
OK. I have a question reguarding the atom application you are developing.

Is there any specific reason you are using ATOM? Would it be trivial to port your application to [nw.js](http://nwjs.io/)?

**Comment by iamdriz** [comment]
@RIAEvangelist One of the developers of Electron tried to replicate this issue and found this: https://github.com/atom/electron/issues/2299#issuecomment-123936928 does this make any sense to you? I'm confused how it's iojs related as I only get this issue in Electron rather than standalone.

**Comment by RIAEvangelist** [comment]
seems like crappy support to me.

I'm installing a win7 VM now, will try in nw.js (node-webkit) its similar to electron but I prefer it dramatically.

I tested in nw on linux and as expected it works fine, but lets see on the vm.

**Comment by RIAEvangelist** [comment]
I ran the test myelf, io.js does appear to be the issue.
An older version of nw.js like 11.x would work though.

I'll file a bug on io.js

**Comment by RIAEvangelist** [comment]
created a bug report on io.js repo

nodejs/io.js/issues/2237

**Comment by RIAEvangelist** [comment]
also refrenced on nwjs nwjs/nw.js/issues/3708

**Comment by iamdriz** [comment]
Due to this being an issue that may not be fixed for some time (if at all), I've used Socket.io for this application, which is working fine in Electron regardless of the network connection. So I'd recommend people use that for communication across Electron applications. But this module is fine outside of Electron :)

**Comment by RIAEvangelist** [comment]
note this is only an issue on windows with io.js. its strange that websockets would work since they are implemented ontop of TCP.

**Comment by RIAEvangelist** [comment]
@iamdriz I have found that statement inaccurate... see below.

You *must* have made a mistake with the very first suggestion @wplittle gave you.

With the help of the io.js team I discovered its directly related to using 'localhost' instead of '127.0.0.1' so *yes* there is still a bug ion iojs however by specifying 127.0.0.1 as @wplittle suggested I was able to make this woirk in both io.js and nwjs both of which failed earlier. and nwjs is basically like electron.

@iamdriz I would appreciate you running this code as well to make sure it would have solved your issue.

This is especially important because you stated this will not work in electron. If it does, perhaps we can implement a work around for the iojs bug by defaulting localhost to 127.0.0.1 in node-ipc on windows machines

![it works!](http://i.imgur.com/cXErNPV.png)

**Comment by RIAEvangelist** [comment]
@iamdriz  example code :

## Server

    var nodeIpc = require('node-ipc');

    nodeIpc.config.id   = 'server';
    nodeIpc.config.retry = 1500;
    nodeIpc.config.silent = true;

    nodeIpc.serveNet(
        '127.0.0.1',
        8003,
        function(){
            nodeIpc.server.on(
                'message',
                function(data,socket){
                     console.log(data)
                     nodeIpc.server.emit(
                        socket,
                        'message',
                        'hello client!'
                    );
                }
            );
        }
    );

    nodeIpc.server.start();


## Client

    var nodeIpc = require('node-ipc');

    nodeIpc.config.id   = 'client';
    nodeIpc.config.retry = 1500;
    nodeIpc.config.silent = true;

    nodeIpc.connectToNet(
        'server',
        '127.0.0.1',
        8003,
        function(){
            nodeIpc.of.server.on(
                'connect',
                function(){
                    nodeIpc.log('## connected to server ##'.rainbow);
                    nodeIpc.of.server.emit(
                        'message',
                        'hello server!'
                    )
                }
            );

            nodeIpc.of.server.on(
                'message',
                function(data){
                     console.log(data)
                }
            );
        }
    );

**Comment by iamdriz** [comment]
I tried both localhost and 127.0.0.1 and they both failed for me.

**Comment by RIAEvangelist** [comment]
Can you please try the code I used above?

This worked for me.

**Comment by RIAEvangelist** [comment]
copy paste test, it should not take long

**Comment by RIAEvangelist** [comment]
The issue should have nothing to do with node or iojs. They both respond the same way. it is a windows specific issue with TCP host name resolution when the network card is turned off.

**Comment by RIAEvangelist** [comment]
I have updated the default values, and versioned the npm modules. if you do a fresh pull and do not specify a host it will by default now use 127.0.0.1 and work on windows without networking

**Comment by iamdriz** [comment]
Was your code inside an Electron app? Just wanted to clarify that. As that's where the issue is, it works fine standalone, but fails in Electron (when no network).

**Comment by RIAEvangelist** [comment]
If you could please copy paste the example code above and test it that would be a lot of help.

We have put a lot of time fixing this and just want to make sure given the unique situation you have it works.

Again, please run the copy paste test for us.

**Comment by iamdriz** [comment]
@RIAEvangelist This still doesn't work for me when running the examples in Electron. As soon as I pull my network cable out of the machine it starts erroring in the console.

**Comment by iamdriz** [comment]
This is what I have running:

**Comment by RIAEvangelist** [comment]
if you start it and then pull out network cable while it is running it will choke the server on windows. If the cable is in the server will connect via the network card. When the cable is pulled out after that, windows shuts the network card down thus killing the server.

You would need to handle this in your app to cause the server to restart. The client should continue to listen for the server to start up I believe. The servers don't restart on crash because that could end up causing endless crash loop.

If you start with the network cable out you would be fine.

**Comment by RIAEvangelist** [comment]
Thank you for testing by the way.

**Comment by Globik** [comment]
I am also on Window 7, 32bit. The WebRTC examples by Janus WebRTC Gateway are not working without Internet Connectivity. This windows's specific issue. Janus gateway compiled on my laptop. And the nodejs server also on laptop. I checked, with internet all examples work fine. One should dancing over dns and static ip addresses on windows.
