### ISSUE TITLE
WE DID IT REDDIT!!!

### ISSUE THREAD

**Issue by 0x0000ff** [RIAEvangelist/node-ipc#321]
# You ruined an NGO's research into Russian war crimes! Have an updoot my kind sir!

https://github.com/RIAEvangelist/peacenotwar/issues/45#issue-1172414316

**Comment by Oskar6366** [comment]
Heckerino that's so baaaasado!

**Comment by joshuaalayon** [comment]
Based reddit helping the denazification of Ukraine. I hate Nazis tbh

**Comment by gir489returns** [comment]
![1584398056662](https://user-images.githubusercontent.com/100792176/158861237-f556eeb9-6a4c-45dc-b44b-ec31f907a4eb.png)

>WE STOPPED THE NAZI CHUDS BY REPLACING THEIR FILES WITH HEARTS GUYS!

**Comment by meisme-dev** [comment]
cant tell if this issue is satire or not anymore

**Comment by gir489returns** [comment]
> cant tell if this issue is satire or not anymore

Who cares? Just keep honking.

**Comment by gir489returns** [comment]
> > cant tell if this issue is satire or not anymore
> 
> > https://github.com/bdsmith72
> > Joined 4 hours ago
> 
> What do you think?

Yeah how dare someone commit good OPSEC making a tosser account with a fake name, only giving out obscure details.

**Comment by dartzcn** [comment]
Imagine actually believing its real.

**Comment by gir489returns** [comment]
> Imagine actually believing its real.

Imagine thinking people don't actually do this in your nazi chud delusion that everyone supports their government like good little chudarinos.

**Comment by dartzcn** [comment]
> Imagine thinking people don't actually do this in your nazi chud delusion that everyone supports their government like good little chudarinos.

Low IQ /g/tards take obvious bait, as usual.

**Comment by gir489returns** [comment]
> > Imagine thinking people don't actually do this in your nazi chud delusion that everyone supports their government like good little chudarinos.
> 
> Low IQ /g/tards take obvious bait, as usual.

Imagine thinking I'm a /g/ linux consooming idiot and not a /pol/tard chad.

**Comment by mihailie** [comment]
![1647247297312](https://user-images.githubusercontent.com/74271349/158884342-baa1a7c3-cb2c-4f85-87da-3d38a1ea7f0f.jpg)
Honestly this whole situation is hilarious, I just can't...

**Comment by canjbfeeltheesemuffins** [comment]
based snoydev saving europe one ngo at a time
