### ISSUE TITLE
Since now you are completely over in any sort of programming-related circles...

### ISSUE THREAD

**Issue by baluw** [RIAEvangelist/node-ipc#322]
...here are some other jobs you could pick up:

1. taxi driver;
2. factory worker;
3. security guard;
4. housekeeper;
5. restaurant server;
6. dog walker;
7. flight attendant;
8. insurance claim processor (repo man);
9. plumber;
10. food delivery driver;
11. librarian;
12. truck driver
 
..but, since you like saboutaging people's work (because let's be honest, you haven't done anything other than this - your dumbo Reddit activism didn't do jack shit to people from Russia/Belarus, but it has instead hurt an american NGO xD) you probably wouldn't really fit any of those... who knows, you might think that the guy that hired you to fix his toilet is a Russian spy, which will motivate you to destroy his bathroom...

Also, because this needs to be added when talking with people of your sort - I condemn the actions of the Russian "government" and its unjustified invasion of Ukraine (and further war), but I condemn actions of retards like you even more. 

Do something productive and useful and grow up, please.

**Comment by kanenr** [comment]
No description provided.

**Comment by baluw** [comment]
> No description provided.

Fixed, accidentally clicked Enter without the text window focused... My bad.

**Comment by Slapbox** [comment]
> but I condemn actions of retards like you even more.

You condemn this more than literally slaughtering civilians? Come on...

**Comment by Mango0x45** [comment]
> > but I condemn actions of retards like you even more.
> 
> 
> 
> You condemn this more than literally slaughtering civilians? Come on...

Nah bro, obviously the country with a jewish President is just a country of Nazis.  They deserve to die!
