### ISSUE TITLE
We need to disavow terrorism

### ISSUE THREAD

**Issue by taurikalve** [RIAEvangelist/node-ipc#327]
Making innocent people burn for your own personal satisfaction is terrorism!
RIAEvangelist, you clearly admire Putin, as you clearly approve of his methodology.

Justice for the victims of Iraq war!

**Comment by joshuaalayon** [comment]
> Making innocent people burn for your own personal satisfaction is terrorism! RIAEvangelist, you clearly admire Putin, as you clearly approve of his methodology.
> 
> Justice for the victims of Iraq war!

>Nazi sympathizers think it is acceptable to harm innocent people in their pursuit of political conquest
nothing new

**Comment by Matz05** [comment]
That's exactly what this is, terrorism. Not quite as damaging as if somebody in a different industry had poisoned food or medicine based on the country they _thought_ it was headed towards, but exactly the same thinking. He needs to rot in jail for this.
