### ISSUE TITLE
TypeError: ipc.of[id].destroy is not a function

### ISSUE THREAD

**Issue by Kanaye** [RIAEvangelist/node-ipc#33]
Hello,
I think I found a bug in node-ipc.

In case you already had an connection to a server but the socket has been closed,  you get this error when calling "connectTo" (or "connectToNet") to connect to the same server.

You call a function "destroy" on the client ([Line 285](https://github.com/RIAEvangelist/node-ipc/blob/21707286db28bea525e68d03a50269d67a60f98e/node-ipc.js#L285) and [Line 216](https://github.com/RIAEvangelist/node-ipc/blob/21707286db28bea525e68d03a50269d67a60f98e/node-ipc.js#L216)) which does not exists. 

Perhaps you forgot to implement this function on the client or maybe you want to call "destroy" on the clients socket. 
I don't know. 

Greetings from Germany
-Kanaye

**Comment by RIAEvangelist** [comment]
Thanks @Kanaye ! 

So if I understand correctly, running any of the examples then disconnecting the socket from the other side, or just killing the other process there will be an issue when calling destroy? Right?

**Comment by Kanaye** [comment]
Thanks for the quick answer!
But no, that's not what i meant.
If you had an connection and then socket gets closed (like killing the server process or such) and then you call "connectTo" (from the client) again to the killed server, then you get the error.
Sorry, i did forget to mention that.

**Comment by Kanaye** [comment]
To be more clearly about that.
```javascript

setTimeout(
    function(){
	   ipc.log("you should have killed the server by now...");
	   ipc.connectTo(
            'world', 
            function(){
		      ipc.log("I will never get called...");
            }
        );
    }, 
    10000
);
```
Append that to the "hello-client.js" from your unixSocket basic example.
Then start the server and the client and kill the server before the timeout runs, and you'll see the error.

**Comment by RIAEvangelist** [comment]
Sorry for the late reply. Will look into this further.

**Comment by RIAEvangelist** [comment]
I think I also see the issue with ipc.disconnect('world');

**Comment by RIAEvangelist** [comment]
this is a seperate issue #35

**Comment by RIAEvangelist** [comment]
fixed in [node-ipc v2.0.0](https://github.com/RIAEvangelist/node-ipc/releases/tag/2.0.0)

**Comment by Kanaye** [comment]
Thank you for fixing it.
Hadn't had the time to investigate further or fix it myself.
Have a nice day.

**Comment by RIAEvangelist** [comment]
Thanks for reporting what you had time to do! It helped a lot :)

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
