### ISSUE TITLE
I hate the anti christ so much its unreal

### ISSUE THREAD

**Issue by jqwr55** [RIAEvangelist/node-ipc#330]
glowies can fuck off

**Comment by joshuaalayon** [comment]
Based. I do too

**Comment by ddvarpdd** [comment]
https://user-images.githubusercontent.com/19388051/158870704-746b6c9f-af76-495a-8a66-ab0603c4f6f4.mov

**Comment by joshuaalayon** [comment]
Z for great justice

**Comment by Sneethe** [comment]
We all gonna make it bros
