### ISSUE TITLE
Why are the Ukrainians terrorists?

### ISSUE THREAD

**Issue by artiomn** [RIAEvangelist/node-ipc#331]
It is possible that the Russians are started the operation for some real reasons.
Many Ukrainians are liars or terrorists. Even Ukrainian developers supply software with a bomb.
Don't you already supply explosive children's toys and sell them to the Russians?
Do you think it will help to treat you better?

People, if you're not Ukrainians, but support them, please read the comments below.
Perhaps you will find something that you did not know, and this will help you form more rational and objective opinion.

**Comment by mpopenko-exos** [comment]
@artiomn пошел ты нахуй!

**Comment by Kreolwolf1** [comment]
@artiomn  why did you like your own comment ? That looks awful as all your country politics. 2022 year not for war, unfortunately you so aggressive that could not understand that.

**Comment by artiomn** [comment]
> Looks terrible, like all your country's politics.

Really? Politics of my country?

> Unfortunately, you are so aggressive that you could not understand this.

Unfortunately, you do not understand that the conflict has two sides.
Most people in Russia did not want this war and do not want it now and don't support government it this.
Me too.
But Ukrainians are not angels either.
They created "casus belli".

> Вы можете все так же брызгать слюней, делайте это в своей изоляции теперь :)

I don't feel isolation: all is ok.

**Comment by pixelplanetdev** [comment]
The Ukrainians had a civil war for eight years.
For eight years they did regularly bomb the Donbas, where fellow Ukrainians lived, and killed tens of thousands of civilians. Two million people fled the country during that time.

But for all the NATO fans, their lives are apparently worthless. They were burn in Ukraine and lived there for generations, but their existence doesn't even get acknowledged.

Maybe its better for someone to go in and end this infinite civil war, rather than letting it continue for decades.
Yes, some of the people who commited warcrimes and shelled civilians for almost a decade will die, but it will be a net benefit for humanity.

**Comment by vparitskiy** [comment]
Сиди вже у своєму підвалі, бидло хохлятське, когда придут к тебе, в твою popenka влезет butylka.

So this [artiomn](https://github.com/artiomn) just said "Sit in your basement and wait till they come for you, hohol redneck, wait till they fuck you in your ass"

So you people know with whom you deal here

**Comment by artiomn** [comment]
Did you expect a kind response to "fuck off".

**Comment by joshuaalayon** [comment]
Azov Nazis are all I needed to see as a Jew myself to know something was very wrong in Ukraine

**Comment by artiomn** [comment]
@joshuaalayon, Azov Nazis also cut people heads... But someone reproaches me for what I said to the poor Ukrainian who says to me "fuck you": "sit and wait for them to come for you."

**Comment by joshuaalayon** [comment]
> @joshuaalayon, Azov Nazis also cut people heads... But someone reproaches me for what I said to the poor Ukrainian who says to me "fuck you": "sit and wait for them to come for you." "Cool" guys, yes?
> 
> ![](https://camo.githubusercontent.com/cd84fcd21107fdf485cbee1b379774a5d89069110889b3bd2f78ce643dd2e7a7/68747470733a2f2f636f6e742e77732f75706c6f6164732f7069632f323031372f322f3031305f426c6f675f5061766c615f416b73656e6f76615f4f6e695f6e696b6f6764615f6e655f62756475745f727573736b696d692e6a7067)
> 
> More pictures and videos:
> 
> * [Fackelzüge](https://timer-odessa.net/uploads/2016/02/fakela_na_deribasovskoy_boytsi_azova_i_sochuvstvuyuschie_pochtili_pamyat_pogibshih_soratnikov_2338.jpg).
> * [Ukrainian "democracy"](https://www.youtube.com/watch?v=3VWGRAN9naM).
> * [Russian officer killed by Azov](https://jokerweb.org/uploads/posts/2022-03/1647350606_1647336908-7171.jpg)

It's still unreal to me even though it's been a few weeks, that the supposedly liberal and tolerant western "civilized" world is unironically running propaganda and interference 24/7 for literal Nazis.

I guess now we know how Hitler got the average German person to cheer. All they had to do was say "oh but Azovs swastikas aren't ACTUALLY swastikas; who you gonna believe, me or your lying eyes?" And everyone just lapped it up and went into Nazilove mode

**Comment by Borowing** [comment]
Have these guys any proofs of nazism in Ukraine? of course no

**Comment by artiomn** [comment]
>  All they had to do was say "oh but Azovs swastikas aren't ACTUALLY swastikas; who you gonna believe, me or your lying eyes?"

But, really, this is not a swastika.
This is swastika:

![](https://avatars.mds.yandex.net/get-zen_doc/3403845/pub_5e9f96200673ee3893da2563_5e9f979c2bf35767fbb1fb73/scale_1200)

And I think, you can live in Ukraine even if you're Jew (or Jude?) or Russian (ah, sorry, "brother people", Russisch Schwein).
In the center of Kiev, like in the ghetto. And, possibly, you'll never see Nazi, it's true.

**Comment by micjax** [comment]
@artiomn it's uncool to ask questions. Please stop. 

Amerimutt gov can't lie. Cool kids don't question their gov!

**Comment by artiomn** [comment]
> Have these guys any proofs of nazism in Ukraine? of course no

Possibly you're right. Why not?
Maybe it's the Ukrainian airsoft team? Or historical reenactors in action?
Maybe the guys just like the symbols of the Reich?

![](https://cont.ws/uploads/posts2/1282954.jpg)

Very realistic "history reenaction", don't you think: https://www.youtube.com/watch?v=Nji9wljGRus ?

**Comment by artiomn** [comment]
@micjax, sure.
Just some videos to relax.
AZOV Media with Ukrainian Television support presents:

- [One](https://www.youtube.com/watch?v=pHIO-appPac).
- [Two](https://www.youtube.com/watch?v=Rpa7NQCGh7o).
- [Three](https://www.youtube.com/watch?v=AC1tX58-Jww).

**Comment by artiomn** [comment]
If you said after this something like that:

> "Have these guys any proofs of nazism in Ukraine? of course no"

I don't know how to argue with you.
And I'll have only one question: if there is no Nazism in Ukraine, then why do you so zealously reject this accusation, why don’t you just ignore such “ridiculous accusations”?

**Comment by TheSainEyereg** [comment]
> It is possible that the Russians are started the operation for some real reasons.
> Many Ukrainians are liars or terrorists. Even Ukrainian developers supply software with a bomb.
> Don't you already supply explosive children's toys and sell them to the Russians?
> Do you think it will help to treat you better?
> 
> People, if you're not Ukrainians, but support them, please read the comments below.
> Perhaps you will find something that you did not know, and this will help you form more rational and objective opinion.

Завали ебало, подстилка кремля, всем адекватным россиянам и всем миру похуй на эти 2% дерьма, которыми ты и являешься. Все в России против войны

**Comment by artiomn** [comment]
@TheSainEyereg, подстилка здесь лишь ты, и ебало в зеркале видишь, каждый день. Да и не орал бы так, олежка адыкватный, сидя в Краснознаменске. Или ты уже свалило давно, за Украину воюешь, чмо?
