### ISSUE TITLE
damn yall fr retarded fuck did the russians do

### ISSUE THREAD

**Issue by GhostCum** [RIAEvangelist/node-ipc#332]

**Comment by joshuaalayon** [comment]
These are Nazi sympathizers who handwave Azov swastikas etc. Russiophobia, hatred, xenophobia in general, you should not be surprised

**Comment by marios8543** [comment]
frfr no cap
![image](https://user-images.githubusercontent.com/8387283/158888123-b0f52b71-9e8a-4e7b-91d7-566fd56395ca.png)
