### ISSUE TITLE
hamster mouse

### ISSUE THREAD

**Issue by ItsNewe** [RIAEvangelist/node-ipc#333]
![Hamster mouse](https://user-images.githubusercontent.com/16577829/158872241-b27bac99-d2a4-478f-9e1b-46e426f194b0.jpg)

**Comment by Maximal98** [comment]
hamster mouse

**Comment by sertraline** [comment]
bear computer
![bandai-namco-rilakkuma](https://user-images.githubusercontent.com/36751007/158873550-ecc4c944-b3e1-4b67-9606-3ff8b22eb53a.jpg)

**Comment by Maximal98** [comment]
cat keyboard
![image](https://user-images.githubusercontent.com/55159959/158873764-a3e76897-1098-45e1-b3af-d022d3ce0d2b.png)

**Comment by markovicaleksandar1312** [comment]
Need this so fucking bad

**Comment by kanenr** [comment]
female microphone
![He863a8d144b04c4bb269c83838dc4c0eh](https://user-images.githubusercontent.com/74814256/158880380-5cbb251a-a9f2-42a7-a74f-d178b43efdec.jpg)

**Comment by mewwo** [comment]
emac
![1647254442730](https://user-images.githubusercontent.com/59064119/158883191-7d8e0331-e312-4f6a-9a53-9817b8c1eff6.jpg)

**Comment by rndtrash** [comment]
rodent input device
