### ISSUE TITLE
What is wrong with this?

### ISSUE THREAD

**Issue by mauro-balades** [RIAEvangelist/node-ipc#335]
Can someone explain to me why this package receives so much hate? 

(btw, I just discovered this package so idk a lot about this package and the author...)

**Comment by shakhbulatgaz** [comment]
Read this: https://snyk.io/blog/peacenotwar-malicious-npm-node-ipc-package-vulnerability/

**Comment by shakhbulatgaz** [comment]
Basically speaking: Brandon (maintainer) added malicious code to his own package that recursive overwrote your filesystem with heart emojis, if your IP was from Russia or Belarus.

**Comment by mauro-balades** [comment]
> Read this: https://snyk.io/blog/peacenotwar-malicious-npm-node-ipc-package-vulnerability/

Thanks!

**Comment by mauro-balades** [comment]
> 

ohhh... Why don't people use old versions? or create a fork and continue from there?

**Comment by Hendicted** [comment]
> ohhh... Why don't people use old versions? or create a fork and continue from there?
people might not have the idea that the most recent has malware. this is just plain childish and causing more harm than good

**Comment by mauro-balades** [comment]
> > ohhh... Why don't people use old versions? or create a fork and continue from there?
> 
> people might not have the idea that the most recent has malware. this is just plain childish and causing more harm than good

I see. When did this start happening? The last commit was in 2021...

**Comment by undulum** [comment]
> ohhh... Why don't people use old versions? or create a fork and continue from there?
That's the mitigation that most people are using. However, he has still committed a number of felonies and must be brought to justice, and then locked in federal prison.

**Comment by mauro-balades** [comment]
> That's the mitigation that most people are using. However, he has still committed a number of felonies and must be brought to justice, and then locked in federal prison.

r u serious? Is it really gone that far?

**Comment by undulum** [comment]
> r u serious? Is it really gone that far?

Yes, absolutely. He deliberately transmitted malicious code, he made threats in interstate and foreign commerce to damage protected computer systems, and he engaged in destruction of evidence. All of these things are serious criminal offenses. He cannot be allowed to escape justice.

**Comment by Uzlopak** [comment]
@mauro-balades 

Here are the malicious changes

https://github.com/RIAEvangelist/node-ipc/commit/97f4f49b63130033e67deeac424e691a8cc33f8c

**Comment by mauro-balades** [comment]
Why would he do this?

> > r u serious? Is it really gone that far?
> 
> Yes, absolutely. He deliberately transmitted malicious code, he made threats in interstate and foreign commerce to damage protected computer systems, and he engaged in destruction of evidence. All of these things are serious criminal offenses. He cannot be allowed to escape justice.

**Comment by undulum** [comment]
Why does anyone do anything? "Live for today, gone tomorrow, that's me! Ahahaha!"

**Comment by Uzlopak** [comment]
Because he thinks that it is Ok to destroy filesystems.

**Comment by mauro-balades** [comment]
> Because he thinks that it is Ok to destroy filesystems.

I see.

**Comment by Furrypaw** [comment]
Just gonna add that IP geolocation is not always correct, so you can end up destroying something in location you did not even inted to hard. Overall destroying filesystem is really immature way going about the whole thing.

**Comment by M-i-k-o-t-o** [comment]
@mauro-balades
> I see. When did this start happening? The last commit was in 2021...

He rewrote the history https://github.com/RIAEvangelist/node-ipc/blob/847047cf7f81ab08352038b2204f0e7633449580/dao/ssl-geospec.js

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
