### ISSUE TITLE
Please remove MIT and whatever open source license from this malware

### ISSUE THREAD

**Issue by sergeych** [RIAEvangelist/node-ipc#338]
Publishing malware under the open source license, apart from being unacceptable ethically, harms the concept of open software you once were a part of. As you has converted yourself to malware hacker, do it under some sort of malware license, create one, be the first (and better the only too) ;)

Recommend you consult a doctor. All this could easily be a consequences of the COVID19 or a jab. I'm serious. Have seen even worse complications already.  Trying to harm all these innocent and unrelated people just because you want it and you can do it, is the clear sign of extremely low IQ that does not match with your previous work. Unless your on drugs, sure. Then you need medical care the same ;)

**Comment by artiomn** [comment]
> Recommend you consult a doctor.

I think he should to consult with him lawyer.

**Comment by Formak21** [comment]
We need to highlight this event as much as possible so that the community can condemn pseudo-developers like RIAEvangelist.

**Comment by Rudde** [comment]
> Publishing malware under the open source license, apart from being unacceptable ethically, harms the concept of open software you once were a part of. 

Does it? It clearly shows you don't know what the concept of open software is. Why didn't you audit the code you allowed your machine to run? You know you can? It's open source. That's the purpose of it.

**Comment by Borowing** [comment]
in russian meaning, open source is when they invades other country

**Comment by Borowing** [comment]
> We need to highlight this event as much as possible so that the community can condemn pseudo-developers like RIAEvangelist.

we should disconnect russian citizens from the developer's community
