### ISSUE TITLE
Киев за три дня - не получилось, грусно))) 

### ISSUE THREAD

**Issue by Borowing** [RIAEvangelist/node-ipc#342]
я даже не знаю как это по фиксить

**Comment by ddvarpdd** [comment]
![7025 - 0272860b16ffeb6642383ac18c907acf](https://user-images.githubusercontent.com/19388051/158885687-19c364d4-6eb6-4cf8-871a-1641469372b8.png)

**Comment by Borowing** [comment]
> ![7025 - 0272860b16ffeb6642383ac18c907acf](https://user-images.githubusercontent.com/19388051/158885687-19c364d4-6eb6-4cf8-871a-1641469372b8.png)

дааааа, как же грусно, а я так ждал, эх
