### ISSUE TITLE
humor thread 

### ISSUE THREAD

**Issue by mihailie** [RIAEvangelist/node-ipc#344]

**Comment by mihailie** [comment]
![1647373286301](https://user-images.githubusercontent.com/74271349/158885196-4054cc87-e713-4cfe-a710-018bf33a96ff.jpg)

**Comment by djracemixer** [comment]
![Uploading 1646431831166m.jpg…]()

**Comment by greasybastard** [comment]
<img src='https://i.kym-cdn.com/photos/images/original/001/953/791/c30.gif' />

**Comment by djracemixer** [comment]
![Uploading 905f77a0dcb65dcb4ed8db4acc7239582327ee32ea6990e700a457ebd6063f05.jpg…]()

**Comment by TheWentiko** [comment]
![1641995358444](https://user-images.githubusercontent.com/61360308/158886967-d84174d7-ab5d-41a6-be83-9a147899868d.jpg)

**Comment by realratchet** [comment]
![1645876866734](https://user-images.githubusercontent.com/25830638/158887192-2933b509-8bb2-4e0b-8392-3896493b528d.jpg)

F

**Comment by Borowing** [comment]
![photo5289928858923022867](https://user-images.githubusercontent.com/53659632/158887899-0cf0860d-10cd-4584-81f9-9839092f3e78.jpg)
