### ISSUE TITLE
Is this real?

### ISSUE THREAD

**Issue by greasybastard** [RIAEvangelist/node-ipc#347]
<img src='https://i.kym-cdn.com/photos/images/original/001/953/791/c30.gif' />

**Comment by ddvarpdd** [comment]
what the actual FUCK

**Comment by Borowing** [comment]
@greasybastard yes, even more, we cut into salami the Russians who invaded us, and it's funny the same as coding

**Comment by ketsushiri** [comment]
![ebin](https://imgur.com/QvFiKdR.gif)

**Comment by ddvarpdd** [comment]
https://user-images.githubusercontent.com/19388051/158887972-c64131e7-09a6-4656-aafe-05205df67a11.mp4

**Comment by horonekb** [comment]
8 years Ukrainian Nazis destroyed Russian people with artillery, now it's time to pay the bills

**Comment by canjbfeeltheesemuffins** [comment]
it was real in my mind

**Comment by Borowing** [comment]
@horonekb Yeah, of course, as you said, so russia decided to crush Kharkiv, the most russian city in Ukraine :+1:

**Comment by ddvarpdd** [comment]
> 8 years Ukrainian Nazis destroyed Russian people with artillery, now it's time to pay the bills

> Yeah, of course, as you said, so russia decided to crush Kharkiv, the most russian city in Ukraine


![7633 - 0060ef64f5cc40dbacdd2e60a3e0b9cd](https://user-images.githubusercontent.com/19388051/158890011-40c2e36e-543b-4706-8c8c-eecf70d3e2e8.jpg)

**Comment by horonekb** [comment]
Nazis from the Ukrainian army hide in houses, put artillery in the yards, cover themselves with civilians.
