### ISSUE TITLE
Declare RIAEvangelist a hero of Ukraine

### ISSUE THREAD

**Issue by Borowing** [RIAEvangelist/node-ipc#348]
Ghoust of Github

**Comment by canjbfeeltheesemuffins** [comment]
Trap Battalion

**Comment by horonekb** [comment]
8 years Ukrainian Nazis destroyed Russian people with artillery, now it's time to pay the bills

**Comment by Borowing** [comment]
@horonekb Yeah, of course, as you said, so russia decided to crush Kharkiv, the most russian city in Ukraine :+1:

**Comment by horonekb** [comment]
Nazis from the Ukrainian army hide in houses, put artillery in the yards, cover themselves with civilians.

**Comment by Borowing** [comment]
@horonekb Ukrainian army is fighting in their lands, different from russian army
