### ISSUE TITLE
Russia fuck UA nazi

### ISSUE THREAD

**Issue by horonekb** [RIAEvangelist/node-ipc#349]
Fuck nazi from all world....

**Comment by Borowing** [comment]
- do you see nazi in Ukraine? 
- No
- but they exist

**Comment by horonekb** [comment]
8 years Ukrainian Nazis destroyed Russian people with artillery, now it's time to pay the bills

**Comment by canjbfeeltheesemuffins** [comment]
dey ded fo 80 years doe

**Comment by Borowing** [comment]
@horonekb Yeah, of course, as you said, so russia decided to crush Kharkiv, the most russian city in Ukraine :+1:

**Comment by Borowing** [comment]
@horonekb Ukrainian army is fighting in their lands, different from russian army
