### ISSUE TITLE
Kyiv in three days didn't work, maybe then github?

### ISSUE THREAD

**Issue by Borowing** [RIAEvangelist/node-ipc#351]
oh, I forgot, Putin gonna disconnect russian from the global internet, very sad :(

**Comment by pixelplanetdev** [comment]
Kyiv alone, the city, took 1 month to take for the Nazis in WW2 and took 1.5 months to take back by the Soviets.
If you believed that it is an "embarrassement" if you don't take it within three days, you are a really gullible sheeple believing your war propaganda.

btw. how did your recent Afghanistan war go?
