### ISSUE TITLE
WE FREED DONBASS, NEXT WE FREE WEBSHIT PACKAGE MANAGER!

### ISSUE THREAD

**Issue by captchaunited** [RIAEvangelist/node-ipc#360]
HELLO COMRADES,

AFTER THE SUCCESSFUL MILITARY OPERATION IN DONESTK AND LUHANSK, WE HAVE LIBERATED THE EAST OF UKRAINE FROM NAZI POWER. 

NEXT WE MUST CLEANSE THE WEBSHIT PACKAGE MANAGER FROM ALL NAZI AND NAZI SYMPATHIZER MALWARE. 

PRAISE ALLAH

**Comment by Borowing** [comment]
владимир путин молодец
vladimir putin is the best
