### ISSUE TITLE
I love you

### ISSUE THREAD

**Issue by Mango0x45** [RIAEvangelist/node-ipc#362]
Have my children

**Comment by Borowing** [comment]
putin doesn't love you

**Comment by RIAEvangelist** [comment]
I love you too :)

**Comment by RIAEvangelist** [comment]
The original license was DBAD, Don't be a dick, Putin violated the license agreement.

**Comment by Mango0x45** [comment]
> putin doesn't love you

That's ok, I wouldn't want him to have my children.

**Comment by BobHassok** [comment]
> 

I didn't know Putin was such an avid node user. Do you think he spins his own packages or maybe one of the millions of innocent people, which you just attacked with malware, do it for him?

**Comment by AreaDenial** [comment]
> The original license was DBAD, Don't be a dick, Putin violated the license agreement.

I'm pretty sure wiping innocent people's hard drives is considered a dick move, but I guess the rules don't apply to you.
