### ISSUE TITLE
sneed 

### ISSUE THREAD

**Issue by BanementI** [RIAEvangelist/node-ipc#367]
:trollface: enjoy your new criminal record dumbass 🤭:trollface:

**Comment by dascar5** [comment]
> :trollface: enjoy your new criminal record dumbass 🤭:trollface:

What law did he break, and where?

**Comment by BanementI** [comment]
> > :trollface: enjoy your new criminal record dumbass 🤭:trollface:
> 
> What law did he break, and where?

Sabotage, it hasn't been very long but who knows how much damage this has caused so far. There was never any good intention in secretly adding this, it's malicious.

**Comment by Chucksfeednseed** [comment]
> > :trollface: enjoy your new criminal record dumbass 🤭:trollface:
> 
> What law did he break, and where?

It's an intentional tort. Almost all states have something called comparative negligence which means even if the NGO is partly responsible, the jury allocates responsibility by percentage. Many states don't allow a percentage to be assigned to the plaintiff for intentional torts. Also the general rule is that you can't waive liability in a contract for an intentional tort either. He's totally fucked legally and if he was arguably acting as the agent for any company, they are vicariously fucked as well.

**Comment by Chucksfeednseed** [comment]
also don't forget you're basically defending a fellow coder for spreading malware intentionally, might not be so useful when future employers look through your history.

**Comment by dascar5** [comment]
> > > :trollface: enjoy your new criminal record dumbass 🤭:trollface:
> > 
> > 
> > What law did he break, and where?
> 
> Sabotage + making/spreading malware, it hasn't been very long but who knows how much damage this has caused so far. There was never any good intention in secretly adding this, it's malicious.



> > > :trollface: enjoy your new criminal record dumbass 🤭:trollface:
> > 
> > 
> > What law did he break, and where?
> 
> It's an intentional tort. Almost all states have something called comparative negligence which means even if the NGO is partly responsible, the jury allocates responsibility by percentage. Many states don't allow a percentage to be assigned to the plaintiff for intentional torts. Also the general rule is that you can't waive liability in a contract for an intentional tort either. He's totally fucked legally and if he was arguably acting as the agent for any company, they are vicariously fucked as well.



> also don't forget you're basically defending a fellow coder for spreading malware intentionally, might not be so useful when future employers look through your history.

dial 8

**Comment by Chucksfeednseed** [comment]
**_What the fuck did you just fucking update that repo with, you little bitch? I'll have you know I graduated top of my class in this NGO, and I've been involved in numerous post-Soviet states, and I have over 2500 confirmed whistleblowers. I am trained in cyber warfare and I'm the top human rights activist in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with wiping my server over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of NATO and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little "clever" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo._**

**Comment by the-brickster** [comment]
Formerly Chuck's

**Comment by BanementI** [comment]
> Formerly Chuck's

The sign is a subtle joke. The shop is called "Sneed's Feed & Seed", where feed and seed both end in the sound "-eed", thus rhyming with the name of the owner, Sneed. The sign says that the shop was "Formerly Chuck's", implying that the two words beginning with "F" and "S" would have ended with "-uck", rhyming with "Chuck". So, when Chuck owned the shop, it would have been called "Chuck's Fuck and Suck".

**Comment by Sneethe** [comment]
Whats a sneed?

**Comment by BanementI** [comment]
sneed bump
