### ISSUE TITLE
serveNet() function missing `else`?

### ISSUE THREAD

**Issue by bizMD** [RIAEvangelist/node-ipc#37]
When using serveNet() I get the following error:
```
            ipc.config.networkHost.data
                                  ^
TypeError: Cannot read property 'data' of undefined
```
I looked at the cause of the error and found this:
```
function serveNet(host,port,UDPType,callback){
    if(typeof host=='number'){
        callback=UDPType;
        UDPType=port;
        port=host;
        host=false;   
    }
    if(typeof host=='function'){
        callback=host;
        UDPType=false;
        host=false;
        port=false;   
    }
    if(!host){
        ipc.log(
            'Server host not specified, so defaulting to'.notice, 
            'ipc.config.networkHost'.variable, 
            ipc.config.networkHost.data
        );
        host=ipc.config.networkHost;
    }
    if(host.toLowerCase()=='udp4' || host.toLowerCase()=='udp6'){
        callback=port;
        UDPType=host.toLowerCase();
        port=false;
        host=ipc.config.networkHost;   
    }
   ...
```
The issue here is if I pass in a function for `host`, the value of `host` will be set to `false` in the second if statement. But on the third if statement, it will think the `host` variable is `false`, and assume `ipc.config.networkHost.data` exists. This causes the error above to be thrown.

It seems to me the way to fix this is by adding an `else` the problem would be solved.

Or am I using it wrong?

Here's the snippet of my code where the error occurs:
```
on: (events, cb) =>
		@_events = @_events.union events
		@_ipc.serveNet () =>
			@_events.forEach (subscription) =>
				@_ipc.server.on =>
					subscription
					(payload) =>
						{hash, sender, data} = payload?
						cb sender, data if hash is @_hash sender, data
```

**Comment by bizMD** [comment]
... I got it to work as is. Seems like I was incorrectly assigning config variables.

**Comment by RIAEvangelist** [comment]
Thanks for the good feedback!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
