### ISSUE TITLE
You better find a new job

### ISSUE THREAD

**Issue by s0menickname** [RIAEvangelist/node-ipc#378]
Just emailed Ethan Glass, CEO of a company you work for, about the NGO thing (#308), and suggested him to cut all ties with you to avoid reputational risks. No company is gonna employ a coder who used to push malicious code to an open source project (literally a criminal offense btw), so you probably need to start looking for a minimum wage job in retail or McDonald's in your area.

I recommend to everyone who is not indifferent to this horrifying shit to do the same as I did: ~ethan@getocra.com, CC to info@getocra.com.~
**UPD: Turns out it's the wrong OCRA. Address of the proper one: info@viveocra.com. Many thanks to some person who deleted their comment so I can't tag them.**

**Comment by kalix123** [comment]
It'll be pretty hard for him to get a new job after this. With his Github looking so bad.
This is exactly why you don't put programming and politics together. Hopefully he learns his lesson.

**Comment by burner03** [comment]
https://www.facebook.com/ocrajeans actually this is the company he works for as pulled from his Facebook linked here.
http://www.viveocra.com/

**Comment by s0menickname** [comment]
> It'll be pretty hard for him to get a new job after this. With his Github looking so bad. This is exactly why you don't put programming and politics together. Hopefully he learns his lesson.

That's exactly why my suggestion is to look for a minimum wage job straightaway, without attempting to get employed as a whatever IT specialist.

**Comment by unknown222** [comment]
> > It'll be pretty hard for him to get a new job after this. With his Github looking so bad. This is exactly why you don't put programming and politics together. Hopefully he learns his lesson.
> 
> That's exactly why my suggestion is to look for a minimum wage job straightaway, without attempting to get employed as a whatever IT specialist.

nah, with dev shortages on market, he will find job quite easy

**Comment by mihailie** [comment]
![image](https://user-images.githubusercontent.com/74271349/158913513-2e0621b7-df2d-4abd-b6a0-128457254f75.png)
Pick up king it's for you

**Comment by s0menickname** [comment]
> https://www.facebook.com/ocrajeans actually this is the company he works for as pulled from his Facebook linked here on his Github profile. http://www.viveocra.com/

OMG for real, thank you for the correction. I got this company from some other issue. I will write to the proper company now. Hope Ethan is fine 😅

**Comment by niallmurphy-ie** [comment]
> > > It'll be pretty hard for him to get a new job after this. With his Github looking so bad. This is exactly why you don't put programming and politics together. Hopefully he learns his lesson.
> > 
> > 
> > That's exactly why my suggestion is to look for a minimum wage job straightaway, without attempting to get employed as a whatever IT specialist.
> 
> nah, with dev shortages on market, he will find job quite easy

Who on Earth would hire someone who is likely to serve malware to your customers if he has a gripe with them?
