### ISSUE TITLE
Add support for Posix Sockets

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-ipc#38]
This will give Windows the benifit of the existing  ` Unix ` sockets

**Comment by RIAEvangelist** [comment]
Was able to modify connectTo event to support both windows and unix

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
