### ISSUE TITLE
Bug: Penis size shrunk after installation 

### ISSUE THREAD

**Issue by schlopp** [RIAEvangelist/node-ipc#387]
so I installed the latest release and my cock just got reeeeaaaally small. what do I do???

**Comment by thepwrtank18** [comment]
install an older version, it reverts the changes automatically

**Comment by schlopp** [comment]
if the developer could tag this as urgent it'd help

**Comment by thepwrtank18** [comment]
this isn't a bug, the developer did it on purpose because he'll never get a big one, so he just lowers the standard

**Comment by s0menickname** [comment]
Just lock a dependency version.
