### ISSUE TITLE
Removed malware

### ISSUE THREAD

**Issue by kalix123** [RIAEvangelist/node-ipc#389]
I'm pretty sure he's removed the actual malware. However it has already done irrevocable damage to many people. Until we get a well written apology from him it's as if it's still there. Also the nerve of someone to try and put malware into an Open Source package is disgusting. As many people have said, it's a disgrace to the entire FOSS community.

**Comment by thepwrtank18** [comment]
He didn't remove the malware. The geolocation api key got revoked.

**Comment by dartzcn** [comment]
Once trust has been broken, it can never truly be recovered.

People should either fork this or create alternatives; either way, there's no reason to trust the developer not to do this in the future and he should step down. (And quite frankly, unless someone's done a full audit of the code, there's no reason to believe this program isn't stealing all your files and logging everything you type either.)

**Comment by shybruh** [comment]
> I'm pretty sure he's removed the actual malware. However it has already done irrevocable damage to many people. Until we get a well written apology from him it's as if it's still there. Also the nerve of someone to try and put malware into an Open Source package is disgusting. As many people have said, it's a disgrace to the entire FOSS community.

I don't think any kind of apology can help fix his rep. He should've never done it in the first place, be vocal, post ab it on social media sure, but why do it with something a lot of people use? He knew the consequences, he wanted to look like a hero but failed, got clowned on. 
Hope he gets fired and/ leaves coding all together, you can't mix your feelings with this, just brings more miserable incels like him.

**Comment by kalix123** [comment]
> I don't think any kind of apology can help fix his rep. He should've never done it in the first place, be vocal, post ab it on social media sure, but why do it with something a lot of people use? He knew the consequences, he wanted to look like a hero but failed, got clowned on. Hope he gets fired and/ leaves coding all together, you can't mix your feelings with this, just brings more miserable incels like him.

Oh I agree, an apology wouldn't fix it and would not change our trust. However it would show us that he at least regrets his actions. Although I personally think that is extremely unlikely. It seems more likely that he, even now, stands by his actions and is unable to find fault in them.

**Comment by olyop** [comment]
Completely agree, writing malicious code like this is extremely dangerous and he should face consequences. It also sets a precedence with the open source community which would result in individuals and companies losing trust.
Does anyone know if npm has removed/blocked this version from being downloaded yet?

**Comment by shybruh** [comment]
> > I don't think any kind of apology can help fix his rep. He should've never done it in the first place, be vocal, post ab it on social media sure, but why do it with something a lot of people use? He knew the consequences, he wanted to look like a hero but failed, got clowned on. Hope he gets fired and/ leaves coding all together, you can't mix your feelings with this, just brings more miserable incels like him.
> 
> Oh I agree, an apology wouldn't fix it and would not change our trust. However it would show us that he at least regrets his actions. Although I personally think that is extremely unlikely. It seems more likely that he, even now, stands by his actions and is unable to find fault in them.

Yeah, this is why personal life and something like this should be separated in life. Just makes it hell for everyone else that doesn't want to be in it. 
The dev probably thinks he's so cool and is smug, but when the supposed lawsuit/ hits i hope he gets fucked, royally.

**Comment by s0menickname** [comment]
> I'm pretty sure he's removed the actual malware. However it has already done irrevocable damage to many people. Until we get a well written apology from him it's as if it's still there. Also the nerve of someone to try and put malware into an Open Source package is disgusting. As many people have said, it's a disgrace to the entire FOSS community.

No apology can fix this. Brandon must immediately leave the community and drop his profession. Wish him to then find a minimum wage job so he can pay for a lawyer. See #378 if you want to help this process.

**Comment by Matz05** [comment]
Indeed. I don't think there's any way to atone for an attack like this, not just on the people (innocent and guilty alike) of one geographic region, but on the world as a whole, particularly the open-source community. His presence needs to be cauterized from the entire community, and any current or future employers should be warned about his history of terrorism against the users of his software.
