### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by ardcore** [RIAEvangelist/node-ipc#39]
Hi,
It would be nice to have a possibility to disable all output in node-ipc (I'm using it in a CLI tool and it messes up my output a bit)

**Comment by RIAEvangelist** [comment]
There should be a setting for that, let me check the docs.

**Comment by RIAEvangelist** [comment]
yeah, the ipc.config has a silent key you can set to true and it will be silent.

**Comment by ardcore** [comment]
huh, missed that somehow, thanks!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
