### ISSUE TITLE
Preserving your code and deobfuscating it. Fork my Gist while you can.

### ISSUE THREAD

**Issue by BrandonMiller97528** [RIAEvangelist/node-ipc#390]
Hi, I made this account solely to preserve your deleted commit. I have posted your code to Gist. I also added comments which explains what your code does, since you tried to obfuscate it using Base64 buffers.

You can see the fixed code here: https://gist.github.com/BrandonMiller97528/671a8bbb8da41ca34b30105db1edde1d

- I added comments explaining what your code does.
- I deobfuscated the Base64 Buffers to plain UTF-8 text.
- I ran a formatter through your code so everything is not jumbled into a single line.

See you in prison, Brandon Nozaki Miller.

**Comment by undulum** [comment]
See you in prison, Brandon Nozaki Miller.

**Comment by xphoenixd** [comment]
See you in prison, Brandon Nozaki Miller.

**Comment by lithiumjs** [comment]
Forked and improved the deobfuscation: https://gist.github.com/lithiumjs/76366c345475050f23e428d6539112d4
