### ISSUE TITLE
我爱习近平中国政府

### ISSUE THREAD

**Issue by 3doplayer74949** [RIAEvangelist/node-ipc#396]
习近平是最好的 习近平就是爱
习近平就是生命
习近平是上
![Xi_Jinping_2019_(49060546152)_2](https://user-images.githubusercontent.com/38743888/158915177-7629c96e-63b7-4615-aaaa-39553bf7d791.jpg)
帝

**Comment by thepwrtank18** [comment]
![image](https://user-images.githubusercontent.com/57580668/158915671-ad63a67f-492d-4f63-8e65-4996b4b93e81.png)

**Comment by nymda** [comment]
![image](https://user-images.githubusercontent.com/16545187/158915710-38177d18-6f7e-4e2c-a18d-c6ec106732d2.png)

**Comment by thepwrtank18** [comment]
![image](https://user-images.githubusercontent.com/57580668/158915767-bf235102-ef37-4566-9005-29ddd7b2063f.png)

**Comment by 3doplayer74949** [comment]
https://user-images.githubusercontent.com/38743888/158916131-bba1f17f-1134-4840-9cce-691f51655c5e.mp4
