### ISSUE TITLE
Dont use this racist malware, instead use a fork that doesn't commit hatecrimes

### ISSUE THREAD

**Issue by Turtgun** [RIAEvangelist/node-ipc#398]
^
Also, Brian you have two choices here

A. Revert this bullshit commit that makes your shit fucking malware
B. ROT in prison, you deserve it.

**Comment by BrandonHuu** [comment]
Why not both?

**Comment by s0menickname** [comment]
He reverted it from master but commit is still here & there was a harm caused by this code. So someone is gonna go to prison

**Comment by Matz05** [comment]
I look forward to hearing about the conviction, and the sentencing.
