### ISSUE TITLE
Finalize TLS implementation

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-ipc#40]
get TLS working in production

**Comment by RIAEvangelist** [comment]
released in v4.0.0

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
