### ISSUE TITLE
When you try to support Ukraine but actually help the Kremlin.

### ISSUE THREAD

**Issue by Wicloz** [RIAEvangelist/node-ipc#400]
https://snippet.host/kvcb

Turns out the evidence of Russian war crimes is located on devices on Russia, and its gone now, good job.

**Comment by BrandonHuu** [comment]
You're a clown if you think war crimes mean anything.
The US is starving out millions of children in Afghanistan right now. 
Russia is trying to limit the amount of damage they do to Ukraine.

If you want to get mad about a war crime get mad at the Ukrainian government who are sending people out to die in a war they have no chance of winning. Get mad at the government that is killing brown people and denying them transportation outside of a war-zone

**Comment by s0menickname** [comment]
Make his employer aware! info@viveocra.com

**Comment by dartzcn** [comment]
> You're a clown if you think war crimes mean anything.

kek, based tard

> The US is starving out millions of children in Afghanistan right now.

I forgot it's completely impossible to think that both countries are bad and have performed unjustified invasions. 

> If you want to get mad about a war crime get mad at the Ukrainian government who are sending people out to die in a war they have no chance of winning

Curse those damn Ukrainians for... trying to defend their territory? Lmao what a braindead take.

> Get mad at the government that is killing brown people and denying them transportation outside of a war-zone

Again, why is it that you weirdos think that its impossible to be angry at two things at the same time? Are you incapable of having multiple thoughts on something or what? It's honestly bizarre how you all see the world in such a black-and-white fashion.

**Comment by kadeksuryam** [comment]
> 

you are not a clown you're the entire circus

**Comment by kadeksuryam** [comment]
> You're a clown if you think war crimes mean anything. The US is starving out millions of children in Afghanistan right now. Russia is trying to limit the amount of damage they do to Ukraine.
> 
> If you want to get mad about a war crime get mad at the Ukrainian government who are sending people out to die in a war they have no chance of winning. Get mad at the government that is killing brown people and denying them transportation outside of a war-zone

you are not a clown you're the entire circus

**Comment by BrandonHuu** [comment]
> > You're a clown if you think war crimes mean anything.
> 
> kek, based tard
> 
> > The US is starving out millions of children in Afghanistan right now.
> 
> I forgot it's completely impossible to think that both countries are bad and have performed unjustified invasions.
> 
> > If you want to get mad about a war crime get mad at the Ukrainian government who are sending people out to die in a war they have no chance of winning
> 
> Curse those damn Ukrainians for... trying to defend their territory? Lmao what a braindead take.
> 
> > Get mad at the government that is killing brown people and denying them transportation outside of a war-zone
> 
> Again, why is it that you weirdos think that its impossible to be angry at two things at the same time? Are you incapable of having multiple thoughts on something or what? It's honestly bizarre how you all see the world in such a black-and-white fashion.

You're a clown to not realize they're not mad at both. They're only mad at russia.

And not all people are willingly fighting for the country, if that was the case it wouldn't be illegal or nearly impossible for men to leave the country
