### ISSUE TITLE
Intentional Malware? Are you serious?  [Gathering Information]

### ISSUE THREAD

**Issue by andrewfer000** [RIAEvangelist/node-ipc#401]
If anyone has been damaged by this malware please leave a comment. I am curious if anyone was here was damaged by this. I have heard news of people who do NOT live in or even by Russia yet their IPs were once registered by Russia and were affected by this malware. The desktop txt file was fine. But destroying data of innocent people and programmers is a sick thing to do. 

This is disgusting and shameful and leaves a huge nasty shit stain on the Open Source community and everything it stands for. Although the MIT itself does not protect against damage done by the software, intentionally placing malware within software that purposely causes damage is. 

I am so lucky that I did not do any Node networking related programming today on my Asia "Virtual Desktop" VPS because I may have gotten fucked. I don't know if anyone is a lawyer or knows one, but if you are planning a class action of any kind I'll be glad to share it with folks who were affected. 

This may take a huge hit on the trustworthiness of small Open Source (and even proprietary) projects, modules, and libraries because it makes it seem like the developer has nothing to loose or gain if potentially thousands of users have no control over current events loose their data. 

For all you know, you may have permanently wiped the only photos of an innocent Ukrainian/Russian relative who was killed in this horrible war and their loved ones will never be able to get it back. It's a sad reality but let's just hope someone more humane and responsible forks and/or takes over the project.

**Comment by NullDev** [comment]
https://github.com/RIAEvangelist/node-ipc/issues/308

**Comment by schlopp** [comment]
I've seen a lot of people talk about how the desktop spam fe was OK. it's not. it was a clear breach of trust and removed all credibility from this module

**Comment by s0menickname** [comment]
Yes, an American NGO got removed an evidence of war crimes commited in Ukraine. #308

**Comment by Stateford** [comment]
@schlopp 
Desktop spam is NOT ok. Imagine you use this a dependency for some electron project and it gets installed on customer machines. It's really bad.

**Comment by AmeliaYeah** [comment]
> I've seen a lot of people talk about how the desktop spam fe was OK. it's not. it was a clear breach of trust and removed all credibility from this module

honestly if he just left it at that then maybe he would've been left off the hook.
but he didn't just stop there. he did something that _actually_ caused (or had the capability to cause) permanent damage

**Comment by s0menickname** [comment]
#408 is another victim

**Comment by jerbear2008** [comment]
Keep this saved, archives are good when the perp of the virus has the ability to delete this.

https://web.archive.org/save/https://github.com/RIAEvangelist/node-ipc/issues/401
