### ISSUE TITLE
give me your liver

### ISSUE THREAD

**Issue by 3doplayer74949** [RIAEvangelist/node-ipc#404]
https://user-images.githubusercontent.com/38743888/158916436-43520f40-8eff-415b-b6e9-e619c5b50ecf.mp4

**Comment by 3doplayer74949** [comment]
![artworks-ILEoKfnCW6HVHXWH-iEN7Vw-t500x500](https://user-images.githubusercontent.com/38743888/158916574-e741f601-6eb0-4585-af03-615fedf457b4.jpg)
mario minestrone

**Comment by HakumenBlazBlue** [comment]
hi mario
