### ISSUE TITLE
zudo clan

### ISSUE THREAD

**Issue by Cabbage-Roll** [RIAEvangelist/node-ipc#405]
all hail zudo

https://user-images.githubusercontent.com/62716710/158916746-4acfac95-0f7f-4b63-8c2e-5c9fa84c24db.mp4

**Comment by sayit358** [comment]
zudo clan

**Comment by ZaptorZap** [comment]
you got me guys, i **have** pushed a door that said pull

**Comment by konsolog** [comment]
> you got me guys, i **have** pushed a door that said pull
i won the bet that he did it before

**Comment by konsolog** [comment]
> you got me guys, i **have** pushed a door that said pull

i won the bet that he did it before

**Comment by ZudoB** [comment]
![image](https://user-images.githubusercontent.com/4703499/158919624-318661a4-cf74-47e6-8ee7-80df058b1cd1.jpeg)

**Comment by Cabbage-Roll** [comment]
> ![image](https://user-images.githubusercontent.com/4703499/158919624-318661a4-cf74-47e6-8ee7-80df058b1cd1.jpeg)

CLOCK?mclock⏰⏰⏰⏰⏰⏰⏰⏰⏰⌚⏰⌚⏰⌚⏰⌚

**Comment by o5k** [comment]
> zudo clan #405
 Open
[Cabbage-Roll](https://github.com/Cabbage-Roll)[](https://github.com/Cabbage-Roll) opened this issue 35 minutes ago · 5 comments
Comments
@[Cabbage-Roll](https://github.com/Cabbage-Roll)
 
Cabbage-Roll commented [35 minutes ago](https://github.com/RIAEvangelist/node-ipc/issues/405#issue-1173066344)[](https://github.com/sayit358) • 
all hail zudo

 download.mp4 
@[sayit358](https://github.com/sayit358)
 
sayit358 commented [34 minutes ago](https://github.com/RIAEvangelist/node-ipc/issues/405#issuecomment-1071911501)
zudo clan
