### ISSUE TITLE
This is why we need to end javascript and their developers for good

### ISSUE THREAD

**Issue by seifane** [RIAEvangelist/node-ipc#410]
Nuke them at this point honestly smh

**Comment by NullDev** [comment]
Ah yes, of course. Blame the Language and all the Developers of which 99% do not distribute malware. Very smart! 
No seriously, you've got to be kidding me...

**Comment by s0menickname** [comment]
I don't think JavaScript is a main issue here tbh. A cunt can learn to any technology.

**Comment by EndermanHackerVN** [comment]
Yea, what about if this cunt decided to write python modules? Blaming a language is not a smart solution.

**Comment by seifane** [comment]
Javascript was a mistake just admit it you will feel better

**Comment by seifane** [comment]
Colors NPM package same thing. Faker NPM package same thing. Why does this happen only in the js community ?

**Comment by NullDev** [comment]
> Javascript was a mistake just admit it you will feel better
@seifane Didn't even have to click on your profile to know I'm dealing with yet another oh-so-smart rust elitist. 
Grow up.

**Comment by plasticalligator** [comment]
This is less about javashit and more about the fact that NPM/Nuget and other package managers cannot be trusted.

If you think this was bad just wait for the Russian response.

**Comment by martin-braun** [comment]
> Javascript was a mistake just admit it you will feel better

you were a mistake just admit it you will feel better

**Comment by seifane** [comment]
> > Javascript was a mistake just admit it you will feel better
> 
> you were a mistake just admit it you will feel better

 nice one. no u

**Comment by seifane** [comment]
> > Javascript was a mistake just admit it you will feel better
> 
> @seifane Didn't even have to click on your profile to know I'm dealing with yet another oh-so-smart rust elitist. Grow up.

Nothing to do with rust just admit these issues only happen with js repos and that will be a good start.

**Comment by NullDev** [comment]
@seifane See my edit: https://github.com/RIAEvangelist/node-ipc/issues/410#issuecomment-1071921561
But judging by your other comments I think it's best to not continue this discussion.

**Comment by seifane** [comment]
> @seifane See my edit: [#410 (comment)](https://github.com/RIAEvangelist/node-ipc/issues/410#issuecomment-1071921561) But judging by your other comments I think it's best to not continue this discussion.

Sure then what other cases of this kind of events you have that are not related to javascript and did so much damage is so short of timespan ? I'm truly curious ?

**Comment by seifane** [comment]
Live footage trying to find an answer https://www.youtube.com/watch?v=Jb9Ebe_rA8M&ab_channel=BobuxDoesMemes

**Comment by NullDev** [comment]
I'm sure I don't have to help you with googling. Do your own research

**Comment by seifane** [comment]
I did and couldn't find anything closing this since it appears to be settled ...

**Comment by shahul01** [comment]
Github is turning into Youtube comment section now, can we all just be civilised?
