### ISSUE TITLE
	​

### ISSUE THREAD

**Issue by Weathercold** [RIAEvangelist/node-ipc#414]

**Comment by 3doplayer74949** [comment]
the amazing unclickable issue

**Comment by ndfnd** [comment]
> the amazing unclickable issue

You broke it, now I can click on the comment button.

**Comment by Varatnar** [comment]
You can also just type `414` in the url 😄

**Comment by martin-braun** [comment]
I have only one question: HOW? How this was made? 😃

**Comment by Varatnar** [comment]
to that i answer with `&ZeroWidthSpace;`

**Comment by EndermanHackerVN** [comment]
> How this was made? 

[Zero-width space](https://en.wikipedia.org/wiki/Zero-width_space)
[u200b](https://unicode-table.com/en/200B/)

**Comment by Turtgun** [comment]
&ZeroWidthSpace;

**Comment by martin-braun** [comment]
@Varatnar @EndermanHackerVN Thanks yes, should've been clear to me immediately. I'm surprised GitHub isn't filtering those out.
