### ISSUE TITLE
The absolute state of javascript.

### ISSUE THREAD

**Issue by bruhgettei** [RIAEvangelist/node-ipc#415]
![1635192200883](https://user-images.githubusercontent.com/93809567/158918265-3394b8ad-a168-4adc-a891-b15edec9c687.png)

**Comment by Exocamp** [comment]
The commit is a subtle joke. The package is called "peacenotwar", where peace and war are opposites, thus wiping the user's hard drive. The author says that the commit was "to protest against the invasion of Ukraine", implying that the citizens of the two countries beginning with "B" and "R" would have turned against Putin, with possibly their entire life's work wiped out even if they protested against the war. So, when Brandon owned the repo, it would have been called "malware".

**Comment by BanementI** [comment]
Javascript was a mistake

**Comment by CoderEx24** [comment]
> Javascript was a mistake

so true
