### ISSUE TITLE
ヒルチャールのお兄さんが病気になった♪…ヒルチャールのお姉さんが看病して♪…ヒルチャールのお兄さんが薬を飲んでも治らない♪

### ISSUE THREAD

**Issue by infernys20** [RIAEvangelist/node-ipc#416]
![image](https://user-images.githubusercontent.com/29486916/158918124-9e4b1027-fac5-4eb3-94b3-46ad082f541b.png)

**Comment by Sliden101** [comment]
hutao

**Comment by aliakseis** [comment]
https://github.com/aliakseis/color-tiles/blob/master/Resources/bad.gif
