### ISSUE TITLE
Hey everyone. Do us all a favour and save the harassment for another time.

### ISSUE THREAD

**Issue by Andre601** [RIAEvangelist/node-ipc#417]
### Disclaimer

I can already seee what this issue here will end up as, but I'll write this anyway, so first, a disclaimer:

I do not know the ins and outs of what happens here. From what I figured out was some malware pushed to production that targets and deletes information stored in Russia and Belarus?
So please do not yell at me if part of this may be incorrect. Thank you.

I also do not support the actions taken here in any way, should they indeed be true as stated. Malware is bad and sharing it is worse, especially if it supports inhumane actions in whatever way.
This still isn't a reason for me to justify harassment and targeted hate towards others. We are all humans. We all make mistakes.

### Please stop the attacks

It's worse enough that we have to face this war in Europe, but now GitHub also becomes a fighting ground?
This place should really stay away from personal attacks against anyone.

With that do I not defend the possible actions taken here by the maintainer(s) nor the damage it caused in the long run.
But attacking individual peoples here - which may not even be at fault at worst - is not the way to go. There are legal measures you can take. You can file a lawsuit, or report the person to either GitHub support or maybe even the authorities, but now doing this manhunt won't bring anyone peace here.

Personally do I give the benefit of the doubt, that the maintainer responsible for this chaos got his account hijacked and abused for this.
If they really are responsible for this, the proof will be found and legal actions certainly be taken.

But we should stop now attacking the people here and spam their issues with all this hate and blatant insulting against others.
Shouldn't open source be a place to welcome others? A place of tolerance? Because looking at the most recent issues can I see that some are only here to let out their hate and nothing more.

So please. Stop this madness now. If you want to write an issue just to insult and attack others, don't. It won't help and if at the end the truth is that the responsible person wasn't liable, you will be guilty of defamation or worse. So consider your choices.

### Wall of Shame

While I usually don't do this, is here a list of issues and issue comments that I find disgusting. Be it because they insult the people behind this software, share hate or similar actions.
This list is by no means a complete one and I do not have any hate towards the creators. I'm just disappointed in them.

*This list is in no chronological order*

- #### #367
  Calling the maintainer a dumbass. Not really mature.

- #### https://github.com/RIAEvangelist/node-ipc/issues/367#issuecomment-1071670809
  Seriously insulting responses. User has posted this in several issues and has been reported to GitHub already.
  Other known cases:
  - https://github.com/RIAEvangelist/node-ipc/issues/369#issuecomment-1071669432

- #### #378
  Directly attacking the guys personal life by telling their boss to fire them for this incident... And then kinda brag about this in public and tells everyone to also do the same.

- #### #382
  If you can find some maturity in this one, show me.

- #### #383
  Calling them the R-word... for attacking a country's citizens I suppose? I'm not that good with words, but isn't racism something towards... you know... A race? Idk about you but I doubt russians are considered a race...

- #### #385
  Just like with #382, if you can find maturity here, be my guest.

- #### #387
  See previous list entry.

- #### #393
  ...I don't think I have to explain this one, do I?

- #### #399
  And when you think stuff can't get any worse...

### Again...

I do not want to defend the person behind this chaos. But at the same time do I not want to see people spamming issues here because they think they do the right thing. You only annoy people and cause not needed drama here.
If you have a problem, report the person, as mentioned and don't just publicly shame him or even encourage others to get their boss to fire them (This is directed at you @s0menickname... Your action here is seriously one of the worst things. Stop it).

**Comment by 3doplayer74949** [comment]
cry harder lol

**Comment by bruhgettei** [comment]
sneed

**Comment by Turtgun** [comment]
sometimes, people deserve to rot, even through petty means.

**Comment by crazymonkyyy** [comment]
>Do us all a favour and save the harassment for another time
no, there will be a news story about some hospital having 4 hours of downtime, how many extra children die when there's no computers near a war zone?

**Comment by niallmurphy-ie** [comment]
Wall of Fame*

**Comment by shybruh** [comment]
> ### Disclaimer
> 
> I can already seee what this issue here will end up as, but I'll write this anyway, so first, a disclaimer:
> 
> I do not know the ins and outs of what happens here. From what I figured out was some malware pushed to production that targets and deletes information stored in Russia and Belarus?
> So please do not yell at me if part of this may be incorrect. Thank you.
> 
> I also do not support the actions taken here in any way, should they indeed be true as stated. Malware is bad and sharing it is worse, especially if it supports inhumane actions in whatever way.
> This still isn't a reason for me to justify harassment and targeted hate towards others. We are all humans. We all make mistakes.
> 
> ### Please stop the attacks
> 
> It's worse enough that we have to face this war in Europe, but now GitHub also becomes a fighting ground?
> This place should really stay away from personal attacks against anyone.
> 
> With that do I not defend the possible actions taken here by the maintainer(s) nor the damage it caused in the long run.
> But attacking individual peoples here - which may not even be at fault at worst - is not the way to go. There are legal measures you can take. You can file a lawsuit, or report the person to either GitHub support or maybe even the authorities, but now doing this manhunt won't bring anyone peace here.
> 
> Personally do I give the benefit of the doubt, that the maintainer responsible for this chaos got his account hijacked and abused for this.
> If they really are responsible for this, the proof will be found and legal actions certainly be taken.
> 
> But we should stop now attacking the people here and spam their issues with all this hate and blatant insulting against others.
> Shouldn't open source be a place to welcome others? A place of tolerance? Because looking at the most recent issues can I see that some are only here to let out their hate and nothing more.
> 
> So please. Stop this madness now. If you want to write an issue just to insult and attack others, don't. It won't help and if at the end the truth is that the responsible person wasn't liable, you will be guilty of defamation or worse. So consider your choices.
> 
> ### Wall of Shame
> 
> While I usually don't do this, is here a list of issues and issue comments that I find disgusting. Be it because they insult the people behind this software, share hate or similar actions.
> This list is by no means a complete one and I do not have any hate towards the creators. I'm just disappointed in them.
> 
> *This list is in no chronological order*
> 
> - #### #367
>   Calling the maintainer a dumbass. Not really mature.
> 
> - #### https://github.com/RIAEvangelist/node-ipc/issues/367#issuecomment-1071670809
>   Seriously insulting responses. User has posted this in several issues and has been reported to GitHub already.
>   Other known cases:
>   - https://github.com/RIAEvangelist/node-ipc/issues/369#issuecomment-1071669432
> 
> - #### #378
>   Directly attacking the guys personal life by telling their boss to fire them for this incident... And then kinda brag about this in public and tells everyone to also do the same.
> 
> - #### #382
>   If you can find some maturity in this one, show me.
> 
> - #### #383
>   Calling them the R-word... for attacking a country's citizens I suppose? I'm not that good with words, but isn't racism something towards... you know... A race? Idk about you but I doubt russians are considered a race...
> 
> - #### #385
>   Just like with #382, if you can find maturity here, be my guest.
> 
> - #### #387
>   See previous list entry.
> 
> - #### #393
>   ...I don't think I have to explain this one, do I?
> 
> - #### #399
>   And when you think stuff can't get any worse...
> 
> ### Again...
> 
> I do not want to defend the person behind this chaos. But at the same time do I not want to see people spamming issues here because they think they do the right thing. You only annoy people and cause not needed drama here.
> If you have a problem, report the person, as mentioned and don't just publicly shame him or even encourage others to get their boss to fire them (This is directed at you @s0menickname... Your action here is seriously one of the worst things. Stop it).

He needs to get clowned on 100,% for this bullshit 
Idk what your smoking but nobody likes someone who releases malware, esp something like this when it's used so much. Sure clowns will clown but yeah your just thinking too much about it. 
And about the his work, he definitely should get fired and his workplace know of his actions. No if and or buts.

**Comment by 3doplayer74949** [comment]
@Andre601 imagine defending warcrime record deletion

**Comment by Hexawolf** [comment]
But why would these crime evidences be collected in Russia or Belaruss? It's self-contradictory.

**Comment by s0menickname** [comment]
> Directly attacking the guys personal life by telling their boss to fire them for this incident... And then kinda brag about this in public and tells everyone to also do the same.

Go cry about it. Brandon deserves imprisonment for distribution of malicious software, nothing wrong with cancelling him.

**Comment by socialretard** [comment]
Cope

**Comment by Sneethe** [comment]
sneeth and dilate

**Comment by Sasytoremember** [comment]
> ### Disclaimer
> I can already seee what this issue here will end up as, but I'll write this anyway, so first, a disclaimer:
> 
> I do not know the ins and outs of what happens here. From what I figured out was some malware pushed to production that targets and deletes information stored in Russia and Belarus? So please do not yell at me if part of this may be incorrect. Thank you.
> 
> I also do not support the actions taken here in any way, should they indeed be true as stated. Malware is bad and sharing it is worse, especially if it supports inhumane actions in whatever way. This still isn't a reason for me to justify harassment and targeted hate towards others. We are all humans. We all make mistakes.
> 
> ### Please stop the attacks
> It's worse enough that we have to face this war in Europe, but now GitHub also becomes a fighting ground? This place should really stay away from personal attacks against anyone.
> 
> With that do I not defend the possible actions taken here by the maintainer(s) nor the damage it caused in the long run. But attacking individual peoples here - which may not even be at fault at worst - is not the way to go. There are legal measures you can take. You can file a lawsuit, or report the person to either GitHub support or maybe even the authorities, but now doing this manhunt won't bring anyone peace here.
> 
> Personally do I give the benefit of the doubt, that the maintainer responsible for this chaos got his account hijacked and abused for this. If they really are responsible for this, the proof will be found and legal actions certainly be taken.
> 
> But we should stop now attacking the people here and spam their issues with all this hate and blatant insulting against others. Shouldn't open source be a place to welcome others? A place of tolerance? Because looking at the most recent issues can I see that some are only here to let out their hate and nothing more.
> 
> So please. Stop this madness now. If you want to write an issue just to insult and attack others, don't. It won't help and if at the end the truth is that the responsible person wasn't liable, you will be guilty of defamation or worse. So consider your choices.
> 
> ### Wall of Shame
> While I usually don't do this, is here a list of issues and issue comments that I find disgusting. Be it because they insult the people behind this software, share hate or similar actions. This list is by no means a complete one and I do not have any hate towards the creators. I'm just disappointed in them.
> 
> _This list is in no chronological order_
> 
> * #### [sneed  #367](https://github.com/RIAEvangelist/node-ipc/issues/367)
>   Calling the maintainer a dumbass. Not really mature.
> * #### [sneed  #367 (comment)](https://github.com/RIAEvangelist/node-ipc/issues/367#issuecomment-1071670809)
>   Seriously insulting responses. User has posted this in several issues and has been reported to GitHub already.
>   Other known cases:
>   
>   * [- #369 (comment)](https://github.com/RIAEvangelist/node-ipc/issues/369#issuecomment-1071669432)
> * #### [You better find a new job #378](https://github.com/RIAEvangelist/node-ipc/issues/378)
>   Directly attacking the guys personal life by telling their boss to fire them for this incident... And then kinda brag about this in public and tells everyone to also do the same.
> * #### [goatse  #382](https://github.com/RIAEvangelist/node-ipc/issues/382)
>   If you can find some maturity in this one, show me.
> * #### [This is so racist. #383](https://github.com/RIAEvangelist/node-ipc/issues/383)
>   Calling them the R-word... for attacking a country's citizens I suppose? I'm not that good with words, but isn't racism something towards... you know... A race? Idk about you but I doubt russians are considered a race...
> * #### [You are a terrible person. #385](https://github.com/RIAEvangelist/node-ipc/issues/385)
>   Just like with [goatse  #382](https://github.com/RIAEvangelist/node-ipc/issues/382), if you can find maturity here, be my guest.
> * #### [Bug: Penis size shrunk after installation  #387](https://github.com/RIAEvangelist/node-ipc/issues/387)
>   See previous list entry.
> * #### [You are smoking PENIS, COCK and WEED in a circle  #393](https://github.com/RIAEvangelist/node-ipc/issues/393)
>   ...I don't think I have to explain this one, do I?
> * #### [you smell of poopoo peepee #399](https://github.com/RIAEvangelist/node-ipc/issues/399)
>   And when you think stuff can't get any worse...
> 
> ### Again...
> I do not want to defend the person behind this chaos. But at the same time do I not want to see people spamming issues here because they think they do the right thing. You only annoy people and cause not needed drama here. If you have a problem, report the person, as mentioned and don't just publicly shame him or even encourage others to get their boss to fire them (This is directed at you @s0menickname... Your action here is seriously one of the worst things. Stop it).

So  you allow Russian childrens hospitals to shut down and possibly kill thousands of children? Stop smoking heroin.

**Comment by undulum** [comment]
Intentionally obfuscating code isn't a mistake. He's a deranged criminal.

**Comment by 5GameMaker** [comment]
We do not tolerate virus makers

**Comment by BrandonHuu** [comment]
> * #### [This is so racist. #383](https://github.com/RIAEvangelist/node-ipc/issues/383)
>   Calling them the R-word... for attacking a country's citizens I suppose? I'm not that good with words, but isn't racism 

How to spot a fellow racist. 
> They say R-word instead of racist

Xenophobia & Racism are pretty much the same thing. Attacking someone for where & how they were born.

Maybe you can discuss this in your next Klan meeting

**Comment by coderboy14** [comment]
They absolutely deserve this. They intentionally and willingly spread malware. They already ruined their reputation. Hopefully they will face repercussions, from Github, NPM, their job, and perhaps legally. They didn't target the Russian government in their shoddy attempt at hacktivism. They targeted private citizens, not just Russians government officials, but anyone who happened to use this library.

I think it fitting to discuss our absolute distain for the individual and their actions here, as this is the GitHub for their malicious code. They should see how badly the screwed up, and at least personally, their reputation is irreversibly damaged. I can't trust any code with their name on it again.

**Comment by undulum** [comment]
He's not arrested yet? No? Then shut up.

**Comment by BanementI** [comment]
> * #### [sneed  #367](https://github.com/RIAEvangelist/node-ipc/issues/367)
>       Calling the maintainer a dumbass. Not really mature.

hey look its me :)
do you think he isnt a dumbass? i could've called him a n

**Comment by aphix** [comment]
Are there any projects out there which blacklist any modules (or dependencies) if they are touched by certain maintainers/keys?

If not, I think this might be a good time to start one. It should audit the full tree (and ideally also commit history of all modules in that tree) upon any install or update, and ensure that developers like this are barred from any further exposure to OSS/FOSS users. No need to be JS-specific, since this could happen in any language.

**Comment by novialriptide** [comment]
![cry-harder-cry-about-it](https://user-images.githubusercontent.com/35881688/158947214-91ce4b67-78f8-4172-b133-146f1f20e09b.gif)

**Comment by Belvix** [comment]
> 

bruh

**Comment by schlopp** [comment]
I stand by my "PENIS, COCK and WEED" comment

**Comment by schlopp** [comment]
> He needs to get clowned on 100,% for this bullshit
> Idk what your smoking but nobody likes someone who releases malware, esp something like this when it's used so much.
>

@shybruh He's smoking the PENIS, COCK, and WEED from earlier.

**Comment by PrivateGER** [comment]
Malware developers and malware spreaders deserve zero quarter. This should be a core principle.

Anything else is ridiculous. The account clearly wasn't hijacked.
