### ISSUE TITLE
Your own fault

### ISSUE THREAD

**Issue by taago27** [RIAEvangelist/node-ipc#419]
Read the [license](https://github.com/RIAEvangelist/node-ipc/blob/master/licence). Here's a TL;DR in case you're mentally unable to find it (click on the blue hyperlink):
```
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
```
While it might've not been the smartest move or implementation, I agree, he has his ass covered unless some bigwig really wants to drill him hard for the "unstated functionality". He has never forced anyone to download it in the first place. The problem with most of the OSS is... by using it YOU take the risk.

**Comment by s0menickname** [comment]
Creating and spreading malicious software is a criminal offense in most countries, including the United States. License doesn't matter.

**Comment by peepopoggers** [comment]
^ If that was the case, all malware would be legal :laughing:

**Comment by greenmancode** [comment]
> He has never forced anyone to download it in the first place.

You realize this package is included as a dependency in other packages, right? Even if you somehow avoided using every package that depends on this package, you would also have to know which proprietary software you use has this package as a dependency (i.e. Unity Hub).

This was a really stupid move considering how this is just going to harm many developers and users, and the man responsible for this deserves jail time.

**Comment by dartzcn** [comment]
Yeah... keep studying for your law degree my friend, you're still a ways off if you think a contract/software license magically exempts you from being criminally charged.

**Comment by AreaDenial** [comment]
In the words of someone in another issue: "Gonna add an MIT license and a copy of the source code to all my ransomware so it becomes legal 'free software' and not malware. You consented to this by downloading my spam email attachment."
