### ISSUE TITLE
Clarify in the README maxRetries vs stopRetrying

### ISSUE THREAD

**Issue by halt-hammerzeit** [RIAEvangelist/node-ipc#42]
It's not clear from the documentation how `maxRetries` is different from `stopRetrying`.
My guess is `maxRetries = -stopRetrying`

**Comment by RIAEvangelist** [comment]
legit question, just looked at documentation, it says they are basically the same, I will take a look at clarifying or removing one from documentation.

**Comment by RIAEvangelist** [comment]
so, the answer to this question is that at any point you can set stopRetrying to true in real time and it will immediately stop retrying reguardless of the maxRetrys are. This is useful in many scenarios. you can then set it back to false and reconnect using the maxRetry count. This is helpful with critical failure paths or highly multi process communication.

Needs to be added to documentation. @MaybeRex you want this one?

**Comment by halt-hammerzeit** [comment]
@RIAEvangelist by the way, your module inspired me to dive into that "streams" thing and write my own TCP-only implementation
https://github.com/halt-hammerzeit/webapp/blob/master/code/common/tcp.js

**Comment by RIAEvangelist** [comment]
@halt-hammerzeit  cool.

You might also take a look at my [js-message](https://www.npmjs.com/package/js-message) module.

It helps a lot for normalizing messages and having JSON available.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
