### ISSUE TITLE
Let's make Brandon's employer aware

### ISSUE THREAD

**Issue by s0menickname** [RIAEvangelist/node-ipc#420]
Guys, that is horrifying. I have emailed his employer about the incident, particularly damage to an NGO (#308) which includes removal of evidence of war crimes commited in Ukraine.

Let's do it together: info@viveocra.com

**Comment by stevensmedia** [comment]
Yes, let's let them know that we support him.

Слава Україні! 🇺🇦

**Comment by Hexawolf** [comment]
But why would these crime evidences be collected in Russia or Belaruss? It's self-contradictory.

**Comment by Turtgun** [comment]
> Yes, let's let them know that we support him.
no
> Слава Україні! ukraine
yes

**Comment by s0menickname** [comment]
> But why would these crime evidences be collected in Russia or Belaruss? It's self-contradictory.

@Hexawolf, are you kidding me? Evidence is collected in places where it exists.

**Comment by Matz05** [comment]
Make sure his employers (and any potential employers in the future) know just what he did, and presumably remains willing to do to people who trust him any time he takes up a cause.

**Comment by Turtgun** [comment]
> But why would these crime evidences be collected in Russia or Belarus? It's self-contradictory.

@Hexawolf, just connecting to a Russian VPN is all that it takes to have your data wiped by this package. Y'know VPN, something that a company that wants to keep its employees private would most likely do. You are self-contradictory.
