### ISSUE TITLE
Protest-ware.

### ISSUE THREAD

**Issue by JackCrispy** [RIAEvangelist/node-ipc#421]
Sat here watching someone with general skill and drive in the development community, ruining their career.
It's **disgusting** to protest against Russian in the form of harming everyday developers who **depend** on your module.

![image](https://user-images.githubusercontent.com/34707863/158919011-a06f82b7-bfa0-444c-b455-caaeb8318ef4.png)

Then cover it up by deleting comments and closing all the issues relating to this. If you surely want peace, maybe do not recursively overwrite every innocent person who is using a Russian IP to a love heart.

You have ruined all the reputation that you built, and you will not land a future job, and I assume that people will be looking into you trying to harm your current job status.

See if any packages you use are depends of nodeipc https://github.com/zlw9991/node-ipc-dependencies-list

**Comment by Hexawolf** [comment]
@RIAEvangelist I am eternally grateful for your action. Even if there was collateral damage... It's just overwhelming madness that people feel entitled to sacrifice a whole nation of Ukraine for the sake of peace, and it is absolutely crazy that some people would still use Russian/Belarussian servers and services after their invasion.

**Comment by JackCrispy** [comment]
Just gonna leave this here... https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=502.&lawCode=PEN

**Evan Checklist**
- [x] Ruin Career 
- [ ] Federal Prison
