### ISSUE TITLE
Instead of shoving hearts up peoples hard drives, how bout you shove those hearts up your ass?

### ISSUE THREAD

**Issue by Sasytoremember** [RIAEvangelist/node-ipc#424]
Just saying that before you get sued.

**Comment by Nightowl2007W** [comment]
lol

**Comment by y0shin** [comment]
Updating code without auditing it, while knowing the licensing is entirely on the person who runs it

**Comment by BrandonHuu** [comment]
> Updating code without auditing it, while knowing the licensing is entirely on the person who runs it

You are a baboon, people got their files deleted because they updated unity hub.

And a license doesn't make malware legal. You can't murder someone and skin them alive just because they agreed to it in a contract

**Comment by y0shin** [comment]
> people got their files deleted because they updated unity hub.

Well thats on them for not looking at what they were updating

**Comment by BrandonHuu** [comment]
> > people got their files deleted because they updated unity hub.
> 
> Well thats on them for not looking at what they were updating

You have to be a baboon. Do you look at what you're updating every time you start google chrome?
Do you look through every single dependency in a program that probably has over 10 million lines?

Stop victim blaming you back water orangutan

**Comment by y0shin** [comment]
Yes I do check what I'm updating, that is basic security. I have nothing set to auto-update for this very reason. If the general consensus is that everything is safe then I update manually. I don't have time to audit every single line of code but the people this attack is aimed at certainly can, though I do agree the general public getting hit by this ain't great.

**Comment by BrandonHuu** [comment]
> Yes I do check what I'm updating, that is basic security. I have nothing set to auto-update for this very reason. If the general consensus is that everything is safe then I update manually. I don't have time to audit every single line of code but the people this attack is aimed at certainly can, though I do agree the general public getting hit by this ain't great.

It was aimed at the general public...
