### ISSUE TITLE
I am grateful

### ISSUE THREAD

**Issue by Hexawolf** [RIAEvangelist/node-ipc#425]
I am eternally grateful for your action. Even if there was collateral damage... It's just overwhelming madness that people feel entitled to sacrifice a whole nation of Ukraine for the sake of peace, "so as to avoid WW3" - and it is absolutely crazy that some people would still use Russian/Belarussian servers and services after that.

**Comment by sayit358** [comment]
> it is absolutely crazy that some people would still use Russian/Belarussian servers and services after that

so their hard drives deserve being wiped?

**Comment by EndermanHackerVN** [comment]
> and it is absolutely crazy that some people would still use Russian/Belarussian servers and services after that.

Perfect example of a person who blames entire country based on the leader's action.

**Comment by Sasytoremember** [comment]
two words; fuck you

**Comment by shybruh** [comment]
Guys it's bait pls don't give the furry more attention 💀💀

**Comment by HakumenBlazBlue** [comment]
https://user-images.githubusercontent.com/101847811/158920465-e64e539b-6484-4734-96e4-43cf1acaab2e.mp4

**Comment by sayit358** [comment]
https://user-images.githubusercontent.com/41551891/158920628-13756352-5a6b-428d-a31b-caec9ea52833.mp4

**Comment by Cabbage-Roll** [comment]
Uploading funny_fish.mp4…

**Comment by Sasytoremember** [comment]
put some spicy hot sauce on your tiny mushroom thing in the middle-bottom of you, and suck it.

**Comment by artur6768** [comment]
> I am eternally grateful for your action. Even if there was collateral damage... It's just overwhelming madness that people feel entitled to sacrifice a whole nation of Ukraine for the sake of peace, "so as to avoid WW3" - and it is absolutely crazy that some people would still use Russian/Belarussian servers and services after that.

So, lemme get straight, do you think it's fair to many innocent users get their PCs cucked up? That's very selfish 


also:
https://user-images.githubusercontent.com/96083801/158924032-a76fc6d1-290c-4840-99f3-f9a3c8b4493c.mp4
