### ISSUE TITLE
this issue page is royally funny wouldn't you say chaps 

### ISSUE THREAD

**Issue by 3doplayer74949** [RIAEvangelist/node-ipc#428]
https://user-images.githubusercontent.com/38743888/158920390-031ba2c2-81f2-488f-969e-b1a082a1f037.mp4

**Comment by 3doplayer74949** [comment]
![clash-royale-emotes](https://user-images.githubusercontent.com/38743888/158920451-68fa7571-0ee5-4e24-8a8a-5cc1fc2e8abb.gif)

**Comment by HakumenBlazBlue** [comment]
![158920451-68fa7571-0ee5-4e24-8a8a-5cc1fc2e8abb](https://user-images.githubusercontent.com/101847811/158920532-85c7ddf9-ff8f-45e2-a7eb-677412e1500a.gif)

**Comment by xXCoolinXx** [comment]
Hee hee ha ha 
![image](https://user-images.githubusercontent.com/64617841/158920580-be7f3400-ba34-4d15-be4c-7a55fd46a689.png)

**Comment by fossdemon** [comment]
![](https://user-images.githubusercontent.com/38743888/158920451-68fa7571-0ee5-4e24-8a8a-5cc1fc2e8abb.gif)

**Comment by Turtgun** [comment]
https://user-images.githubusercontent.com/38743888/158920451-68fa7571-0ee5-4e24-8a8a-5cc1fc2e8abb.gif

**Comment by Turtgun** [comment]
![image](https://user-images.githubusercontent.com/84696091/158921602-1b951577-f0a7-4bb8-b86c-8fa973e14b06.png)

**Comment by Turtgun** [comment]
![](https://user-images.githubusercontent.com/38743888/158920451-68fa7571-0ee5-4e24-8a8a-5cc1fc2e8abb.gif)

**Comment by AreaDenial** [comment]
Hee hee ha ha
