### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by matthiasg** [RIAEvangelist/node-ipc#43]
I am investigating node-ipc to replace our current axon and zeromq based mechanisms. is there a standardized benchmark script anywhere ? e.g time to send x packages at y bytes per message for increasing y (similar to zeromq perf tests). This is helpful in evaluating base line performance (throughput and latency) before application overhead.

**Comment by RIAEvangelist** [comment]
No, but the library should be blazingly fast, we use it for real time critical software.

If you write such a benchmark, please submit it as a pull request! I would love to see it.

**Comment by matthiasg** [comment]
@RIAEvangelist thanks for the feedback, that sounds promising .. i will start evaluation then, if i do create tests i will certainly make them available

**Comment by RIAEvangelist** [comment]
@matthiasg Thanks!

**Comment by dimichgh** [comment]
@matthiasg why would you want to switch from zmq to node-ipc?
have you tried to compare?

**Comment by matthiasg** [comment]
@dimichgh actually we stayed and invested further into zmq. I was hoping for an all JavaScript ipc method to avoid compiling dependencies.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
