### ISSUE TITLE
HELP! This package deleted my special homework folder!

### ISSUE THREAD

**Issue by xXCoolinXx** [RIAEvangelist/node-ipc#430]
More than a terabyte gone 
![image](https://user-images.githubusercontent.com/64617841/158920889-181df736-e331-4e8d-ab03-9591c34d64cc.png)

**Comment by fossdemon** [comment]
![FH5GIp0VEAAtEU6](https://user-images.githubusercontent.com/101847732/158921119-ba7fa786-251e-481a-9438-8cd3dd398c16.jpeg)

**Comment by jerbear2008** [comment]
yep, the dev/malware perpetrator did this.
