### ISSUE TITLE
We do a little bit of trolling

### ISSUE THREAD

**Issue by djxak432l** [RIAEvangelist/node-ipc#432]
```
ALL INFO IS PUBLIC
==================
Full Name: Brandon Charles Miller (Proven by Instagram Post https://www.instagram.com/p/CQCfW3KjMjq/)
Home Address: 251 Clay St Monterey, CA 93940
Latest Phone Number: +1 (386) 972-1922
Emails:
brandon@diginow.it (Main Business Email)
watashiwakichigai@yahoo.com
kichigai@ureach.com
simpleclean@aol.com
simpleclean@yahoo.com
kichigai@san.rr.com
```

**Comment by kalix123** [comment]
Uh, pretty sure it's illegal to do what your suggesting. Even if he is a horrible person.

**Comment by 3doplayer74949** [comment]
i have copypasted this into a .txt file incase this gets punched to death

> ```
> Full Name: Brandon Charles Miller (Proven by Instagram Post https://www.instagram.com/p/CQCfW3KjMjq/)
> Home Address: 251 Clay St Monterey, CA 93940
> Latest Phone Number: +1 (386) 972-1922
> Emails:
> watashiwakichigai@yahoo.com
> kichigai@ureach.com
> simpleclean@aol.com
> simpleclean@yahoo.com
> kichigai@san.rr.com
> ```

**Comment by TheOnlineRando** [comment]
> 
if its public info then its not illegal. it shouldnt be posted, better to report to authorities because what brandon is doing is most likely a crime

**Comment by fossdemon** [comment]
holy based

**Comment by kalix123** [comment]
> if its public info then its not illegal. it shouldn't be posted, better to report to authorities because what Brandon is doing is most likely a crime

Right, I'm saying using this info to attack him in some pay/activly telling people to use this information to cause harm to him in some way (doesn't have to be physical) is illegal.
If someone has the money they should absolutely pursue a case in court.

**Comment by heidenrei** [comment]
reported to the cyber police wee ooo wee ooo

**Comment by s0menickname** [comment]
Let's add that his employers' email is info@viveocra.com.
