### ISSUE TITLE
иди нахуй

### ISSUE THREAD

**Issue by 1over137** [RIAEvangelist/node-ipc#436]

**Comment by Hexawolf** [comment]
Ты забыл добавить "Русский военный корабль"

**Comment by cloud65** [comment]
I support.
This schizophrenic disgraced the entire community

Поддерживаю.
Этот шизик обосрал весь open-source

**Comment by Steve-Brule** [comment]
> Ты забыл добавить "Русский военный корабль"

Американская npm библиотека, иди нахуй

Брэндон Нозаки Миллер, иди нахуй.

**Comment by mrpavlikov** [comment]
На хуй пишется раздельно всегда. Поправьте, пожалуйста.

**Comment by Steve-Brule** [comment]
> На хуй пишется раздельно всегда. Поправьте, пожалуйста.

https://en.m.wiktionary.org/wiki/%D0%BD%D0%B0%D1%85%D1%83%D0%B9

**Comment by mrpavlikov** [comment]
> > На хуй пишется раздельно всегда. Поправьте, пожалуйста.
> 
> https://en.wiktionary.org/wiki/%D0%BD%D0%B0%D1%85%D1%83%D0%B9

Это ошибка.
