### ISSUE TITLE
would you please sign my petition

### ISSUE THREAD

**Issue by 3doplayer74949** [RIAEvangelist/node-ipc#441]
![image](https://user-images.githubusercontent.com/38743888/158922035-3af65a85-b397-4f6b-8a40-aa8d0566972e.png)

**Comment by moronwithinternet** [comment]
no way you freaking pinko!

**Comment by BanementI** [comment]
Are you gonna sign this or will it be your surviving family members?

**Comment by tymondouglas** [comment]
Okay, I guess that sounds pretty good
