### ISSUE TITLE
your favourite song!

### ISSUE THREAD

**Issue by moronwithinternet** [RIAEvangelist/node-ipc#442]
`My neighbors ask me why I'm limping down the way`
`And who that fellow was who came by yesterday`
`I quickly turn my face before I start to blush`
`'Cause frankly there is nothing I can say`

`I've always had a thing for pushing the extremes`
`And I've just got a thing you won't find in the magazines`
`This molded silicone has got me begging please`
`Give me more of what I really need`

`[Chorus 1]`
`'Cause there is no cock like horse cock`
`Send your asshole into shock`
`You need horse cock of course-cock`
`Grab the lube and slam the day away`

`[Verse 2]`
`[My shaft is quivering, my balls are turning blue, and`
`I think of drinking in a foot or even two`
`My favorite stallion that I keep in my top drawer`
`Slip it in and out be dripping goo`

`[Chorus 2]`
`As I take more cock, horse cock`
`Shut the door and turn the lock`
`Is your cock a horse cock?`
`[You will never hear me saying neigh!`
`'Cause there is no cock like horse cock`
`Rub my dick inside a sock`
`Don't stop now, horse cock`
`Stretch out my insides and make me pray`

`My lovely horse cock, horse cock`
`[scatting]`
`Horse cock, horse cock`
`[scatting]`

**Comment by bush-did-711** [comment]
rofl
