### ISSUE TITLE
This has gotten out of hand

### ISSUE THREAD

**Issue by kalix123** [RIAEvangelist/node-ipc#445]
Obviously what he's done is horrible. And the commenting on the malware and how wrong it was is good. But you guys are full on trying to ruin this guys entire life. Which, if you support cancel culture, then sure your just cancelling someone. But if you don't support it, then that applies to everyone.

While what he did was extremely messed up and wrong, also very likely illegal. He is still a person. The people who are advocating using his phone number and home address to troll are also part of the problem. You guys also give the FOSS community a bad name.

The issue section alone will be enough to stop people from using this project. And it's already been removed as a dependency from many projects. If you have further problems with him. Sue him, or do some of that lawyer shit.

But attacking him on a personal level is just making the situation worse.

**Comment by 3doplayer74949** [comment]
cry about it

**Comment by Sasytoremember** [comment]
But why did he shrink my cock?

**Comment by undulum** [comment]
It's not over until he's in federal custody.

**Comment by xXCoolinXx** [comment]
For all my homies that ain't convinced: 
There is such a thing as too much trolling.

**Comment by fossdemon** [comment]
https://user-images.githubusercontent.com/101847732/158922526-34bea03a-5ed8-463e-a06f-d6f4fe82b8b0.mp4

**Comment by kalix123** [comment]
Idk why I'm getting all this hate. I absolutely should be locked away and never allowed to touch a computer again. He ruined potentially millions of peoples lives and likely terabytes of data loss. 

A first goal would be getting the package removed from npm as people are still downloading it.

**Comment by Ashdemai** [comment]
No, he needs to go to jail. You yourself said what he did is illegal. Where are his repercussions?

**Comment by BrandonHuu** [comment]
> you guys are full on trying to ruin this guys entire life. 

Yes, that is the goal

**Comment by gentue** [comment]
> I absolutely should be locked away and never allowed to touch a computer again.

Now you're talking sense

**Comment by s0menickname** [comment]
Cope

**Comment by SansCipher** [comment]
Play stupid games

**Comment by Ashdemai** [comment]
Yeah close it, like you should close your mouth.
