### ISSUE TITLE
Client does not fire disconnect event if retries remaining is 0

### ISSUE THREAD

**Issue by nileshprasad** [RIAEvangelist/node-ipc#45]
client.trigger('disconnect');

should be in the statement that destroys the socket.

**Comment by RIAEvangelist** [comment]
fixed by PR #52

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
