### ISSUE TITLE
javascript is the literal fast food of programming languages 

### ISSUE THREAD

**Issue by 3doplayer74949** [RIAEvangelist/node-ipc#450]
also most the programmers of js are the most naive little shits i have ever seen

**Comment by artur6768** [comment]
JS sucks, PHP is a lot better

**Comment by bruhgettei** [comment]
so true!

**Comment by SoulRepo** [comment]
based, javascript expects you to do lazy programming instead of optimization

**Comment by luqaska** [comment]
> JS sucks, PHP is a lot better

As a mainly PHP programmer, I have to say: I think Python is better

**Comment by Mango0x45** [comment]
The fact that you can access an object attribute in JS that doesn't exist and not have your interpreter crash is horrible.  I once spent hours debugging a program only to find that I had a typo in an attribute name.

**Comment by aequabit** [comment]
![](https://i.imgur.com/WDIlF67.png)

**Comment by arunanshub** [comment]
> > JS sucks, PHP is a lot better
> 
> As a mainly PHP programmer, I have to say: I think Python is better
> 
> Easier to add/make modules + more secure web dev = based

As a Python developer, I believe C is more based.

You can always dereferrrrrrrrrrr

\[SEGFAULT\]

**Comment by CoderEx24** [comment]
Javascript is ass, Rust is the best (although I only learned it very recently)
