### ISSUE TITLE
L github repo

### ISSUE THREAD

**Issue by Yoshii64** [RIAEvangelist/node-ipc#451]
Fat L for this gh repo

**Comment by 3doplayer74949** [comment]
how long til this entire repo is deleted?

**Comment by Yoshii64** [comment]
> how long til this entire repo is deleted?

Idk. Hope soon. Just enough though so I can shit on this gh repo more

**Comment by moronwithinternet** [comment]
> 

hopefully someone can clone it without the malware before its taken down. honestly i hope its soon

**Comment by Yoshii64** [comment]
> > 
> 
> hopefully someone can clone it without the malware before its taken down. honestly i hope its soon

Indeed. Just beating the shit out of them now. Because. No bitches?
