### ISSUE TITLE
No bitches?

### ISSUE THREAD

**Issue by Yoshii64** [RIAEvangelist/node-ipc#452]
People who make viruses dont get bitches

**Comment by 3doplayer74949** [comment]
![cover2](https://user-images.githubusercontent.com/38743888/158923298-408547ae-12e6-4c9f-b79b-3efcbf014d54.jpg)

**Comment by Yoshii64** [comment]
![image](https://user-images.githubusercontent.com/100977835/158923875-874608b4-2952-4d1b-b6b2-c7302bcd751a.png)

**Comment by moronwithinternet** [comment]
no wenches?

**Comment by Lisenaaaa** [comment]
![image](https://user-images.githubusercontent.com/69115669/158935136-77e88fdc-71b6-4579-a225-884cf51e21df.png)
