### ISSUE TITLE
what the frick

### ISSUE THREAD

**Issue by ghost** [RIAEvangelist/node-ipc#454]
how isnt this guy banned yet? He created a big trust issue on the whole npm system and javascript

**Comment by y0shin** [comment]
its hilarious
shoulda audited your code

**Comment by BrandonHuu** [comment]
> its hilarious shoulda audited your code

Rape apologist behavior right here

**Comment by aequabit** [comment]
> > its hilarious shoulda audited your code
> 
> Rape apologist behavior right here
No, you're just lazy and not aware of how easy software development has become. And maybe you should read the license, I know you haven't before.

**Comment by xKiraiChan** [comment]
> its hilarious
> shoulda audited your code

dude, I'm just trying to use unity3d, this is bigger than just lazy js devs

**Comment by BrandonHuu** [comment]
> > > its hilarious shoulda audited your code
> > 
> > 
> > Rape apologist behavior right here
> > No, you're just lazy and not aware of how easy software development has become. And maybe you should read the license, I know you haven't before.

Did you know people had their files deleted for updating Unity Hub

**Comment by xKiraiChan** [comment]
> Did you know people had their files deleted for updating Unity Hub the client for Unity 3D game engine.

> It's not just the people who directly use the package that are being affected.

> Again, rape apologist behavior coming from this psychos

what do you expect from an entitled, subpar C programmer, they think they can check every single instruction in a 372 MB application for malware
:trollface:

**Comment by aequabit** [comment]
> It's also insane to think that everyone is going to go through every single line in god-zillion line project

No, but the person at Unity that pulled the latest version should have went over the diff.
