### ISSUE TITLE
The code on this repo doesn't contain/call the malware right?

### ISSUE THREAD

**Issue by luqaska** [RIAEvangelist/node-ipc#457]
Right?

**Comment by s0menickname** [comment]
He reverted the last commit in branch but it is still in the repo and caused real harm.

**Comment by luqaska** [comment]
So, if I wanted to download the zip of the master, that wouldn't be there?

**Comment by 5GameMaker** [comment]
I haven't found anything just yet, still looking thro every file tho

**Comment by 5GameMaker** [comment]
K it should be safe
