### ISSUE TITLE
I wonder what his boss has to say about it

### ISSUE THREAD

**Issue by ghost** [RIAEvangelist/node-ipc#459]
As we know his name is Brandon Nozaki Miller and hes working as the Director of Front End Technology & JavaScript Engineering at OCRA. He deleted his Linkedin, I wonder why🤔

**Comment by admiralnelson** [comment]
Got fired, simple as.

**Comment by s0menickname** [comment]
Obviously he doesn't need LinkedIn anymore. No company is gonna hire him for any IT speciality, while burger-flipping and retail jobs don't require a LinkedIn profile.

**Comment by moronwithinternet** [comment]
> Got fired, simple as. Possibly blacklisted from the industry

do we know for sure? its possible he hasnt been fired yet but just deleted his linkedin

**Comment by BrandonHuu** [comment]
Let's goo Brandon

**Comment by CoderEx24** [comment]
I think his boss is the least of his worries now.
Considering that he might face criminal charges
