### ISSUE TITLE
Client can't reconnect to server on Windows

### ISSUE THREAD

**Issue by asbelov** [RIAEvangelist/node-ipc#46]
Every time, when client try to reconnect to server, in lib\client.js:connect() initialised windows pipe:
if (process.platform ==='win32'){
    client.path = client.path.replace(/^\//, '');
    client.path = client.path.replace(/\//g, '-');
    **client.path= '\\\\.\\pipe\\'+client.path;**
}

and every reconnect added to pipe string '\\\\.\\pipe\\'. 

I fix it:
if (process.platform ==='win32'){
    client.path = client.path.replace(/^\//, '');
    client.path = client.path.replace(/\//g, '-');
    **if(client.path.indexOf('\\\\.\\pipe\\') == -1) client.path= '\\\\.\\pipe\\'+client.path;**
}

**Comment by RIAEvangelist** [comment]
fixed by PR #44

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
