### ISSUE TITLE
message about his father

### ISSUE THREAD

**Issue by Yoshii64** [RIAEvangelist/node-ipc#461]
as they say in python. father_figure = "gone"

**Comment by moronwithinternet** [comment]
`bitches = 0
print("Brandon has", bitches, "bitches")`

**Comment by Yoshii64** [comment]
> `bitches = 0` `print("Brandon has", bitches, "bitches")`
based python program and maker

**Comment by Sasytoremember** [comment]
:nobitches
mov r0, "bitches none"
mov r1, "father gone"
jmp nobitches

**Comment by Yoshii64** [comment]
what programming language is this? looks like ASM

**Comment by ThamognyaKodi** [comment]
in rust

```rust
fn main() {
    let brandon_father_figure=0; //yeah not even mut
    let brandon_bitches=0; // yeah not even mut
    if brandon_father_figure == 0 && brandon_bitches == 0 {
        println!("Brandon has {} bitches, and {} father figures", brandon_bitches, brandon_father_figure);
    } 
    else {
        println!("still a dick");
    }
}

```

**Comment by ThamognyaKodi** [comment]
> what programming language is this? looks like ASM

yup, thats assembly, just dont know if its x86-64 or etc. I never fully learned assembly.

**Comment by epstein-suicider** [comment]
> > what programming language is this? looks like ASM
> 
> yup, thats assembly, just dont know if its x86-64 or etc. I never fully learned assembly.

usual for a rust dev..

**Comment by zlw9991** [comment]
> what programming language is this? looks like ASM

:nobitches -> declares function nobitches
mov r0, "bitches none" -> moves string to r0 register, probably not legal afaik for arm32 (immediate addressing past 8 bits needs even rotations)
mov r1, "father gone" -> moves string to r1 register probably not legal afaik for arm32 (immediate addressing past 8 bits needs even rotations)
jmp nobitches -> jumps to start of nobitches function

**Comment by korewaChino** [comment]
```py
bitches = None
```
