### ISSUE TITLE
Creating issues talking about how messed up this is won't do anything

### ISSUE THREAD

**Issue by TechStudent11** [RIAEvangelist/node-ipc#462]
This guy can easily never touch GitHub ever again and won't have to deal with all the issues. Creating them won't help the situation

**Comment by thepwrtank18** [comment]
he's about to lose his job and potentially get charged with a felony

**Comment by 1over137** [comment]
This isn't about Ukraine. We should do other things to help defend Ukraine, such as donations. This is about defending free software against morons like @RIAEvangelist

**Comment by BrandonHuu** [comment]
> 

Not everything is about Ukraine dude, turn off the TV and go outside

**Comment by IAmMute** [comment]
Dead-on.
Are our software principles now moot?

**Comment by TechStudent11** [comment]
> This is about defending free software against morons like @RIAEvangelist

Many open source projects depend on `node-ipc`. 
They must contain a good version of the library. It should be easy for someone to create a repo without the malware.

**Comment by TechStudent11** [comment]
> Not everything is about Ukraine dude, turn off the TV and go outside

I know that. There are many other things happening in the world. But the timing is almost spot on,

**Comment by s0menickname** [comment]
We are talking about malicious code in an open source project, not about Ukraine.

**Comment by TechStudent11** [comment]
I have edited the issue. I didn't understand this didn't relate to the war.
