### ISSUE TITLE
Anyone here from MentalOutlaw?

### ISSUE THREAD

**Issue by ThamognyaKodi** [RIAEvangelist/node-ipc#463]
Also @RIAEvangelist, hope this does not delete all my files recursively and replace them with heart emojis if I had a Russian or Belarusian ip, would it?

**Comment by moronwithinternet** [comment]
yea i found out about this because of his video

**Comment by aequabit** [comment]
Based Jogger.

**Comment by TechStudent11** [comment]
Same here. I had no idea until I opened YT

**Comment by Yoshii64** [comment]
no. watching his video rn tho

**Comment by 5GameMaker** [comment]
yes

**Comment by coderboy14** [comment]
Thankfully I found out about it. I was looking for YouTube videos on the library, because this was exactly the library my project needed. However, I will now *never* use this package, nor any other packages from this user.

**Comment by IAmMute** [comment]
No doubt a large section of recent activity

**Comment by ThamognyaKodi** [comment]
I would not suggest not using it at all but rather waiting till this issue/crime is solved.

**Comment by AreaDenial** [comment]
> However, I will now _never_ use this package, nor any other packages from this user.

Just wait until somebody forks the repo and use that instead. It's going to happen soon enough

**Comment by ThamognyaKodi** [comment]
> Just wait until somebody forks the repo and use that instead. It's going to happen soon enough

yup, I think that will be the best case scenario.

**Comment by IAmMute** [comment]
> this was exactly the library my project needed. However, I will now _never_ use this package, nor any other packages from this user.



> > However, I will now _never_ use this package, nor any other packages from this user.
> 
> Just wait until somebody forks the repo and use that instead. It's going to happen soon enough

That's the road. Got to keep an eye on it.

**Comment by 5GameMaker** [comment]
> Thankfully I found out about it. I was looking for YouTube videos on the library, because this was exactly the library my project needed. However, I will now _never_ use this package, nor any other packages from this user.

I'm glad you found it before you installed malware on your PC

**Comment by 5GameMaker** [comment]
> > However, I will now _never_ use this package, nor any other packages from this user.
> 
> Just wait until somebody forks the repo and use that instead. It's going to happen soon enough

np

**Comment by realratchet** [comment]
He posted? Brb

**Comment by coderboy14** [comment]
> @coderboy14 I would not suggest not using it at all but rather waiting till this issue/crime is solved.

Frankly, I don't trust any code with their name on it now. They have ruined their reputation. If I can't find an alternative library, I'd sooner write my own, then ever touch any package with their name on it again. Their actions were simply abhorrent, attacking private citizens knowingly and wilfully. It is not just morally objectionable, but straight up a crime.

**Comment by 5GameMaker** [comment]
> > @coderboy14 I would not suggest not using it at all but rather waiting till this issue/crime is solved.
> 
> Frankly, I don't trust any code with their name on it now. They have ruined their reputation. If I can't find an alternative library, I'd sooner write my own, then ever touch any package with their name on it again. Their actions were simply abhorrent, attacking private citizens knowingly and wilfully. It is not just morally objectionable, but straight up a crime.

`node-ipc@10` should be safe. Also I forked the repo JIK they add that nonsence back

**Comment by ThamognyaKodi** [comment]
> > @coderboy14 I would not suggest not using it at all but rather waiting till this issue/crime is solved.
> 
> Frankly, I don't trust any code with their name on it now. They have ruined their reputation. If I can't find an alternative library, I'd sooner write my own, then ever touch any package with their name on it again. Their actions were simply abhorrent, attacking private citizens knowingly and wilfully. It is not just morally objectionable, but straight up a crime.

I can understand that, since that is how I am feeling. I am just going to stick to using forks of the package, can really trust @RIAEvangelist anymore.

**Comment by coderboy14** [comment]
> > > @coderboy14 I would not suggest not using it at all but rather waiting till this issue/crime is solved.
> > 
> > 
> > Frankly, I don't trust any code with their name on it now. They have ruined their reputation. If I can't find an alternative library, I'd sooner write my own, then ever touch any package with their name on it again. Their actions were simply abhorrent, attacking private citizens knowingly and wilfully. It is not just morally objectionable, but straight up a crime.
> 
> `node-ipc@10` should be safe. Also I forked the repo JIK they add that nonsence back

Honestly, I don't want code of theirs in my project at this point. Their work deserves to be forgotten in obscurity. This is just about of my moral standing, just as I wouldn't want the code of a flagrant racist in my project, I don't want the code of somebody who either A) demonstrated a lack of control over their emotions and impulsiveness; or B) demonstrated a wilful disregard for the individuals and companies using the code.

**Comment by CoderEx24** [comment]
I only know about this because of him
