### ISSUE TITLE
Okay, now serious

### ISSUE THREAD

**Issue by 5GameMaker** [RIAEvangelist/node-ipc#465]
It's good that you've reverted that change, but could you please also remove it from NPM? People getting malware on their PCs just because this package was listed somewhere in dependencies is a bad thing.

**Comment by 1over137** [comment]
Realistically, NPM needs to take over and remove his access permanently while also fixing the packages. There's no reason to trust @RIAEvangelist ever again.

**Comment by coderboy14** [comment]
Personally, I am never going to use any code with their name on it again. They have permanently ruined any reputation they had. I already reported this repository to GitHub, and reported the package to NPM.

**Comment by 5GameMaker** [comment]
I reported this to NPM already, hope they'll take action

**Comment by ThamognyaKodi** [comment]
Yup, I also reported it. Thanks for the idea @5GameMaker .

**Comment by 5GameMaker** [comment]
Also reported peacenotwar in case there're are any packages that do the same

**Comment by coderboy14** [comment]
The package owner is the only one I've reported. Reported to GitHub, NPM, authorities, employer, and I contacted the one supporter he has, just in case they were unaware of the actions he has taken against the open source community, so they can make an informed decision moving forward.
