### ISSUE TITLE
Help Brandon find a new job.

### ISSUE THREAD

**Issue by mattwilson888** [RIAEvangelist/node-ipc#467]
What Brandon did was wrong, but everyone deserves forgiveness. Lets post job applications to help him get his life back on track.

https://careers.mcdonalds.com/us-restaurants/jobs?page=1

**Comment by coderboy14** [comment]
Can't say I'd trust the food made by him. Would likely mess with the food of anyone he thinks is Russian.

**Comment by IAmMute** [comment]
Malicious Hamburgers, _with Love from McDonalds_.

**Comment by thepwrtank18** [comment]
every mcdonalds burger he makes will have a tiny atom bomb that will explode if it thinks the person who ate it is russian

**Comment by BrandonHuu** [comment]
He's good bro. hes gonna be making license plates for 2 cents an hour in prison

**Comment by ThamognyaKodi** [comment]
Would not trust him, but you know might give him a second chance.

**Comment by coderboy14** [comment]
> Would not trust him, but you know might give him a second chance.

That's for an individual to choose on their own. Frankly, I will not be giving them one. They demonstrated a wilful disregard for the individuals using the code, directly or otherwise. They showed they cannot be trusted, as they either A) acted in severe ignorance based on emotion; B) wilfully attacked the private citizens and companies using this code out of virtue-signalling; C) all of the above.

**Comment by ThamognyaKodi** [comment]
> 

Yup I agree, I will definitely not give him another chance in anything tech related for sure.

**Comment by IAmMute** [comment]
> Would not trust him, but you know might give him a second chance.

Uncertain of what to expect now. In my ethics when it comes to building something like this the code is supposed to touch the issue the project is aimed at and keep contained to that issue. It's a building block.

Flaming him with issues is counterproductive but a natural internet thing.
If he doesn't dig in and double down more maybe he's wise enough to back away from it for things to cool down -what matters is this not happening elsewhere. To play these kind of cards in this kind of a position.. that's reputation damage that is going to be fairly easy to look up.

**Comment by OnePinkSheep** [comment]
> Malicious Hamburgers

Isn't that just regular McDonald's hamburgers?
