### ISSUE TITLE
Server connects to multiple clients when "maxConnections" parameter is set to value 1.

### ISSUE THREAD

**Issue by nileshprasad** [RIAEvangelist/node-ipc#47]

**Comment by nileshprasad** [comment]
If the value of "maxConnections" is set 0, still the server will make connections with any available clients.

**Comment by RIAEvangelist** [comment]
0 is an invalid argument for a server, however 1 should work.

**Comment by nileshprasad** [comment]
Only for clarification purpose, the value set to 1, does not work.

**Comment by RIAEvangelist** [comment]
are you trying to say it doesn't work only if set to 1 but will work if set to 2 then?

**Comment by nileshprasad** [comment]
When the value is set to 1 or any number, the max connections does not matter. The server will connect to any number of clients available and not just connect to the set value in "max connections" parameter. So if the value set is 2 and three clients are available, the server will make connections with all 3 of them.

**Comment by RIAEvangelist** [comment]
OK, so maxConnections just doesn't work. It's unrelated to setting it to 1.

Thank you!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
