### ISSUE TITLE
report him

### ISSUE THREAD

**Issue by 1over137** [RIAEvangelist/node-ipc#470]
don't forget to go to the profile page to smash the report button

**Comment by Thanatoslayer6** [comment]
lol

**Comment by coderboy14** [comment]
Report him to GitHub, report his NPM package to NPM, report his actions to the relevant authorities (it's a federal crime, afik, to knowingly and wilfully spread malware), and if you're so inclined, several people have shared the email to his place of employment (which I'm sure you could also find via LinkedIn).

**Comment by expeditiousRubyist** [comment]
Report him to the FBI's Internet Crime Complaint Center
https://www.ic3.gov/Home/FileComplaint
