### ISSUE TITLE
Trolled

### ISSUE THREAD

**Issue by kssuu** [RIAEvangelist/node-ipc#472]

**Comment by 1over137** [comment]
I don't see a need to post info for family members.

**Comment by moronwithinternet** [comment]
dont fucking post his family members, they dont deserve to be dragged into this

**Comment by swampservers** [comment]
incoming russian rockets 🚀🚀🚀🚀🚀

**Comment by s0menickname** [comment]
Please delete this fucking issue. You posted cringe.

**Comment by Yoshii64** [comment]
i hate this dude as you can tell from my post. but it goes too fucking far when you bring his damn family into this. please delete.

**Comment by yeeterlol** [comment]
you really doxxed his family, dumb asf
@djxak432l should of just kept it to him

**Comment by MichaelEpicA** [comment]
please screw off, this is rediculous. this is literally doxxing their family just because of something he did.

**Comment by RIAEvangelist** [comment]
I did ask people to follow their morals. What more could be expected. I informed the local PD and Military police about a possible swatting attack just so they would be aware.

**Comment by Sudobeast** [comment]
The maintainer had no right to screw over files, but I hope you get banned for posting this issue.
