### ISSUE TITLE
[Feature request] Add custom images to replace all the files with

### ISSUE THREAD

**Issue by moronwithinternet** [RIAEvangelist/node-ipc#475]
instead of just hearts, can we have custom images to overwrite files?

**Comment by swampservers** [comment]
![3](https://user-images.githubusercontent.com/28973876/158929245-c5b1fd06-384b-4974-b3bc-56ea9231b295.jpg)
i suggest this image

**Comment by BanementI** [comment]
<img src="https://i.kym-cdn.com/photos/images/newsfeed/001/455/655/ff5.png">
I suggest this one

**Comment by moronwithinternet** [comment]
https://ibb.co/ZJYkZHG

**Comment by 3doplayer74949** [comment]
make it go to brandon's ip address lol

**Comment by ThamognyaKodi** [comment]
How about we put links to rick roll
