### ISSUE TITLE
Fork?

### ISSUE THREAD

**Issue by ThamognyaKodi** [RIAEvangelist/node-ipc#476]
Does anyone have a fork that is updated or will be updated without malware? If there is, are there any intentions to add the fork to npm.

**Comment by MichaelEpicA** [comment]
i believe it has been removed already

**Comment by MichaelEpicA** [comment]
> i believe it has been removed already

Unsure tho

**Comment by s0menickname** [comment]
I have one, but don't have any intentions to add it to npm because I am just above zero in js and won't be able to maintain.

**Comment by ThamognyaKodi** [comment]
> i believe it has been removed already

Yup, I noticed that but I just dont have enough trust in @RIAEvangelist to use it again sadly. Maybe if this issue/crime cools down I will consider using it.

**Comment by ThamognyaKodi** [comment]
> I have one, but don't have any intentions to add it to npm because I am just above zero in js and won't be able to maintain.

Although I am not the best at js, I can try to look and see if I can fix stuff like that.

**Comment by Boogie3D** [comment]
> > I have one, but don't have any intentions to add it to npm because I am just above zero in js and won't be able to maintain.
> 
> Although I am not the best at js, I can try to look and see if I can fix stuff like that.

I'd wait until he's safely in prison personally

**Comment by MichaelEpicA** [comment]
> > Yup, I noticed that but I just dont have enough trust in @RIAEvangelist to use it again sadly. Maybe if this issue/crime cools down I will consider using it.
> 
> I'd wait until he's safely in prison personally

Question, how many repos use this?

**Comment by ThamognyaKodi** [comment]
> > > Yup, I noticed that but I just dont have enough trust in @RIAEvangelist to use it again sadly. Maybe if this issue/crime cools down I will consider using it.
> > 
> > 
> > I'd wait until he's safely in prison personally
> 
> Question, how many repos use this?

Quite a lot actually, here is the list: https://github.com/zlw9991/node-ipc-dependencies-list

**Comment by Boogie3D** [comment]
> > > Yup, I noticed that but I just dont have enough trust in @RIAEvangelist to use it again sadly. Maybe if this issue/crime cools down I will consider using it.
> > 
> > 
> > I'd wait until he's safely in prison personally
> 
> Question, how many repos use this?

Many electron-based apps could potentially be compromised

**Comment by MichaelEpicA** [comment]
> > > > Yup, I noticed that but I just dont have enough trust in @RIAEvangelist to use it again sadly. Maybe if this issue/crime cools down I will consider using it.
> > > 
> > > 
> > > I'd wait until he's safely in prison personally
> > 
> > 
> > Question, how many repos use this?
> 
> Many electron-based apps could potentially be compromised

I heard Unity Hub uses this, thank god I'm still using an old version of Unity Hub haha

**Comment by yeeterlol** [comment]
> > > > > Yup, I noticed that but I just dont have enough trust in @RIAEvangelist to use it again sadly. Maybe if this issue/crime cools down I will consider using it.
> > > > 
> > > > 
> > > > I'd wait until he's safely in prison personally
> > > 
> > > 
> > > Question, how many repos use this?
> > 
> > 
> > Many electron-based apps could potentially be compromised
> 
> I heard Unity Hub uses this, thank god I'm still using an old version of Unity Hub haha

Unity Hub 3.1.1 fixes the issue

**Comment by MichaelEpicA** [comment]
> > > > > > Yup, I noticed that but I just dont have enough trust in @RIAEvangelist to use it again sadly. Maybe if this issue/crime cools down I will consider using it.
> > > > > 
> > > > > 
> > > > > I'd wait until he's safely in prison personally
> > > > 
> > > > 
> > > > Question, how many repos use this?
> > > 
> > > 
> > > Many electron-based apps could potentially be compromised
> > 
> > 
> > I heard Unity Hub uses this, thank god I'm still using an old version of Unity Hub haha
> 
> Unity Hub 3.1.1 fixes the issue

thx updating now
