### ISSUE TITLE
GUIDE TO SURVIVING WITHOUT NODE-IPC (NOT CLICKBAIT)

### ISSUE THREAD

**Issue by REALERvolker1** [RIAEvangelist/node-ipc#479]
Step 1: `npm init -y`

Step 2: Copy and paste the following into index.js:
`const express = require('express')
const app = express()
const port = 6969
app.get('/', (req, res) => {
  res.send('Hello World!')
})
app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})`

Step 3: Profit

**Comment by 3doplayer74949** [comment]
happy 100 issues

**Comment by REALERvolker1** [comment]
as the 100th normie to complain about this, do I get a special prize?

**Comment by 3doplayer74949** [comment]
you get a hot dog
![image](https://user-images.githubusercontent.com/38743888/158931122-3a15de3a-19f5-4d37-997d-ae35c63f2df4.png)

**Comment by zlw9991** [comment]
> as the 100th normie to complain about this, do I get a special prize?

you have my updoot

**Comment by REALERvolker1** [comment]
![image](https://user-images.githubusercontent.com/73304952/158931214-201e1d5c-e30f-4412-b9d8-17a129729770.png)
kek

**Comment by REALERvolker1** [comment]
so how long until I can get back to learning svelte

**Comment by RIAEvangelist** [comment]
@REALERvolker1 this is actually an interesting way to do http & https, but it does not solve for TLS/TCP/UDP/POSIX/UNIX sockets. However, this does solve.
