### ISSUE TITLE
fuck node ipc, all my homies hate node ipc

### ISSUE THREAD

**Issue by SkySpnc** [RIAEvangelist/node-ipc#481]

**Comment by DillonPotts** [comment]
![node](https://user-images.githubusercontent.com/47173826/158932172-80cdd806-0778-4e43-af18-e94bb4c4cec8.jpg)

**Comment by gitdrug** [comment]
RIAEvangelist = Retard That sould commit self harm

**Comment by RIAEvangelist** [comment]
This but OSS instead... Click it, click it good.

[![Alt text](https://i3.ytimg.com/vi/idx3GSL2KWs/hqdefault.jpg)](https://www.youtube.com/watch?v=idx3GSL2KWs)
