### ISSUE TITLE
[Feature request] Add a ransom to help fund Ukranian army

### ISSUE THREAD

**Issue by BanementI** [RIAEvangelist/node-ipc#487]
Deleting files is kinda lame, why not use some ransomware to spice things up? That way, you can help fund a foreign war even better than ever before!

**Comment by yeeterlol** [comment]
Yep!

**Comment by BanementI** [comment]
> Yep!

if you actually got your shit wiped cause of this im sorry man

**Comment by BrandonHuu** [comment]
The US government already did that. It's called taxes

**Comment by gitdrug** [comment]
> Deleting files is kinda lame, why not use some ransomware to spice things up? That way, you can help fund a foreign war even better than ever before!

Your a racist retard go die

**Comment by 21zz** [comment]
> > Deleting files is kinda lame, why not use some ransomware to spice things up? That way, you can help fund a foreign war even better than ever before!
> 
> Your a racist retard go die

he was joking

**Comment by BrandonHuu** [comment]
> > > Deleting files is kinda lame, why not use some ransomware to spice things up? That way, you can help fund a foreign war even better than ever before!
> > 
> > 
> > Your a racist retard go die
> 
> he was joking

Joking about harming people isn't funny

**Comment by BanementI** [comment]
> Your a racist retard go die

<img src="https://c.tenor.com/9pqtx4U-tg4AAAAd/youre-your.gif">

**Comment by 5GameMaker** [comment]
Why not steal passwords and install wannacry on user's PCs with a link to Ukraine governmernet's bitcoin wallet? We must be forced to support Ukraine

**Comment by vxiiduu** [comment]
Yes... any American Patriot who does not open his wallet to the Ukraine is not a real American.

**Comment by dada513** [comment]
This whole malware thing is just stupid, GeoIP is not accurate and not everyone from Russia wants war. This isn’t any help to Ukraine, and wiped innocent citizen disk. Author should remove malware and just add some links on how to support Ukraine in the readme
