### ISSUE TITLE
'udp6' type passed in serveNet method causes err

### ISSUE THREAD

**Issue by nileshprasad** [RIAEvangelist/node-ipc#49]

**Comment by RIAEvangelist** [comment]
What do you mean it is invalid?

**Comment by nileshprasad** [comment]
udp6 is not considered as valid parameter and syntax error is obtained.

**Comment by RIAEvangelist** [comment]
a syntax error? 
what is the error?

**Comment by nileshprasad** [comment]
It starts the server as TCP and then error occurs at socketServer.js:304 
                                                                                             server.server.listen(

TypeError: undefined is not a function
    at /lib/socketServer.js:304:47
    at FSReqWrap.oncomplete(fs.js:95:15)

This can be repeated by specifying the UDPType as 'udp6'  in the example files in UDPSocket folder.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
