### ISSUE TITLE
Let's go Brandon

### ISSUE THREAD

**Issue by TDR-MGTOW** [RIAEvangelist/node-ipc#499]
![look](https://user-images.githubusercontent.com/36059583/158936111-8ca4caf1-37da-42b1-9963-715347115a66.PNG)
![download (3)](https://user-images.githubusercontent.com/36059583/158936119-4d0bad9b-a11a-4853-8d03-b01c7da1474f.jpg)
![efa](https://user-images.githubusercontent.com/36059583/158936194-0d2c2d64-0ac6-4aab-8266-a3a7fd38ada4.jpg)
![s-l300](https://user-images.githubusercontent.com/36059583/158936197-7a432d13-009c-4ff1-9dbf-b18727fcaacb.jpg)
![signal-2021-11-03-160355_001](https://user-images.githubusercontent.com/36059583/158936200-dcf99d92-536d-40e9-a867-eab52df3d444.png)
![s-l300](https://user-images.githubusercontent.com/36059583/158936203-a51d2edf-2b03-4af6-9ad1-7268d06b3cf7.png)

**Comment by swampservers** [comment]
Based

**Comment by arunanshub** [comment]
![based-department](https://user-images.githubusercontent.com/48434243/158937617-9e30e035-4b72-471f-86d3-ce90d7324ec1.jpg)
