### ISSUE TITLE
No error condition defined for the case when two UDP sockets are using the same port.

### ISSUE THREAD

**Issue by nileshprasad** [RIAEvangelist/node-ipc#50]

**Comment by RIAEvangelist** [comment]
If this is happening on your machine, it is a system level issue or inherent in what you are building.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
