### ISSUE TITLE
Good job cunt

### ISSUE THREAD

**Issue by mpfatxd** [RIAEvangelist/node-ipc#500]
What an awesome way to ruin your reputation and earn yourself some potential prison time. I'm sure it was well worth it though, after all you single handedly ended the war! Oh wait, you did nothing but install malware on thousands or millions of innocent peoples' PCs and make yourself look like a piece of shit. Congrats you fuckin moron 😊

**Comment by quantumpacket** [comment]
Not sure what country he's from, but afaik in the U.S. intentionally spreading malware is a felony. What a stupid  and childish way to ruin one's career.

**Comment by mpfatxd** [comment]
> 

As far as I know the malware itself is not illegal, but the destruction of data on computers that do not belong to you is a felony. So looks like our friend here may be facing a decent prison sentence. Oopsie

**Comment by quantumpacket** [comment]
This guy plead guilty to and was charged with a felony for just the intent to distribute the Kronos malware.
 https://www.techspot.com/news/79736-marcus-hutchins-known-stopping-wannacry-pleads-guilty-banking.html

**Comment by mpfatxd** [comment]
> 

Well I stand corrected then. Seems Brandon is going to get dicked by the law either way
