### ISSUE TITLE
Niggers

### ISSUE THREAD

**Issue by racist-incel** [RIAEvangelist/node-ipc#503]
Niggers

**Comment by t3xasdev** [comment]
Wow so funny.

**Comment by racist-incel** [comment]
Mental outlaw is aight tho

**Comment by BrandonHuu** [comment]
> Mental outlaw is aight tho

I really hope github fingerprints you and bans you forever

**Comment by racist-incel** [comment]
> > Mental outlaw is aight tho
> 
> I really hope github fingerprints you and bans you forever

Niggers???????

**Comment by jonathan-rosa** [comment]
> > Mental outlaw is aight tho
> 
> I really hope github fingerprints you and bans you forever

like how your website is?

**Comment by Privanom** [comment]
hahahaahaah good one. you are the funniest comedian ever

**Comment by farmisen** [comment]
Racist, incel and coward, not even surprised.

**Comment by TheShermanTanker** [comment]
this would make at least more sense if we actually knew who or what that was directed at

**Comment by freaky33** [comment]
> > Mental outlaw is aight tho
> 
> I really hope github fingerprints you and bans you forever

So what's your problem with mental outlaw?

**Comment by CoderEx24** [comment]
I like how everyone is so disturbed by a single word

**Comment by Hendicted** [comment]
based
