### ISSUE TITLE
Good Work, Wagie!

### ISSUE THREAD

**Issue by arunanshub** [RIAEvangelist/node-ipc#504]
<img src="https://user-images.githubusercontent.com/48434243/158936286-3553d912-d3a5-4a29-9df1-44b9d2e0db9a.jpeg" width="400" height="400" />

Thanks for your contribution, Wagie No. 472-25-9-9. You have been awarded 1400 Good They/Them Tokens to your account.

## Alert ⚠️

Our automated scans shows that you have not received your 956th booster vaccine! Make sure you register with the nearest centre within this week. Failure to do so will result in 25% deduction of your They/Them Tokens.

**Comment by waleed177** [comment]
They 'obviously' supported the 'current thing' by 'deleting files' of people
