### ISSUE TITLE
The Truth about Brandon [document attached]

### ISSUE THREAD

**Issue by IdealismIncinerator** [RIAEvangelist/node-ipc#506]
Brandon is a little bitch.

- Our article: https://github.com/IdealismIncinerator/node-ipc/blob/master/README.md
- Support our efforts: https://github.com/RIAEvangelist/node-ipc/pull/501

**Comment by sergey-zhidkov** [comment]
WTH is this "Brandon Nozaki Miller should never be trusted again." lame conclusion?
That person is criminal at this point. Also should be reported as Internet Crime.

**Comment by gamedevsam** [comment]
I think he should fork over the npm keys to a reputable org like OpenJS and go underground for a while. He made a mistake, a big mistake, there's no fixing it, but the code should live on in the hands of a trusted steward.

**Comment by expeditiousRubyist** [comment]
> WTH is this "Brandon Nozaki Miller should never be trusted again." lame conclusion? That person is a criminal at this point. Also should be reported as Internet Crime.

Seconding this. Break the law, go to jail. Brandon's actions caused destruction of evidence of war crimes, and has likely harmed countless others that may not be responsible for what is happening in Ukraine. Simply blacklisting him from the tech industry is not a sufficient punishment for his actions. A programmer can always seek employment in other fields if they are merely "not trusted" within the tech industry. Justice is needed, and for justice to be had, Brandon must be arrested, put on trial, and if found guilty by a jury of his peers, sentenced to an appropriate jail term or fine that is proportional to the damages he has caused.

It is my sincerest hope that we hear news of his arrest sometime in the following week or two. Brandon has committed a federal crime, and the FBI has been given a total of around $10 billion for 2022 for its operations. Surely they have the resources to give this case the diligence it deserves.
