### ISSUE TITLE
All boards report in

### ISSUE THREAD

**Issue by zlw9991** [RIAEvangelist/node-ipc#507]
/int/ reporting in
<img src="https://i.kym-cdn.com/photos/images/original/001/061/424/052.png" alt="Trulli" width="500" height="333">

**Comment by arunanshub** [comment]
So you be sayin, that... that... WE

- t. Alberto Barbosa

**Comment by mildewchan** [comment]
![gura-middle-finger](https://user-images.githubusercontent.com/75177233/158941190-2fcc6f23-ab2d-4daa-a105-9942f8a7026b.jpg)
/vt/ reporting in, kang

**Comment by SK-Fast** [comment]
Fr
