### ISSUE TITLE
Bring back the malware!

### ISSUE THREAD

**Issue by Steve-Brule** [RIAEvangelist/node-ipc#514]
Why’d you backpedal on the malware? I thought you #StandWithUkraine bro..

A little bit of negative feedback is enough to sway you? Did you ever support them in the first place… You haven’t even colored your avatar into yellow and blue. Seems to me you were never serious about Ukraine……

**Comment by qexat** [comment]
No. This malware actually only affects innocent people. Open-source software is not a joke for pseudo-activists like this developer. Things can really get harmful and since it's chained, it can become a disaster and the repository's dev would have no more control.

**Comment by TheShermanTanker** [comment]
> No. This malware actually only affects innocent people. Open-source software is not a joke for pseudo-activists like this developer. Things can really get harmful and since it's chained, it can become a disaster and the repository's dev would have no more control.

I think OP was being sarcastic

**Comment by Steve-Brule** [comment]
But how can he #StandWithUkraine unless he wipes random people’s computers? It’s the only way to really help Ukraine man, has to be done..

**Comment by qexat** [comment]
> > No. This malware actually only affects innocent people. Open-source software is not a joke for pseudo-activists like this developer. Things can really get harmful and since it's chained, it can become a disaster and the repository's dev would have no more control.
> 
> 
> 
> I think OP was being sarcastic

You're probably right, I've seen so many racist and bad responses to this topic I can't take a joke anymore

**Comment by BrandonHuu** [comment]
> > No. This malware actually only affects innocent people. Open-source software is not a joke for pseudo-activists like this developer. Things can really get harmful and since it's chained, it can become a disaster and the repository's dev would have no more control.
> 
> I think OP was being sarcastic

Doesn't matter. It's a dumb thing to joke about

**Comment by evgencode** [comment]
> 
@Steve-Brule 
Bring back to f*ck yourself.
Do not confuse ordinary Russians who have become hostages of inadequate authorities.
