### ISSUE TITLE
No more free and safe open source software

### ISSUE THREAD

**Issue by seeth23** [RIAEvangelist/node-ipc#515]
I mean that's all gone, no more free and safe software we can use now, if anyone who runs repository can literally put malware to delete personal data of some people IN PUBLIC REPOSITORY(just imagine, PUBLIC repository). We cannot trust more other free packages, because tomorrow someone will decide to put malware in his repository and etc. That's not even about Russia and Ukraine, some other country can be bullied this way.

**Comment by konstantin1722** [comment]
Malicious code can be added to any software. You need to check for updates, and not download mindlessly.
In this case, the Nazis showed themselves, what can I say, nothing but disgust for these people can not be experienced.

**Comment by 3doplayer74949** [comment]
rest in piss forever miss foss

**Comment by CoderEx24** [comment]
we don't have to loss trust altogether.
we just need to know who to trust.
if one falls, other will take his place

**Comment by waleed177** [comment]
Free software is still important, not just because there are bad actors that we should distrust everyone. If this was in proprietary software it wouldn't have been as easy to discover as right now. Distrust the person who did this, yes. Distrust everyone no.
