### ISSUE TITLE
I thought we had each other! This is heartbreaking.

### ISSUE THREAD

**Issue by vajahath** [RIAEvangelist/node-ipc#518]
I'm not from Russia. But I remember we are here because we had each other.
There should be no discrimination in dev community on any regards.
No matter:
- back or white
- poor or rich
- african or american or russian
- or stackoverflow reputation

We helped each other to reach this state. And I owe a lot to this community and I bet everyone else too.

Imagine people are doing this allover like:
- angular/react/express/node.js and every popular repo are deleting Russian commits and PRs!
- and removing all stackoverflow Russian answers!

Now I can't trust the opensource because 
after all the sweat and tears I put into my project for years vanished in a snap due to some govt-to-govt conflict!
That is heartbreaking.
I may have never voted for the govt or I may never support govt actions.
I may be cherishing my family, my kids and my dreams - and the same community helped me to gain all of them are now destroying it in a snap.

Innocent russuan life matters just like how blacklivesmattered.

**Comment by CoderEx24** [comment]
don't lose trust in open source because some guy decided to act heroic
if he falls, others will take his place

and I am sorry for you project

**Comment by RIAEvangelist** [comment]
God bless you, your family and your people.
