### ISSUE TITLE
ok but

### ISSUE THREAD

**Issue by the2048** [RIAEvangelist/node-ipc#519]
have you ever seen the Nissan NX2000 and how cool it generally is
![image](https://user-images.githubusercontent.com/37256486/158948213-ebe93533-70f7-4086-92ad-2826226ef770.png)

**Comment by IvanAdmaers** [comment]
Looks amazing. Even better than Tesla

**Comment by CoderEx24** [comment]
cars are overrated.
walking is good :3

**Comment by dausruddin** [comment]
Walking is overrated.
Being disabled is the best.

**Comment by RIAEvangelist** [comment]
set the original title back. This is funny.
