### ISSUE TITLE
Where is Github's response in all of this?

### ISSUE THREAD

**Issue by AlfZR** [RIAEvangelist/node-ipc#522]
As others have mentioned, this is a very serious violation to what FOSS stands for. Why aren't these people black listed from github already?

**Comment by 3doplayer74949** [comment]
nowhere 
they have their own fish to fry

**Comment by expeditiousRubyist** [comment]
No clue, though the repository does need to remain accessible in some way for the FBI to use as evidence. Maybe prevent him from making commits that would delete git history.

**Comment by PeterStrick** [comment]
> As others have mentioned, this is a very serious violation to what FOSS stands for. Why aren't these people black listed from github already?

Good question, as of now all we can do is report @RIAEvangelist to GitHub as well as his NPM Module. See #525. Creating issues won´t help as he will close and delete them. Just report him directly.
