### ISSUE TITLE
#StopHatingRussians

### ISSUE THREAD

**Issue by pointofpresence** [RIAEvangelist/node-ipc#528]
https://www.youtube.com/watch?v=gAyWhP4kI0M

Stop nazism!!!!!!

**Comment by ecdsa521** [comment]
Russians are _the_ nazis. 

When there were bigger protests against closing mcdonalds than putler waging a war, something is deeply wrong with the whole country.

**Comment by pointofpresence** [comment]
> 

I think deeply wrong with your own head, man
