### ISSUE TITLE
How do I read data received from client on the server side

### ISSUE THREAD

**Issue by aafeliz** [RIAEvangelist/node-ipc#54]
I implemented the basic UDP server shown below, and I have a different application(written in c++) sending messages to the server. The server logs the following:
 socket connection to server detected                                                                                                                                                       
Received UDP message from  127.0.0.1 46843
indicating that it has received a message from a client, now how do i access the data from the server side in order to make a variable equal to the data that the server has received?
ipc.config.id   = 'hello';
    ipc.config.retry= 1500;
 
    ipc.serveNet(
        8001,
        'udp4',
        function(){
            ipc.server.on(
                'message',
                function(data){
                    ipc.log('got Data');
                    ipc.log('got a message from '.debug, data.from.variable ,' : '.debug, data.message.variable);
                }
            );
            ipc.server.emit(
                {
                    address : '127.0.0.1', //any hostname will work 
                    port    : ipc.config.networkPort
                },
                'message',
                {
                    from    : ipc.config.id,
                    message : 'Hello'
                }
            );
        }
    );
 
    ipc.server.define.listen.message='This event type listens for message strings as value of data key.';
 
    ipc.server.start();

**Comment by RIAEvangelist** [comment]
is your C++ code sending the delimiter?

I believe the docs cover this you can change it to whatever you want. The default is either \f I think

**Comment by aafeliz** [comment]
Thank you for you quick response, I really appreciate it. 
The delimiter that I am using is a comma, but ill give the \f a try. Im not very familiar with node js, which attribute of ipc.server contains the data?

**Comment by RIAEvangelist** [comment]
If you are sending JSON then you should get JSON,

If you are sending raw buffers, hex or binary then you should set the raw buffer in the node config.

This looks like you might not be sending anything from C++.

When dealing with JSON in C based languages the Janson lib might be helpful.

Otherwise just specify in the node code that you are using rawBuffers

**Comment by aafeliz** [comment]
bellow i pasted the node js including the configurations.I set the configs to raw buffer I also tried using both ascii and utf8. On the c++ side of things i am sending a string after successfully connecting as a client to the UDP server initiated by nodejs. 

I a bit confused by the message "Received UDP message from 127.0.0.1 36632". I took it as an indication that c++ is sending the data, since it shows the message immediately after the scheduled output to the server from the c++ code.

Please help, this a key component to a class project that I need to get different processes talking to each other. Thank you, I appreciate your help.
--------------------------------------------------------------------
var ipc = require('node-ipc');
var dataFrom;
ipc.config.id = 'world';
//ipc.config.retry = 1500;
ipc.config.encoding = 'ascii';//'utf8';
ipc.config.rawBuffer = true;

ipc.serveNet(
    8001,
    'udp4',
    function(){
        console.log(123);
        ipc.server.on(
            'message',
            function(data,socket){
                ipc.log('got a message from '.debug, data.from.variable ,' : '.debug, data.message.variable);
                ipc.server.emit(
                    socket,
                    'message',
                    {
                        from    : ipc.config.id,
                        message : data.message+' world!'
                    }
                );
            }
        );

        console.log(ipc.server);
    }
);



ipc.server.define.listen.message='This event type listens for message strings as value of data key.';
ipc.server.start();

**Comment by RIAEvangelist** [comment]
That means it is sending stuff. your node portion is working as expected.

Your C++ code is not sending what you are expecting. Have you tried ***ipc.config.rawBuffer***

Inorder for me to help with your C++ you have to put it up on github.

**Comment by RIAEvangelist** [comment]
Also, is there any reason you have to build it in C++ if you are having trouble with it?

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
