### ISSUE TITLE
Unable to handle EADDRINUSE error from outside of this module.

### ISSUE THREAD

**Issue by Rokt33r** [RIAEvangelist/node-ipc#56]
I want my app to switch the path of socket if it is already using automatically.
But, It seems to be impossible.

I checked `lib/socketServer.js` file. It seems to be able to access Server instance of node-ipc after the server started.
But, starting with a path already using, EADDRINUSE is thrown before the Server instance of node-ipc became accessible.
Putting `nodeIpc.server.start()`method into `try...catch` also doesn't work because this exception occurs inside of callback of async function, `fs.unlink`.

Is there any solution to solve this problem?

**Comment by Rokt33r** [comment]
This is my temporary expedient.

https://github.com/Rokt33r/node-ipc/commit/069146e005a1581fe7341366ec01a3e8a7cc0f66#diff-4548bafde8aa8c29050173ecc3ecb9d1

**Comment by RIAEvangelist** [comment]
Just to make sure, did you try binding to the error event?

.on('error',handlerFunc)

**Comment by RIAEvangelist** [comment]
nvm, if it is in fs.unlink, then I understand why it would never get to the error handler. I'll see if there is another way to handle this issue. If not I will merge in your quick fix. Just want to make sure we can't come up with something a bit more elegant.

**Comment by Rokt33r** [comment]
I agree with that there must be much better solution than mine. I'll wait for it gladly.

**Comment by RIAEvangelist** [comment]
Fixed now

see the basic example in TCP

```javascript

    ipc.server.on(
        'error',
       function(err){
           ipc.log('Got an ERROR!'.warn,err)
       }
   )

```

**Comment by Rokt33r** [comment]
Thank you for updating! :tada:

**Comment by RIAEvangelist** [comment]
Do you think you could help with the documentation in Chinese?

I saw in some of your repos you used chinese in your code or HTML.

If not that's cool, I know it can be a lot of work to help with documentation. If you can though I would really appreciate it!

**Comment by Rokt33r** [comment]
Haha, I would be glad to do it if I can. But, I cannot speak Chinese.
I'm Korean and living in Japan.

So, if you need Japanese or Korean translation, I think I can help you! :dancers:

**Comment by RIAEvangelist** [comment]
I thought so by your name, but your repos look like they have chinese so I was like huh... guess names can be deceiving.

俺も日本語できる。日本語のドキュメントも作るべきなー。何語でも手伝ったら嬉。

저는 조금 한국어 말한다.

我的中國不好。

**Comment by Rokt33r** [comment]
I thought you can speak Japanese because of your middle name! :smirk: 
Btw, I started writing Korean version of documentation first. I think it would be finished about next weekend.

**Comment by RIAEvangelist** [comment]
Amazing! Thanks!! :tada:

**Comment by Rokt33r** [comment]
I think we have to create a new issue for translation.
Btw, I have a question. What is the difference between `maxRetries` and `stopRetrying` in `ipc.config`?

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
