### ISSUE TITLE
Someone made a video about you and your module 

### ISSUE THREAD

**Issue by Infidigious** [RIAEvangelist/node-ipc#562]
https://youtu.be/2M-L0yPbtPE
Imagine deleting issues

**Comment by 3doplayer74949** [comment]
hell its not even deletion
you can still post in them

**Comment by CoderEx24** [comment]
Mental Outlaw goes brrrrrrrrrrrrrrr

**Comment by Infidigious** [comment]
> hell its not even deletion you can still post in them

If he knew how to automate issue deletion he would have done it probably

**Comment by Infidigious** [comment]
> Mental Outlaw goes brrrrrrrrrrrrrrr

Yes funny outlaw
