### ISSUE TITLE
You just destroyed your work, career and probably your online life.

### ISSUE THREAD

**Issue by pPkMnh4to8994h** [RIAEvangelist/node-ipc#567]
This looks messy. Was it worth it, man?

**Comment by expeditiousRubyist** [comment]
That's nothing. Dude's going to jail.

**Comment by pPkMnh4to8994h** [comment]
@expeditiousRubyist Nothing is decided yet. Anything can happen, especially nowadays. I only want to know what he feels right now.

**Comment by expeditiousRubyist** [comment]
@pPkMnh4to8994h While it is true that nothing has been decided yet, it is abundantly clear that what he has done constitutes a crime. What remains to be determined is:
1. Will the FBI choose to investigate
2. Will the DOJ choose to prosecute
3. Will the jury convict

I expect with enough complaints from his victims, 1 will be true. 2 is likely if the FBI finds from the evidence that what he has done constitutes a crime (it should, particularly under the CFAA), and 3 is likely if the jury is not incredibly stupid, or the prosecutor incredibly incompetent. But hey, I'm not a lawyer, so maybe my predictions are wildly inaccurate. But I do know that the legal counsel of one of his victims recommended pressing federal criminal charges.

**Comment by pPkMnh4to8994h** [comment]
@expeditiousRubyist I see.
Well, let's see what happens. I wonder if anyone actually had actually suffered data loss.

**Comment by pPkMnh4to8994h** [comment]
You're not even reading these, I presume. Well, fuck you too then.
