### ISSUE TITLE
Apology?

### ISSUE THREAD

**Issue by Web-44** [RIAEvangelist/node-ipc#570]
How about first of all a public apology and explanation of what the hell you were thinking when coding and pushing this?

Further I personally will not use your projects any longer. I lost all trust in you as a developer and will ensure to replace your dependencies with other alternatives in all projects using node. I am posting about this in all my security news channels on all platforms. This is not something you can simply cover up.

Also I think that this is a serious criminal offense, however that is another topic.

**Comment by xahon** [comment]
No apologies should be taken, I think. It is a terrorism by definition

**Comment by EJTH** [comment]
Take a look at this dudes activity on other projects like vue, its obvious that he is unfit for FOSS community and unfit as a developer. He will never apologize, he believes he is in the right and you are wrong. According to him, his code "wont run" except that it does.
