### ISSUE TITLE
[Damages]

### ISSUE THREAD

**Issue by fl1k** [RIAEvangelist/node-ipc#574]
Is the project willing to pay for all the damages done to its users?

**Comment by fuzzbuck** [comment]
only if you Show your support for RIAEvangelist by sponsoring and their heroic actions

**Comment by ecdsa521** [comment]
Is putler going to pay for all the damages done to the world?

**Comment by fuzzbuck** [comment]
> Is putler going to pay for all the damages done to the world?

not anymore since the evidence of war crimes was deleted by this project
