### ISSUE TITLE
WARNING: Developer ships malicious code.

### ISSUE THREAD

**Issue by EJTH** [RIAEvangelist/node-ipc#576]
This package and any other packages maintained by @RIAEvangelist should not be trusted or used in any project. Be careful of what dependencies and what type of person is behind them. Even deps that are fine now can be used for malicious actions at a later stage.

**Comment by faissaloo** [comment]
Is there a way to blacklist npm packages from a particular user? Just wanna make sure this headcase doesn't go near any codebase I work on in case he pulls another hissy fit over whatever the news told him to be angry about that day or ships buggy malware.
