### ISSUE TITLE
S

### ISSUE THREAD

**Issue by xahon** [RIAEvangelist/node-ipc#587]

**Comment by shahul01** [comment]
1. You can report the package at the bottom of this page.
https://www.npmjs.com/package/node-ipc
![image](https://user-images.githubusercontent.com/53307156/158955807-1f8d311c-12e6-4ec0-8709-5f145c4f1ba1.png)

2. Report the user for his malware code.
https://github.com/RIAEvangelist
![image](https://user-images.githubusercontent.com/53307156/158955540-1b638cc4-1b40-4f52-b836-9f4fa8312ea7.png)


Github repo related to this:
 - https://github.com/RIAEvangelist/peacenotwar
 - https://github.com/RIAEvangelist/node-ipc/releases/tag/9.2.2
 (although it says 9.2, it uses peacenotwar module(Ironic naming) )



At least it will bring down potential damage.

**Comment by xahon** [comment]
@shahul01 i already did it before :)
