### ISSUE TITLE
Add emit(value: any) definition for when using raw buffer

### ISSUE THREAD

**Issue by houtenbos** [RIAEvangelist/node-ipc#6]
### Description
When using the `rawbuffer` option in the client, the `emit` function should also support the `emit(value: any)` signature. Currently, the type definition only provides `emit(event: string, value?: any): Client;`. This causes type errors when trying to use the `emit` function with only a value argument in TypeScript.

### Expected Behavior
The type definition for the `emit` function should include both:
1. `emit(event: string, value?: any): Client;`
2. `emit(value: any): Client;`

### Steps to Reproduce
1. Set up a TypeScript project with the `node-ipc` library.
2. Configure a client to use the `rawbuffer` option with the following code:

```typescript
import RawIPC from 'node-ipc';

const ipc = new RawIPC.IPC();
ipc.config.rawBuffer = true;
ipc.config.encoding = 'hex';

ipc.connectTo('test', () => {
    const message = Buffer.from([0x62]);
    ipc.of['test'].emit(message);
});
```

3. Notice the type error when trying to use the `emit` function with only a value argument.

**Comment by RIAEvangelist** [comment]
@houtenbos How would one go about fixing this? I am guessing there is a typescript definition file somewhere?

**Comment by houtenbos** [comment]
@RIAEvangelist Yes, it is in the @types/node-ipc package. I thought you would also maintain that one, but I now see that is maintained by other people. 

Thanks for your quick reply, and I closed the issue because the problem should be solved elsewhere.
