### ISSUE TITLE
Add node-ipc to awesome-nodejs

### ISSUE THREAD

**Issue by Rokt33r** [RIAEvangelist/node-ipc#61]
I think this module should be listed there because of its awesomeness!!
https://github.com/sindresorhus/awesome-nodejs

**Comment by RIAEvangelist** [comment]
requested

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
