### ISSUE TITLE
Which is faster: process.fork/send or node-ipc?

### ISSUE THREAD

**Issue by gajus** [RIAEvangelist/node-ipc#63]
I have a node process that uses `process.fork` to distribute tasks. However, I have learned that communication via master and child process via `process.send` is relatively slow.

Which is faster for sending large JSON objects: core IPC or `node-ipc` module?

**Comment by RIAEvangelist** [comment]
I'm not totally sure which would be faster, using unix sockets would be the way to go with node-ipc. 

But, you might consider sending multiple smaller objects instead of one BIG object.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
