### ISSUE TITLE
is there a way to know when a message is fully 'emitted' on the socket?

### ISSUE THREAD

**Issue by Mostafa-Samir** [RIAEvangelist/node-ipc#64]
consider the following client that sends a termination message to a running ipc server and then immediately disconnects from the server

```javascript
ipc.connectTo('world', function() {
    ipc.of.world.emit('terminate', {});
    ipc.disconnect('world');
});
```
because `emit` is an asynchronous process, when the client disconnects the message wouldn't have been fully written to the socket and the server won't receive the message.

so, does the module provide any thing to check if the message is fully written on the socket so that it could be known when its safe to disconnect the client?

I attempted to add a callback to the `emit` method that would be triggered after the message was written to the socket, but I thought I should check if an alternative already exists. 

Thanks.

**Comment by RIAEvangelist** [comment]
when you emit the terminate message does the other end not hangup?

***I don't think*** this exists right now. The main reason to avoid it would be performance under heavy load. If you don't need a callback, but have an if statement checking for it say 800 times per second that would slow your code down some do to the  unnecessary overhead. Many applications do use this for real time communication either via rawBuffer, or even the standard json implementation.

The most efficient way to do this would be to have the other end close the socket if you send a terminate message.

The next best... would be a set timeout for like 1 to 5 ms.

**Comment by Mostafa-Samir** [comment]
Thank you,

I went with the solution to have the other end close the socket when it receives the terminate message using `socket.destroy()` or `socket.end()`. There was a minor issue in the client with that solution, it raised an **ENOENT** error and kept retrying to connect to the server after the socket was closed on the other end. I solved that by adding a listener for the `end` event on the socket on the client that calls `ipc.disconnect`. So the following seems to work:

```javascript
ipc.connectTo('world', function() {
    ipc.of.world.emit('terminate', {});
    ipc.of.world.socket.on('end', () => ipc.disconnect('world'));
});
```
Thanks again.

**Comment by RIAEvangelist** [comment]
Did you bind to the close event?

You also can change your max reconnect trys and duration in the config.

**Comment by Mostafa-Samir** [comment]
Yeah I attempted to bind to the `close` event, the callback wasn't invoked until after one **ENOENT** error was raised and one attempt to retry is made. When I set the `maxRetries` to 0, it raised the exception then invoked the callback. However when I bind to the `end` event it invokes the callback immediately without raising the exception.

**Comment by RIAEvangelist** [comment]
Also, just for future reference, you can listen for the ` error ` event toi catch things like ***ENOENT***

**Comment by Mostafa-Samir** [comment]
Thanks :+1:

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
