### ISSUE TITLE
Writing to stdout from within server.on.app.message throws an error

### ISSUE THREAD

**Issue by singhshashi** [RIAEvangelist/node-ipc#65]
I have an ipc server set up as follows: 

```
var output = new nativeMessage.Output();

ipc.serve(function(){
  ipc.server.on('app.message', function (data, socket) {
    var pingFromMyApp = {"message":"pingfrommyapp"};
    output.end(pingFromMyApp);
    ipc.server.emit(socket,'app.message', {id: ipc.config.id, message: data.message+' I can hear you too!'});
    process.stdout.write(pingFromMyApp);

  })
});
```

nativeMessage.output() transforms the object pingFromMyApp to bytes in the format required by chrome native messaging api. I am using https://github.com/jdiamond/chrome-native-messaging to do that. 

However, I get an exception on process.stdout.write(pingFromMyApp) : 

>  {"message":"pingfrommyapp"}net.js:617
>     throw new TypeError('invalid data');
>     ^
> 
> TypeError: invalid data
>     at WriteStream.Socket.write (net.js:617:11)
>     at Object.<anonymous> (/home/shashi/WebstormProjects/NodeJsConsoleApp/index.js:22:20)
>     at Object.pub (/home/shashi/WebstormProjects/NodeJsConsoleApp/node_modules/event-pubsub/event-pubsub.js:69:19)
>     at Object.trigger (/home/shashi/WebstormProjects/NodeJsConsoleApp/node_modules/event-pubsub/event-pubsub.js:111:21)
>     at Socket.<anonymous> (/home/shashi/WebstormProjects/NodeJsConsoleApp/node_modules/node-ipc/dao/socketServer.js:251:44)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
>     at Socket.Readable.push (_stream_readable.js:110:10)
>     at Pipe.onread (net.js:523:20)

Is this happening because for the thread executing, the stdio is piped to the socket? Is it possible to to just output to stdio? I am not quite sure what's happening.

**Comment by singhshashi** [comment]
This may not have to do with node-ipc but how I am using the chrome-native-messaging

**Comment by RIAEvangelist** [comment]
:+1:

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
