### ISSUE TITLE
Help with C++ socket messages

### ISSUE THREAD

**Issue by mattrmunson** [RIAEvangelist/node-ipc#66]
I'm trying to get the [Unix server example](https://www.npmjs.com/package/node-ipc#server-for-unix-sockets-windows-sockets--tcp-sockets) to work with a simple [c++/boost::asio client](http://www.boost.org/doc/libs/1_53_0/doc/html/boost_asio/example/local/stream_client.cpp). I got the node-ipc server working with the node-ipc client, and I can connect with the c++ client. But, when I send a short message (eg. "hello"), the server just logs `Implementing larger buffer for this socket message. You may want to consider smaller messages.` and doesn't send a response. 

I tried using strace -p to see what messages the programs are really sending. Apparently the c++ client is sending exactly what I type, but I noticed the node-ipc client seems to send the string `{\"type\":\"message\",\"data\":\"hello\"`  (with the end cut off from strace output) and length of 34. So it seems like node-ipc is parsing the socket with some protocol, and maybe this is why it doesn't respond properly to the c++ client?

**Comment by mattrmunson** [comment]
I got the node-ipc server to respond by modifying the c++ client with the code:

```
std::string msg = "{\"type\":\"message\",\"data\":\"hello\"}\f";
std::cout << boost::asio::write(s, boost::asio::buffer( msg.c_str(),  msg.size()));
```
But now the c++ client is not acknowledging the server response. I took a look at the client with strace and saw that it is receiving the message 

`recvmsg(6, {msg_name(0)=NULL, msg_iov(1)=[{"{\"type\":\"message\",\"data\":\"hello "..., 1024}], msg_controllen=0, msg_flags=0}, 0) = 41`

It turns out that, if I set `request_length` for  `boost::asio::buffer(reply, request_length)` to 41 or less, the client will register the response (though message is truncated and server logs an error if its less than 41). So I guess boost::asio::read() needs to know the length of the message? Which doesn't make sense.

I also noticed that node-ipc uses `read(13,...` and `write(9,...`, whereas boost::asio is using `sendmsg(6,...` and `recvmsg(6,...`, and I don't know whether that's relevant or not. 

Any help here would be much appreciated.

**Comment by RIAEvangelist** [comment]
Things I would check :

### concat and check for delimiter in C++
if this is too small your messages will need to be stitched together and split on the delimiter you have set in node-ipc. (that's actually why the delimiter is there)

both sides can determine a full message is available by the presence of a delimiter. This is the best way to do it incase messages are coming rapidly and possibly have more than one in a buffer.

Split the string on the buffer before parsing it as json.

pseudo code idea below

```

buffer filled or dispatched {
  if !contains delimiter {
    save to a variable and concat on next buffer and recheck for delimiter
  }else{
    do your thing
  }
  
```

### make C++ buffer bigger

this might be easier, just make the buffer bigger in your C++ code

---

both ways should work

**Comment by RIAEvangelist** [comment]
As an aside, I have worked on projects with C and C++ using Janson as the JSON lib.

Also, there is a RawBuffer member in the config. That might be of help to you as well. But primarily I think the concat and check for delimiter in C++ is the best way to handle this.

**Comment by RIAEvangelist** [comment]
FYI, depending on what you are doing you might also benifit from the sync setting in the config too. With that node requires some kind of ack | nack before sending the next message

**Comment by mattrmunson** [comment]
You're right, the delimiter was the key. It turns out I was using some boost streambuff setting that was waiting until a minimum number of characters are in the buffer before reading. So it was never reading the message unless that minimum number was less or equal to the length of the message. So I switched to using `boos::asio::read_until()` and now it reads in everything up until the delimiter. Works like a charm. 

Btw, I wonder if you would mind answering some questions about speed.
1)When the number of clients connected is 1, is there a significant latency difference between `emit()` and `broadcast()`?
2)formatting a string into JSON before sending must cost some time. Can I reduce latency much by skipping that step?
3)does RawBuffer affect latency?
4)I want absolute minimum latency, is there anything else I should know?

**Comment by RIAEvangelist** [comment]
:+1: 

1. no, the only additional latency would be the creation of the for loop, so I expect for 1 client this would be less than 1ms.
2. yes, use the raw buffer setting I mentioned earlier. This will remove any latency with that and instead send a raw buffer. It might make things easier and faster for you in C++ as well.
3. Any code you write will inherently add latency, even defining a variable. I have done many perf tests to see how things as basic a var vs const vs let effect latency. Raw Buffer should be your best bet, especially since it means you don't need to parse or format the JSON in your C++ either.
4. try to keep your messages as small as feasible. This will allow you to write more asynchronous methods which in turn will allow the processing of messages and execution of methods to begin as soon as they get what they care about. This will give a tangible feel of it being faster when you have thousands of clients connected at the same time. You should do this for any code, not just related to node-ipc, its a good trick for responsive feeling functionality. Sometimes async can seem daunting, but its worth it if you want the performance.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
