### ISSUE TITLE
PubSub library built from node-ipc :)

### ISSUE THREAD

**Issue by bluejamesbond** [RIAEvangelist/node-ipc#67]
Just thought I would share a dependency.
https://github.com/bluejamesbond/PubSub.js

Feel free to close as needed.

Thank you for the great library!

**Comment by RIAEvangelist** [comment]
:+1:  Awesome! thanks for the news, I'll keep an eye on it!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
