### ISSUE TITLE
How do node-ipc conmunicate with server of Unix-domain sockets in C language ?

### ISSUE THREAD

**Issue by zhang007z** [RIAEvangelist/node-ipc#68]
I see your example that client and server all use node.js for communication between them.if my server is Unix-domain sockets framework in C language, please I want to ask that can your node-ipc communicate with it ?

**Comment by RIAEvangelist** [comment]
Yes. It can. Just send messages to the socket.

There is a guide to unix sockets in the README.txt.

remember to look for the delimiter. Or set rawBuffer to true in the config.

**Comment by zhang007z** [comment]
thanks RIAEvangelist
first problem:
if I use your node-ipc to send json message to unix sockets,which mode of node-ipc can complete it?  this unix sockets end is completed in C language.   
second problem:
I use node-ipc to send json message to the received-end server process that is based on Unix-domain sockets model. if node-ipc as client adopts TCP protocal for sending json to the received-end, in this case  may the received-end receive incomplete json data package? because of TCP protocal is stream protocal.if node-ipc uses UDP protocal for this thing,can this unix sockets server process receive complete json message data package?

**Comment by RIAEvangelist** [comment]
@zhang007z 
1) please use the unix socket settings. They are documented in the readme. It is very easy.

2) your buffer on the c side is probably too small either stich your buffers by checking for the delimiter or increase your buffer size. I recommend checking for the delimiter though.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
