### ISSUE TITLE
Listen to client events

### ISSUE THREAD

**Issue by valette** [RIAEvangelist/node-ipc#69]
Hi,

on the server-side, it is possible to listen to events using ipc.of[serverId].on(), but it seems this is not possible to do this on the client side. Is this functionality difficult to implement?

Thanks

**Comment by valette** [comment]
OK, got it, after invoking ipc.connectTo(), ipc.of.socket can be listened to...

Sorry for the noise

**Comment by RIAEvangelist** [comment]
:+1:

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
