### ISSUE TITLE
In Client log received is misspelled 

### ISSUE THREAD

**Issue by mwshortt** [RIAEvangelist/node-ipc#71]
Client logs: `## recieved events ##`; received is misspelled. Should be: `## received events ##`.

**Comment by mwshortt** [comment]
PR created: https://github.com/RIAEvangelist/node-ipc/pull/70/files

**Comment by RIAEvangelist** [comment]
merged

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
