### ISSUE TITLE
ZeroMQ vs Node-ipc

### ISSUE THREAD

**Issue by Dillybob92** [RIAEvangelist/node-ipc#74]
Hey guys,

Just curious, is node-ipc generally faster than ZeroMQ for local communication only?

**Comment by RIAEvangelist** [comment]
It should be, but not sure, would be awesome to have benchmarking. node-ipc is being used in many real time applications.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
