### ISSUE TITLE
server socket don't fire disconnect on client disconnection

### ISSUE THREAD

**Issue by jjp91** [RIAEvangelist/node-ipc#75]
Hello,

I use node 4.4.4, and the TCP server mode.

The connection goes well, 'connect' is fired on the server and the client, but if I kill the client process, there is just a message (ipc.log) on the server but the event 'disconnect' is not fired on the server.

If i kill the server process, the 'disconnect' event fires normaly on the client.

Thank you.

**Comment by wjagodfrey** [comment]
Confirmed on `node 6.1.0` with this code:

```
const ipc   = require('node-ipc');

// ipc configuration
ipc.config.id       = 'test';
ipc.config.silent   = true;
ipc.config.retry    = 1500;

ipc.serve( () => {
  ipc.server.on('disconnect', () => {
    console.log('Disconnect event fired');
  });
});

ipc.server.start();
```

**Comment by RIAEvangelist** [comment]
can you supply some more info on this?

What was expected and didn't happen? the disconnect did not fire?

**Comment by wjagodfrey** [comment]
Yes at least from my perspective, I was hoping there would be a disconnect event for each client, so that I could clean up any client state. Connect events were firing but disconnect events were not.

It seems that we are both getting this (absence of) behaviour for both TCP and UNIX socket servers.

**Comment by Stealthmate** [comment]
Looking through the source, it seems that the server fires a 'socket.disconnected' event, which you can listen for, however that's missing from the docs. Perhaps this is a name mismatch? Or maybe something internal which we aren't supposed to catch at all?

**Comment by RIAEvangelist** [comment]
It may just be missing from the docs. I'll have a look. Thanks @Stealthmate

**Comment by RIAEvangelist** [comment]
@Stealthtate you are correct. It is missing from the docs. Do you want to add it? If not I will.

Thanks again for answering this.

**Comment by niklas112** [comment]
Great! This is exactly what I needed. But how can I identify the client with this event?
Thanks in advance

**Comment by RIAEvangelist** [comment]
@Stealthmate just  documented this in the readme.

```javascript

                        ipc.server.on(
 				'socket.disconnected',
 				function(socket, destroyedSocketID) {
 					ipc.log('client ' + destroyedSocketID + ' has disconnected!');
 				}
 			);


```

:+1:

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
