### ISSUE TITLE
What happens when client lost network and tries to send data?

### ISSUE THREAD

**Issue by pdaddy26** [RIAEvangelist/node-ipc#76]
Hi, 

I'll be using TCP and I was wondering what will happen when the clients send data when there is no network? Is the data lost forever lost, so the client must start buffering the data? Is there a way to get notified when the send data didn't work because of no network? Or is TCP handling all of this already?

Thanks,

**Comment by RIAEvangelist** [comment]
It should be.

closed from age.

**Comment by pdaddy26** [comment]
Sorry I didn't understand, what should it be doing in that scenario?

**Comment by RIAEvangelist** [comment]
TCP should give you an error. Otherwise you can watch the connectivity.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
