### ISSUE TITLE
Not sure which type of socket to use

### ISSUE THREAD

**Issue by Dillybob92** [RIAEvangelist/node-ipc#77]
----
#### Types of IPC Sockets

| Type      | Stability |Definition |
|-----------|-----------|-----------|
|Unix Socket or Windows Socket| Stable    | Gives Linux, Mac, and Windows lightning fast communication and avoids the network card to reduce overhead and latency. [Local Unix and Windows Socket examples ](https://github.com/RIAEvangelist/node-ipc/tree/master/example/unixWindowsSocket/ "Unix and Windows Socket Node IPC examples")  |
|TCP Socket | Stable    | Gives the most reliable communication across the network. Can be used for local IPC as well, but is slower than #1's Unix Socket Implementation because TCP sockets go through the network card while Unix Sockets and Windows Sockets do not. [Local or remote network TCP Socket examples ](https://github.com/RIAEvangelist/node-ipc/tree/master/example/TCPSocket/ "TCP Socket Node IPC examples") |
|TLS Socket | Stable    | Configurable and secure network socket over SSL. Equivalent to https. [TLS/SSL documentation](https://github.com/RIAEvangelist/node-ipc/tree/master/example/TLSSocket) |
|UDP Sockets| Stable    | Gives the **fastest network communication**. UDP is less reliable but much faster than TCP. It is best used for streaming non critical data like sound, video, or multiplayer game data as it can drop packets depending on network connectivity and other factors. UDP can be used for local IPC as well, but is slower than #1's Unix Socket or Windows Socket Implementation because UDP sockets go through the network card while Unix and Windows Sockets do not. [Local or remote network UDP Socket examples ](https://github.com/RIAEvangelist/node-ipc/tree/master/example/UDPSocket/ "UDP Socket Node IPC examples") |  

| OS  | Supported Sockets  |
|-----|--------------------|
|Linux| Unix, Posix, TCP, TLS, UDP|
|Mac  | Unix, Posix, TCP, TLS, UDP|
|Win  | Windows, TCP, TLS, UDP      |  

My game basically runs multiple node instances behind a nginx reverse proxy. But, when a player joins another player's games **that is not on their instance**... I need to use IPC so I can communicate. (Sending player's movement data, etc, etc) 

 I can use Redis Pub/Sub, but I think node-ipc has less overhead, right? Which type of IPC socket would be the best for my scenario? Thank you!

**Comment by jjp91** [comment]
Hello,

I think Redis would be quicker, and specialy if you use sub on multiple process/server at the same time.

But if you still want to use Node for IPCs, use the Unix Socket, it is quicker than the NetworkCard.

Be aware that Node is an interpreted language, so more you use third parties the more your programms will be faster.

**Comment by Dillybob92** [comment]
@jjp91 Thanks for the response! 

Yeah, I'm kind of stumped right now. I have 3-4 node instances up, but when two players join the same game (but on different instances) I would need to use Redis or IPC to send data between them. It seems like extra overhead regardless. Would putting them on the same instance be a better solution and then just have "Channels" where players can switch to?

**Comment by jjp91** [comment]
Hello Dilllybob92,

What do you mean by "instance", you mean processes?
If you have 4 processes, it will be quicker because processors have several cores now, if you use all the cores of your processor, you will be faster.

Never forget that Node is node threaded, this means that nothing is "parallel", so when your process is doing something, it is not doing something else.

Do you send binary data?

**Comment by Dillybob92** [comment]
@jjp91 Yeah,processes. Are you talking about node-ipc will be faster (Since it's processes,not servers)?  And yeah, it's a quad core server. I run 3 node instances (websocket server) behind a nginx reverse proxy/load balancer. Then players can join other games, etc.

I'm just stumped because it seems like if a player joins another players game that isn't on the same instance as them... I have to basically communicate through the socket (or Redis/Pub/Sub) on every single movement skill a player does. It seems like it would be easier to just transfer that player to the correct instance before joining the game.

But, then, when that play leaves that game.. and then creates a new game, it will be on that instance that they were transferred to! Which means nginx's load balancer = useless because a lot of players could end up one instance instead of being spread out equally.

And yeah, binary!

**Comment by jjp91** [comment]
@Dillybob92 

Look, i'm not talking about games, just computing systems, when i mean binary, it means not text.

Are you sure  you want to send NOT text messages between processes?

**Comment by Dillybob92** [comment]
Probably not, binary would be the most fastest, right? If so, yes I already am using binary, so you recommend node-ipc for local processes and Redis` Pub/Sub for server communication?

**Comment by jjp91** [comment]
If not text, Redis or Node-IPC will be great but not in binary mode, use Node-IPC with Unix Domain Socket, it will be great.

Binary is not a good idea because Node-IPC turn binary in hex encoding which double the size of the data sent, and Redis manages not very well binary data.

**Comment by Dillybob92** [comment]
Okay @jjp91 Thanks for time, really appreciate it!!

**Comment by jjp91** [comment]
You're welcome, i'm sure you're doing great gaming :-)

**Comment by mirague** [comment]
@Dillybob92 Which of the methods did you choose in the end? Has it been performant?

**Comment by Dillybob92** [comment]
@mirague Unfortunately, I took a different approach for IPC. I basically will only use it to communicate between processes for basic events (chatting, pming a player, etc) -- not for any high intensive tasks like player movement, updating skills or whatnot. I decided to create a custom "load balancer" if you will, and just put players on separate 5$ nodejs game instances (with 1 core) to handle all the player to player communication.  I think that way is better to horizontally scale, and have less latency since players will be put on the same node. So no IPC is involved (on their instances) -- but for the "Central / Load Balancing" server, this module has been great for performant and auto switches to unix sockets when I switch to debian. It's great and so easy and love the module here. Very underrated :)

**Comment by jjp91** [comment]
If you want very fast communication between servers and processes, the best is NATS, you put the downloadable command "gnatsd" in your directory, and run. There is a NATS driver for node which is quick also.

**Comment by mirague** [comment]
@Dillybob92 Thanks for your reply! Do you think `node-ipc` can be performant enough to pass these messages at a high interval? Or have you benchmarked it in a way and found it lacked performance at a certain throughput?

Also, these 5$ instances are monthly instance-prices for which you pay per hour? Thanks again!

**Comment by Dillybob92** [comment]
@mirague I think only on linux servers because of the RAW unix sockets. But, I did test it with high interval message passing (player movement, etc) and it's fine. It's just I didn't want to stick everything into one server (Even if using multiple node instances) -- I think it's just easier to scale out with the cheap 3-5$ VPS's instead of spending 70$ for a good dedicated server.  That's just me personally though :P.  And yeah, they are per month.  Digital Ocean / OVH / BuyVM / RamNode. The best of the best

@jjp91 Never heard of NATS until now.. That seems promising, I'm too far in though to switch though haha.

**Comment by jjp91** [comment]
@mirague 
The pb is not node-ipc, the pb is node.

**Comment by mirague** [comment]
@jjp91 What's a PB?

**Comment by jjp91** [comment]
@mirague 
Sorry, it's a mistake, forget it. I remove it.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
