### ISSUE TITLE
Error: Messages are large, You may want to consider smaller messages.

### ISSUE THREAD

**Issue by antitoxic** [RIAEvangelist/node-ipc#79]
I'm having his error with the example setup. I tried to figure out what it means from the code but I couldn't. 

The messages I'm sending are not that large

**Comment by antitoxic** [comment]
Example:

```bash
node ./ipc-example.js
# in anotther terminal:
echo "what"  | nc -U /tmp/app.world
```
The output is the error.

**Comment by mirague** [comment]
You need to send in a valid JSON object in the following format:
```
{ "type": "yourType", "data": { "foo": "bar" } } \f
```

Note that the library is looking for a `\f` in the very end of the message.

**Comment by attfarhan** [comment]
I've just run into this issue.  Tried the above solution but faced the same error.  

The command I'm running is:
`echo  { "type": "message", "data": { "editor_type": "vscode", "filename":"~/test.go", "cursor_offset": "3", "selected_token": "fmt", "file_buffer": "fmt"} } \f | nc -U /tmp/app.sourcegraph`.  Any other suggestions?

**Comment by RIAEvangelist** [comment]
instead of echoing from the command line, try sending from javascript for testing.

you can output what your sending and then try from there. It is entirely possible that your commandline is not working because it has chars that need escaping.

**Comment by RIAEvangelist** [comment]
also you can specify raw buffer and such in the config if you don't want JSON.

**Comment by jimarlet** [comment]
Use the 'pr' command, it will append the Form Feed control character that node-ipc is looking for as a delimiter:
`pr -tF test.json | nc -U /tmp/app.world`

test.json:
`{ "type": "message", "data": { "foo": "bar" } }`

Output:
`received event of :  message { foo: 'bar' }`

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
