### ISSUE TITLE
client.disconnect() doesn't disconnect

### ISSUE THREAD

**Issue by joewalker** [RIAEvangelist/node-ipc#83]
My code does `client.disconnect(client.config.id);`

"disconnect" calls `this.of[id].off('*');` ([see here](https://github.com/RIAEvangelist/node-ipc/blob/master/services/IPC.js#L97)).

"off" is defined in event-pubsub, and it calls `unsub(...args)` ([in a round about way](https://github.com/RIAEvangelist/event-pubsub/blob/master/event-pubsub.js#L108)) so in effect, we're calling `unsub('*');`.

But unsub expects 2 parameters, and throws if the second isn't provided ([here](https://github.com/RIAEvangelist/event-pubsub/blob/master/event-pubsub.js#L17)).

Hence, clean disconnection doesn't seem possible.

**Comment by RIAEvangelist** [comment]
Thanks this must be related to the latest event-pubsub

Well get on it.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
