### ISSUE TITLE
Socket.on('data'): Pass data as JSON object instead of a string

### ISSUE THREAD

**Issue by mirague** [RIAEvangelist/node-ipc#86]
We're wrapping our own `EventEmitter` class around a Connection since we have several Transports in our application (WebSockets and TCP). We'd like to have a catch-all event listener so that we can "bubble up"/re-emit any events that are happening.

Right now we worked around this by listening for the `'data'` event on the Socket, but it passes in a string of the payload - requiring us to parse it. This works, but creates extra overhead as the library is already parsing the JSON-payload.

What we got:
```
socket.on('data', (data) => {
  let parsed;
  try {
    parsed = JSON.parse(data.trim());
  } catch (err) {
    logger.error('Could not parse incoming data on TCP socket: ', data);
    return;
  }
  
  if (parsed.type && parsed.data) {
    this.emit(parsed.type, parsed.data);
  }
});
```

Question is, can we have a flag of some sorts to indicate messages being re-thrown? Or at least indicate we want to have the data already parsed instead of having it passed on as a string?

**Comment by RIAEvangelist** [comment]
Are you binding directly onto the underlying socket instead of using the framework?

**Comment by RIAEvangelist** [comment]
In the framework you just bind to the * event.

.on('*',catchAll)

The catch-all recieves (type,data) string, json

**Comment by RIAEvangelist** [comment]
Lmk if that's what you were looking for.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
