### ISSUE TITLE
Ability to Remove an Event Listener on Socket

### ISSUE THREAD

**Issue by mirague** [RIAEvangelist/node-ipc#87]
Right now you can do:

```
function handleEvent(data) {
   // do stuff with data
}

socket.on('data', handleEvent);
```

What's missing is a way to remove the handler when one needs to, such as:
```
socket.off(handleEvent); // or
socket.unsub(handleEvent); // or
socket.removeEventListener(handleEvent)
```

**Comment by RIAEvangelist** [comment]
.off works well.

**Comment by RIAEvangelist** [comment]
This is built into node-ipc since the beginning.

**Comment by mirague** [comment]
Heya! Appreciate the response.

It seems to work on the `server` object, but not directly on the `socket`

**Comment by RIAEvangelist** [comment]
I think you should use the framework as described in the documentation.

I am not sure why you are trying to use the raw sockets. In all the examples you will see `  ipc.of.socketNameHere.on ` or `  ipc.of.socketNameHere.off `

```javascript

 ipc.connectTo(
        'world',
        function(){
            ipc.of.world.on(
                'hello',
                function(data){
                    ipc.log(data.debug);
                    //if data was a string, it would have the color set to the debug style applied to it
                }
            )
        }
    );

```

**Comment by mirague** [comment]
I'm using the raw socket because I have my own wrappers around "connections" since we needed to abstract between clients connecting over WebSockets and TCP. When we instantiate a "connection" we pass in the Socket so that we can have our own logic over it.

Using the "server" does not work in this scenario, as we care about the socket itself. We can monkey-patch it to work our way though.

**Comment by RIAEvangelist** [comment]
Why not extend IPC?  The core class is exposed for just this reason. Otherwise you are not using node-IPC, you are just using raw sockets. So you will need to write everything from scratch. I think extending IPC is probably the best idea.

**Comment by RIAEvangelist** [comment]
Will the PR Feature that @DutchKev is working on help you? from #96 

Also as for raw socket events like you are talking about maybe try : 

```

socket.removeAllListeners([eventName])
socket.removeListener(eventName, handler)

```

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
