### ISSUE TITLE
Client fails to connect to Node server(TCP Sockets)

### ISSUE THREAD

**Issue by SunandoSamaddar** [RIAEvangelist/node-ipc#88]
So, I'm trying to pass messages between a node server(which uses both node-ipc and socket.io) and an Electron client.

Node server `ipc.config` below
```
ipc.config = {
	appspace        : 'app.',
	socketRoot      : '/tmp/',
	id              : 'test',
	networkHost     : 'localhost', //should resolve to 127.0.0.1 or ::1 see the table below related to this
	networkPort     : 9090,
	encoding        : 'utf8',
	rawBuffer       : false,
	sync            : false,
	silent          : false,
	logInColor      : true,
	logDepth        : 5,
	maxConnections  : 100,
	retry           : 1500,
	maxRetries      : false,
	stopRetrying    : false
};
```

Server code below - relevant portion
```
ipc.serveNet(
        ipc.config.networkHost,
        ipc.config.networkPort,
	function() {
		io.on('connection', function(socket) {
			socket.on('move', function(data) {
				//console.log(data);
				if(data.direction == 'F') {
					ipc.server.emit(socket, { type: 'app.move'}, { direction: 'F' });
				} else if(data.direction == 'L') {
					ipc.server.emit(socket, { type: 'app.move'}, { direction: 'L' });
				} else if(data.direction == 'R') {
					ipc.server.emit(socket, { type: 'app.move'}, { direction: 'R' });
				}
			});
		});
	}
);
ipc.server.start();
```

Electron client **index.html** inline JavaScript code below. **[I have included `<script type="text/javascript" src="node_modules/node-ipc/node-ipc.js"></script>` before the inline code]**
```
var ipc = require('node-ipc');

ipc.config = {
					appspace        : 'app.',
					socketRoot      : '/tmp/',
					id              : 'notTest',
					networkHost     : 'localhost', //should resolve to 127.0.0.1 or ::1 see the table below related to this
					networkPort     : 9090,
					encoding        : 'utf8',
					rawBuffer       : false,
					sync            : false,
					silent          : false,
					logInColor      : true,
					logDepth        : 5,
					maxConnections  : 100,
					retry           : 1500,
					maxRetries      : false,
					stopRetrying    : false
 };

ipc.connectToNet(
						'test',
						9090,
						function() {
							ipc.of.test.on(
									'connect',
									function() {
										ipc.log('## connected to test ##'.rainbow, ipc.config.delay);
									}
							);
							ipc.of.test.on(
									'moveIn',
									function(data) {
										ipc.log('command from node server '.debug, data);
									}
							);
						}
);
				
```

Electron client console throws the error below
```
IPC.js:85 requested connection to  test localhost
IPC.js:85 Connecting client via TCP to localhost 9090
IPC.js:85  
IPC.js:85 retrying reset
```

**Comment by RIAEvangelist** [comment]
That is not an error.

That is the initial connection happening.

I do not see the issue yet.

**Comment by RIAEvangelist** [comment]
Also, you should probably require node-ipc in the electron app not, include via script tag.

**Comment by SunandoSamaddar** [comment]
@RIAEvangelist The thing is the `ipc.server.emit()` does not reach the Electron client and yes, I have done `require('node-ipc');` in the client. Is there something else I can provide that may ease the debugging?

**Comment by RIAEvangelist** [comment]
There is one thing, if you could just toss up a hello world electron app It would help. That way when I get a spare moment I can just quick clone it and test. Also, add me as a contributor to the repo so if I figure something out, I can just push it up as an example for you.

**Comment by SunandoSamaddar** [comment]
@RIAEvangelist Okay I'll do that. Thanks. :)

**Comment by RIAEvangelist** [comment]
@SunandoSamaddar any progress?

**Comment by SunandoSamaddar** [comment]
@RIAEvangelist Not really. You can check [this repo](https://github.com/SunandoSamaddar/igorbrbr)...this is the code that I'm using now.

**Comment by RIAEvangelist** [comment]
+1

**Comment by SunandoSamaddar** [comment]
@RIAEvangelist I added you as a contributor.

**Comment by RIAEvangelist** [comment]
perfect

**Comment by RIAEvangelist** [comment]
Did you even look at the docs or examples?

I fixed it for you, but you were trying to use socket.io as the socket for ipc on the server, as well as you were trying to run both servers on the same port.

The errors you were getting back should have been a clue on that.

Next time try harder.

BTW I pushed fixes up. take a look.

**Comment by SunandoSamaddar** [comment]
@RIAEvangelist Hey, thanks a lot...thanks a lot. I wrote some seriously stupid and conceptually f***ed up code which I'm learning from now.

**Comment by RIAEvangelist** [comment]
:+1:  no problem ;)

**Comment by SunandoSamaddar** [comment]
Hello Brandon,

Remember you had touched upon my code after I added you as a contributor to
one of my repos https://github.com/SunandoSamaddar/igorbrbr. I was testing
your code yesterday and I found that you had made the same mistake(in the
edit) that I had originally made but it didn't catch your eye then so just
thought of letting you know. You can refer to *server/app.js* to check what
I'm talking about. The thing is the *socket.on('move', function(data) { *
*code** })* inside the *ipc.server.on* call is literally tied to *ipc
socket* variable (in your edit) but not the other socket at port 8000 which
listens for the *move* event that is fired when clicking a button in
http://localhost:8000. Can you tell me if there's a way I can retrieve the
other socket(*port 8000 socket*) from inside the *ipc.server.on*? I tried
putting *io.on('connection', function(socket8000) { code })* inside
*ipc.server.on* but that doesn't help.

Thanks,
Sunando

**Comment by RIAEvangelist** [comment]
the sockets should be named. then you can listen on them.

**Comment by SunandoSamaddar** [comment]
Hey, hope you're doing good. I worked through it, yes, you're right.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
