### ISSUE TITLE
8.8.0 version breaks Node LTS

### ISSUE THREAD

**Issue by Chocobozzz** [RIAEvangelist/node-ipc#89]
The cause seems to be the ES6 version of https://github.com/RIAEvangelist/event-pubsub that Node LTS (4.6) does not support.

http://pastebin.ca/3723743

**Comment by jmx** [comment]
Confirmed (installed as a dependent of jspm-watch (which requires node-ipc^7.0.0))

node_modules/event-pubsub/event-pubsub.js:56
    emit(type,...args){
              ^^^

SyntaxError: Unexpected token ...

**Comment by RIAEvangelist** [comment]
releasing a fix now which uses version detection to choose es5/es6 event-pubsub module

**Comment by RIAEvangelist** [comment]
Please confirm fix with v8.9.0

**Comment by RIAEvangelist** [comment]
I have confirmed on my end, but would like to be extra sure

**Comment by RIAEvangelist** [comment]
also LTS is now 6 ;) but should still be fixed for people who remain behind.

**Comment by Chocobozzz** [comment]
@RIAEvangelist I confirm this is fixed with 8.9.0. Thanks.

**Comment by RIAEvangelist** [comment]
:+1:

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
