### ISSUE TITLE
Using it with cluster

### ISSUE THREAD

**Issue by bsense-rius** [RIAEvangelist/node-ipc#91]
Been trying to use it as a means to communicate between forked processes but it fails. The goal is to avoid pivotting through master.

Anyway whenever I try to connect two forked processes the following error appears:
Error: write ENOTSUP
    at exports._errnoException (util.js:873:11)
    at ChildProcess.target._send (internal/child_process.js:611:20)
    at ChildProcess.target.send (internal/child_process.js:507:12)
    at sendHelper (cluster.js:722:8)
    at send (cluster.js:517:5)
    at cluster.js:492:7
    at SharedHandle.options.process.on.process.on.SharedHandle.add (cluster.js:86:3)
    at queryServer (cluster.js:484:12)
    at Worker.onmessage (cluster.js:432:7)
    at ChildProcess.<anonymous> (cluster.js:736:8)

I guess that it might be related the way node-ipc uses other child / etc. But dunno. I keep pivoting through the master process (the one that forks)... but it is not elegant.

**Comment by RIAEvangelist** [comment]
You will have to set up your processes to be clients but the parent to be a server for communication.

Alternatively, you could write a simple process manager that will spin up the child processes as actual separate children.

Cluster is an attempt to do what node-ipc allows you to do, but cluster is A LOT slower.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
