### ISSUE TITLE
client identifiers on server

### ISSUE THREAD

**Issue by DutchKev** [RIAEvangelist/node-ipc#92]
When using node-ipc to communicate between NodeJS processes over IPC, it seems pretty simple to start a server and listen for connections, or create a client and connect to the server.

But there is something that doesn't seem all that simple:

> *How can the server push a message to a client?*

The manual says, 

**On the client, listening to the server for a message**: 

    ipc.connectTo('world', function(){
            ipc.of.world.on('hello', function(data){
                    console.log(data);
                }
            )
        }
    );

Pretty straightforward... But:

**On the server, sending a message**

    // Start server
    ipc.serve(function(){
    
        // Listen for connecting clients
        ipc.server.on('connect', socket => {
            // From here I can do ipc.server.emit(socket, 'message', {});
            // But I still do not know the ID of the client that just connected
        });
    });

So lets say I setup the server as the given example above, and the client connected.. Than later on in a different timeFrame, On the server side, you would expect this to be the way to send a message to the client:

    ipc.server.of[TheClientIdThatJustConnected].emit('myMessage')

But this does not work, as ipc.server.of is always an empty object and I still do not know the socket client IDs..

So the only way I can think of, is to start EVERY process as both a server and a client... Or after the client connected, I send an '_identification' event with a hardcoded ID and store that sockets in a separate object, but that doesn't make any sense, because the socket is already given in the on('connect') function of the ipc.serve()...

So, how does a node-ipc server send a message to a connected client?

Thanks!

**Comment by RIAEvangelist** [comment]
You would do this the same as any other socket library, like ws for websockets etc.

The accept function gives you a scope. you can either create event handlers in this scope with something like `event-pubsub` on a global Events class, or you can push the client sockets into an array or object for you to track.

My guess based on what you are describing is that you are looking for more of an `event-pubsub` type of communication.

```javascript

              function(data,socket){
                    ipc.log('got a message : '.debug, data);
                    ipc.server.emit(
                        socket,
                        'message',  //this can be anything you want so long as
                                    //your client knows.
                        data+' world!'
                    );

                    myEventPubSubInstance.on('someType',(...args)=>ipc.server.emit(socket,'message',...args));
                }

```

**Comment by RIAEvangelist** [comment]
also see the docs for the server

you can listen for messages from the client and respond.

you may also want to check the docs for the `server.broadcast` function. I think there may also be a server.clients?

**Comment by RIAEvangelist** [comment]
Although... I do like your idea of `ipc.server.of` however how will you know which client you want to dispatch to if you have like 300 clients connected without handling the naming yourself as described above.

If you can come up with an identification pattern and use case for me, I would be happy to add it.

**Comment by DutchKev** [comment]
Hi Ria, thanks for helping me out.. 

I will make a UML for my current use case, and I will have a a deeper look into the node-ipc source to see if I can help by creating a quick draft pull-request ..  I will try to get back to it by the end of the day

**Comment by RIAEvangelist** [comment]
will be in next release.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
