### ISSUE TITLE
Examples communicating in other languages, e.g. C?

### ISSUE THREAD

**Issue by Jodes81** [RIAEvangelist/node-ipc#93]
It would be awesome to have examples in other languages on how to communicate with the examples given. For example, in C with the unix domain sockets hello world examples.

I appreciate that it's a bit of a detour from the essence of node-ipc if that makes sense, but it would be extremely helpful!

**Comment by Jodes81** [comment]
I solved this here:

http://stackoverflow.com/questions/39841942/communicating-between-nodejs-and-c-using-node-ipc-and-unix-sockets/39848936#39848936

**Comment by RIAEvangelist** [comment]
Wow, nice, maybe you could do a PR with a C example?

That would be helpful for a lot of people I think.

:question: :tada:

**Comment by Jodes81** [comment]
Thanks - I definitely will! I've only just started using unix sockets, I'm still getting used to them, and using them in C and node-ipc and I think I still have a long way to go but I'll definitely do that once I have it working. Interestingly I just discovered that unix stream sockets are in fact bi-directional, even though I've read elsewhere that they're not. I actually [asked about this on stack exchange](http://stackoverflow.com/questions/39870196/if-unix-socket-sock-streams-are-unidirectional-how-is-node-ipc-bidirectional) as well. A lot to learn!!

**Comment by RIAEvangelist** [comment]
Very cool, when you have the chance to make just a basic example like one of the hello-client/world-server ones that would be much appreciated by all!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
