### ISSUE TITLE
Event-pubsub Update

### ISSUE THREAD

**Issue by raybooysen** [RIAEvangelist/node-ipc#94]
A direct dependency, event-pubsub released a new version 4.1.0 which seems to cause the unit tests for node-ipc to fail.

I've also had some issues today running node-ipc and webpack where event-pubsub is throwing with: 

```
Error = TypeError: server.on is not a function
```

**Comment by raybooysen** [comment]
For more context, we're using node-ipc 7.0.0.  Seems the package.json versioning for node-ipc at that time was `    "event-pubsub": "*",` which means we just pull the latest and greatest.

**Comment by RIAEvangelist** [comment]
In your app you can add event-pubsub 2.2.0 as a dep and it will satisfy node-ipc need and keep you from pulling latest.

sorry about that.

**Comment by raybooysen** [comment]
Thanks.

Would you accept a PR that moves to `save-exact` for all dependencies?

**Comment by RIAEvangelist** [comment]
in the next release we will be moving to specific release targets for modules and doing sequential releases for dependency updates.

**Comment by RIAEvangelist** [comment]
Just going through with everyone to see if we need to do anything further before publishing a patch update

**Comment by RIAEvangelist** [comment]
I created a new branch called v7.0.2

If you want to do a PR to update the `package.json` dependancies to be an exact version of event-pubsub, I will accept and publish.

Thanks @raybooysen !

**Comment by raybooysen** [comment]
Happy to do this on master so all future builds are exact?

**Comment by RIAEvangelist** [comment]
right now master requires v4.2.2 explicitly

but what I would like to do is get any of the other engine fields populated and release them as a patch to the old builds.

**Comment by RIAEvangelist** [comment]
btw thats as of 8.9.1

**Comment by raybooysen** [comment]
PR Submitted.  Let me know if there is anything else you'd need.

**Comment by RIAEvangelist** [comment]
worked out perfect :) thanks!

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
