### ISSUE TITLE
Are unix datagram sockets supported? 

### ISSUE THREAD

**Issue by Jodes81** [RIAEvangelist/node-ipc#95]
I want 2-way communication between C and NodeJS in "packets" - ie chunks of data, and AFAIK unix datagram sockets rather than unix stream sockets are the way to go. Does node-ipc support this?

**Comment by RIAEvangelist** [comment]
I believe this is what we are using for UDP no? I'll have to look at the code.

**Comment by Jodes81** [comment]
I know that UDP uses datagrams, but unix sockets have several modes. If you run `man socket` it gives several constants: `SOCK_STREAM`, `SOCK_DGRAM`, `SOCK_SEQPACKET' and a couple of others. For example, to create a socket at the moment in C to communicate with node, it has this :

```
 if ( (fd = socket(AF_UNIX, SOCK_STREAM, 0)) == -1) {
    perror("socket error");
    exit(-1);
  }
```
So if I wanted datagrams I could use SOCK_DGRAM` instead of `SOCK_STREAM`

**Comment by RIAEvangelist** [comment]
I am not sure, but I will have a look around and if we can do it we should.

Are DGRAM unix sockets faster? If so, this is definately something I would like to add.

**Comment by Jodes81** [comment]
That's a good question - I was going to do some benchmarks once I understand how it all works. It should be interesting. But everywhere I read, it says unix sockets are always faster than UDP because it doesn't involve the network stack (IIRC).

**Comment by RIAEvangelist** [comment]
I mean the unix SOCK_DGRAM

**Comment by RIAEvangelist** [comment]
unix socket that I have implemented is definitely faster than the UDP because of avoiding the network card.

**Comment by kentmw** [comment]
Did this get converted into an enhancement request? I also have need for establishing a `SOCK_SEQPACKET` mode socket

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
