### ISSUE TITLE
engine tags in older package.json

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-ipc#97]
Request for PR with engine tags and event pubsub versions in dependencies.

Please submit merge requests to appropriate branches.
- [ ] v1.x branch
- [ ] v2.x branch
- [ ] v4.x branch
- [ ] v5.x branch
- [ ] v6.x branch
- [ ] v7.x branch

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
